In [1]:
import pandas as pd
from db import MyDB

In [2]:
db = MyDB()

#### 데이터 필터링

In [3]:
query_1 = """
    SELECT * FROM `emp`
"""

sql_result = db.sql_query(query_1)
# sql_result: 리스트 안에 딕셔너리

In [4]:
emp_df = pd.DataFrame(sql_result)
emp_df

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
7    7788   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
8    7839    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
10   7876   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0
11   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [12]:
emp_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   EMPNO     14 non-null     int64
 1   ENAME     14 non-null     str
 2   JOB       14 non-null     str
 3   MGR       14 non-null     float64
 4   HIREDATE  14 non-null     str
 5   SAL       14 non-null     float64
 6   COMM      14 non-null     float64
 7   DEPTNO    14 non-null     float64
dtypes: float64(4), int64(1), str(3)
memory usage: 1.0 KB

In [6]:
# read_csv() 함수를 이용하여 csv 파일 로드

emp_df2 = pd.read_csv("../csv/emp.csv")
emp_df2

     EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7369.0   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
1   7499.0   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2   7521.0    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3   7566.0   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4   7654.0  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5   7698.0   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6   7782.0   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
7   7788.0   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
8   7839.0    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
9   7844.0  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
10  7876.0   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0
11  7900.0   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
12  7902.0    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
13  7934.0  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [8]:
dept_df = pd.read_csv('../csv/dept.csv')
dept_df

   DEPTNO       DNAME       LOC
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [9]:
query_2 = """
    SELECT * FROM `dept`
"""

pd.DataFrame(db.sql_query(query_2))

접속된 서버가 존재함

   DEPTNO       DNAME       LOC
0    10.0  ACCOUNTING  NEW YORK
1    20.0    RESEARCH    DALLAS
2    30.0       SALES   CHICAGO
3    40.0  OPERATIONS    BOSTON

In [11]:
# emp_df 에서 SAL 컬럼의 데이터가 1500 이상인 사원의 모든 정보를 확인

emp_df[emp_df['SAL'] >= 1500]

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0    0.0    20.0
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0    0.0    30.0
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
7    7788   SCOTT    ANALYST  7566.0  1987-06-28  3000.0    0.0    20.0
8    7839    KING  PRESIDENT     0.0  1981-11-17  5000.0    0.0    10.0
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0    0.0    20.0

In [13]:
emp_df.loc[emp_df['SAL'] >= 1500, ]

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0    0.0    20.0
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0    0.0    30.0
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
7    7788   SCOTT    ANALYST  7566.0  1987-06-28  3000.0    0.0    20.0
8    7839    KING  PRESIDENT     0.0  1981-11-17  5000.0    0.0    10.0
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0    0.0    20.0

In [16]:
query_3 = """
    SELECT *
    FROM `emp`
    WHERE SAL >= 1500
"""

emp_filter = db.sql_query(query_3)
pd.DataFrame(emp_filter)

접속된 서버가 존재함

   EMPNO   ENAME        JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
0   7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
1   7566   JONES    MANAGER  7839.0  1981-04-02  2975.0    0.0    20.0
2   7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0    0.0    30.0
3   7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
4   7788   SCOTT    ANALYST  7566.0  1987-06-28  3000.0    0.0    20.0
5   7839    KING  PRESIDENT     0.0  1981-11-17  5000.0    0.0    10.0
6   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0
7   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0    0.0    20.0

In [26]:
# pandas 버전
# SAL이 1500 이상이고, JOB이 MANAGER인 사원의 사원번호와 이름을 출력

flag_1 = emp_df['SAL'] >= 1500
flag_2 = emp_df['JOB'] == 'MANAGER'
col_flag = ['EMPNO', 'ENAME']

# emp_df.loc[[flag_1, flag_2], ['EMPNO', 'ENAME']]
emp_df.loc[ flag_1 & flag_2, col_flag]

   EMPNO  ENAME
3   7566  JONES
5   7698  BLAKE
6   7782  CLARK

In [25]:
# sql 버전

query_4 = """
    SELECT EMPNO, ENAME
    FROM `emp`
    WHERE SAL >= 1500 AND JOB = 'MANAGER'
"""

pd.DataFrame(db.sql_query(query_4))

접속된 서버가 존재함

   EMPNO  ENAME
0   7566  JONES
1   7698  BLAKE
2   7782  CLARK

In [27]:
# sql 버전
# SAL 1500 이상 2500 이하인 사원의 모든 정보 확인

query_5 = """
    SELECT *
    FROM `emp`
    WHERE SAL BETWEEN 1500 AND 2500
"""

pd.DataFrame(db.sql_query(query_5))

접속된 서버가 존재함

   EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
0   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
1   7782   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
2   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [28]:
# pandas 버전 1
# 인덱스 조건 SAL이 1500 이상 & 2500 이하

flag_3 = emp_df['SAL'] >= 1500
flag_4 = emp_df['SAL'] <= 2500

emp_df.loc[flag_3 & flag_4, ]

   EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
6   7782   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
9   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [29]:
# pandas 버전 2
# 존재 여부 is, 포함되어 있는가 in

emp_df.loc[
    emp_df['SAL'].isin(range(1500,2501)),
]

   EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
6   7782   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
9   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [31]:
# pandas 버전 3
# 사잇값: between()

emp_df.loc[
    emp_df['SAL'].between(1500, 2500)
]       # 종료값 포함

   EMPNO   ENAME       JOB     MGR    HIREDATE     SAL   COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0  300.0    30.0
6   7782   CLARK   MANAGER  7839.0  1981-06-09  2450.0    0.0    10.0
9   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0    0.0    30.0

In [33]:
# JOB이 MANAGER 이거나 SALESMAN인 경우 모든 사원 정보를 확인

query_6 = """
    SELECT *
    FROM `emp`
    WHERE JOB in ('MANAGER', 'SALESMAN')
"""

pd.DataFrame(db.sql_query(query_6))

접속된 서버가 존재함

   EMPNO   ENAME       JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
1   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
2   7566   JONES   MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
3   7654  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
4   7698   BLAKE   MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
5   7782   CLARK   MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
6   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0

In [34]:
# 계속 pd.DataFrame 쓰는 거 귀찮아서 만드는 함수

def sql(query):
    result = pd.DataFrame(
        db.sql_query(query)
    )

    return result

In [35]:
# pandas
# JOB이 MANAGER 이거나 SALESMAN인 경우 모든 사원 정보를 확인

flag_5 = emp_df['JOB'] == 'MANAGER'
flag_6 = emp_df['JOB'] == 'SALESMAN'

emp_df.loc[flag_5 | flag_6, ]

   EMPNO   ENAME       JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3   7566   JONES   MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5   7698   BLAKE   MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6   7782   CLARK   MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
9   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0

In [39]:
flag_7 = emp_df['JOB'].isin(['MANAGER', 'SALESMAN'])
emp_df.loc[flag_7,]

   EMPNO   ENAME       JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2   7521    WARD  SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
3   7566   JONES   MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5   7698   BLAKE   MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6   7782   CLARK   MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
9   7844  TURNER  SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0

In [73]:
# 사원의 이름이 S로 시작하는 사람

query_7 = """
    SELECT *
    FROM `multicam`.`emp`
    WHERE ENAME LIKE "%%s%%"
"""

sql(query_7)

접속된 서버가 존재함

   EMPNO  ENAME      JOB     MGR    HIREDATE     SAL  COMM  DEPTNO
0   7369  SMITH    CLERK  7902.0  1980-12-17   800.0   0.0    20.0
1   7566  JONES  MANAGER  7839.0  1981-04-02  2975.0   0.0    20.0
2   7788  SCOTT  ANALYST  7566.0  1987-06-28  3000.0   0.0    20.0
3   7876  ADAMS    CLERK  7788.0  1987-07-13  1100.0   0.0    20.0
4   7900  JAMES    CLERK  7698.0  1981-12-03   950.0   0.0    30.0

In [65]:
# pandas
# 시작하는 경우

word = 's'

flag_list = []

for name in emp_df['ENAME']:
    flag_list.append(
        name.lower().startswith(word.lower())
    )

emp_df.loc[flag_list,]

   EMPNO  ENAME      JOB     MGR    HIREDATE     SAL  COMM  DEPTNO
0   7369  SMITH    CLERK  7902.0  1980-12-17   800.0   0.0    20.0
7   7788  SCOTT  ANALYST  7566.0  1987-06-28  3000.0   0.0    20.0

In [68]:
# pandas
# 포함하는 경우

word = 's'

flag_list = []

for name in emp_df['ENAME']:
    flag_list.append(
        word.lower() in name.lower()
    )

emp_df.loc[flag_list,]

    EMPNO  ENAME      JOB     MGR    HIREDATE     SAL  COMM  DEPTNO
0    7369  SMITH    CLERK  7902.0  1980-12-17   800.0   0.0    20.0
3    7566  JONES  MANAGER  7839.0  1981-04-02  2975.0   0.0    20.0
7    7788  SCOTT  ANALYST  7566.0  1987-06-28  3000.0   0.0    20.0
10   7876  ADAMS    CLERK  7788.0  1987-07-13  1100.0   0.0    20.0
11   7900  JAMES    CLERK  7698.0  1981-12-03   950.0   0.0    30.0

In [71]:
# pandas for문 없이

word = 's'

flag_8 = emp_df['ENAME'].str.lower().str.startswith(word.lower())

emp_df.loc[flag_8,]

# 끝나는 경우는 endswith

   EMPNO  ENAME      JOB     MGR    HIREDATE     SAL  COMM  DEPTNO
0   7369  SMITH    CLERK  7902.0  1980-12-17   800.0   0.0    20.0
7   7788  SCOTT  ANALYST  7566.0  1987-06-28  3000.0   0.0    20.0

In [72]:
word = 's'

flag_8 = emp_df['ENAME'].str.lower().str.contains(word.lower())

emp_df.loc[flag_8,]

    EMPNO  ENAME      JOB     MGR    HIREDATE     SAL  COMM  DEPTNO
0    7369  SMITH    CLERK  7902.0  1980-12-17   800.0   0.0    20.0
3    7566  JONES  MANAGER  7839.0  1981-04-02  2975.0   0.0    20.0
7    7788  SCOTT  ANALYST  7566.0  1987-06-28  3000.0   0.0    20.0
10   7876  ADAMS    CLERK  7788.0  1987-07-13  1100.0   0.0    20.0
11   7900  JAMES    CLERK  7698.0  1981-12-03   950.0   0.0    30.0

#### 데이터 결합

##### join

emp와 dept 결합

In [74]:
# sql query

query_8 = """
    SELECT *
    FROM emp
        LEFT JOIN dept
            ON emp.DEPTNO = dept.DEPTNO
"""

sql(query_8)

접속된 서버가 존재함

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,dept.DEPTNO,DNAME,LOC
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20.0,20.0,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30.0,30.0,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30.0,30.0,SALES,CHICAGO
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20.0,20.0,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30.0,30.0,SALES,CHICAGO
5,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30.0,30.0,SALES,CHICAGO
6,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK
7,7788,SCOTT,ANALYST,7566.0,1987-06-28,3000.0,0.0,20.0,20.0,RESEARCH,DALLAS
8,7839,KING,PRESIDENT,0.0,1981-11-17,5000.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK
9,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,30.0,SALES,CHICAGO
10,7876,ADAMS,CLERK,7788.0,1987-07-13,1100.0,0.0,20.0,20.0,RESEARCH,DALLAS
11,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30.0,30.0,SALES,CHICAGO
12,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20.0,20.0,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK

In [75]:
pd.merge(emp_df, dept_df, on='DEPTNO', how='left')

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DNAME,LOC
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20.0,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30.0,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30.0,SALES,CHICAGO
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20.0,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30.0,SALES,CHICAGO
5,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30.0,SALES,CHICAGO
6,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10.0,ACCOUNTING,NEW YORK
7,7788,SCOTT,ANALYST,7566.0,1987-06-28,3000.0,0.0,20.0,RESEARCH,DALLAS
8,7839,KING,PRESIDENT,0.0,1981-11-17,5000.0,0.0,10.0,ACCOUNTING,NEW YORK
9,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,SALES,CHICAGO
10,7876,ADAMS,CLERK,7788.0,1987-07-13,1100.0,0.0,20.0,RESEARCH,DALLAS
11,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30.0,SALES,CHICAGO
12,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20.0,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10.0,ACCOUNTING,NEW YORK

In [76]:
dept_df2 = dept_df.copy()

In [78]:
dept_df2.rename(
    columns={
        'DEPTNO' : 'DEPTNUM'
    }, inplace=True
)

In [ ]:
# pd.merge(
#     emp_df, dept_df2, on='DEPTNO', how='left'
# )

In [80]:
pd.merge(
    emp_df, dept_df2, left_on='DEPTNO', right_on='DEPTNUM', how='left'
)

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,DEPTNUM,DNAME,LOC
0,7369,SMITH,CLERK,7902.0,1980-12-17,800.0,0.0,20.0,20.0,RESEARCH,DALLAS
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20,1600.0,300.0,30.0,30.0,SALES,CHICAGO
2,7521,WARD,SALESMAN,7698.0,1981-02-22,1250.0,500.0,30.0,30.0,SALES,CHICAGO
3,7566,JONES,MANAGER,7839.0,1981-04-02,2975.0,0.0,20.0,20.0,RESEARCH,DALLAS
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28,1250.0,1400.0,30.0,30.0,SALES,CHICAGO
5,7698,BLAKE,MANAGER,7839.0,1981-05-01,2850.0,0.0,30.0,30.0,SALES,CHICAGO
6,7782,CLARK,MANAGER,7839.0,1981-06-09,2450.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK
7,7788,SCOTT,ANALYST,7566.0,1987-06-28,3000.0,0.0,20.0,20.0,RESEARCH,DALLAS
8,7839,KING,PRESIDENT,0.0,1981-11-17,5000.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK
9,7844,TURNER,SALESMAN,7698.0,1981-09-08,1500.0,0.0,30.0,30.0,SALES,CHICAGO
10,7876,ADAMS,CLERK,7788.0,1987-07-13,1100.0,0.0,20.0,20.0,RESEARCH,DALLAS
11,7900,JAMES,CLERK,7698.0,1981-12-03,950.0,0.0,30.0,30.0,SALES,CHICAGO
12,7902,FORD,ANALYST,7566.0,1981-12-03,3000.0,0.0,20.0,20.0,RESEARCH,DALLAS
13,7934,MILLER,CLERK,7782.0,1982-01-23,1300.0,0.0,10.0,10.0,ACCOUNTING,NEW YORK

##### union

tran_1, tran_2 결합

In [81]:
query_9 = """
    SELECT * FROM `tran_1`
    UNION
    SELECT * FROM `tran_2`
"""

sql(query_9)

접속된 서버가 존재함

     transaction_id   price         payment_date customer_id
0       T0000000113  210000  2019-02-01 01:36:57    PL563502
1       T0000000114   50000  2019-02-01 01:37:23    HD678019
2       T0000000115  120000  2019-02-01 02:34:19    HD298120
3       T0000000116  210000  2019-02-01 02:47:23    IK452215
4       T0000000117  170000  2019-02-01 04:33:46    PL542865
...             ...     ...                  ...         ...
6781    T0000006894  180000  2019-07-31 21:20:44    HI400734
6782    T0000006895   85000  2019-07-31 21:52:48    AS339451
6783    T0000006896  100000  2019-07-31 23:35:25    OA027325
6784    T0000006897   85000  2019-07-31 23:39:35    TS624738
6785    T0000006898   85000  2019-07-31 23:41:38    AS834214

[6786 rows x 4 columns]

In [82]:
tran_1 = pd.read_csv('../csv/tran_1.csv')
tran_2 = pd.read_csv('../csv/tran_2.csv')
tran_d1 = pd.read_csv('../csv/tran_d_1.csv')
tran_d2 = pd.read_csv('../csv/tran_d_2.csv')

In [83]:
pd.concat([tran_1, tran_2], axis=0, ignore_index=True)

     transaction_id   price         payment_date customer_id
0       T0000000113  210000  2019-02-01 01:36:57    PL563502
1       T0000000114   50000  2019-02-01 01:37:23    HD678019
2       T0000000115  120000  2019-02-01 02:34:19    HD298120
3       T0000000116  210000  2019-02-01 02:47:23    IK452215
4       T0000000117  170000  2019-02-01 04:33:46    PL542865
...             ...     ...                  ...         ...
6781    T0000006894  180000  2019-07-31 21:20:44    HI400734
6782    T0000006895   85000  2019-07-31 21:52:48    AS339451
6783    T0000006896  100000  2019-07-31 23:35:25    OA027325
6784    T0000006897   85000  2019-07-31 23:39:35    TS624738
6785    T0000006898   85000  2019-07-31 23:41:38    AS834214

[6786 rows x 4 columns]

In [84]:
pd.concat([tran_1, tran_2], axis=0, ignore_index=True).rename(
    columns={
        'transaction_id':'거래고유번호',
        'price':'가격',
        'payment_date':'거래일자',
        'customer_id': '고객고유번호'
    }
)

           거래고유번호      가격                 거래일자    고객고유번호
0     T0000000113  210000  2019-02-01 01:36:57  PL563502
1     T0000000114   50000  2019-02-01 01:37:23  HD678019
2     T0000000115  120000  2019-02-01 02:34:19  HD298120
3     T0000000116  210000  2019-02-01 02:47:23  IK452215
4     T0000000117  170000  2019-02-01 04:33:46  PL542865
...           ...     ...                  ...       ...
6781  T0000006894  180000  2019-07-31 21:20:44  HI400734
6782  T0000006895   85000  2019-07-31 21:52:48  AS339451
6783  T0000006896  100000  2019-07-31 23:35:25  OA027325
6784  T0000006897   85000  2019-07-31 23:39:35  TS624738
6785  T0000006898   85000  2019-07-31 23:41:38  AS834214

[6786 rows x 4 columns]

In [86]:
query_10 = """
    SELECT
        transaction_id as 거래고유번호,
        price as 가격,
        payment_date as 거래일자,
        customer_id as 고객고유번호
    FROM `tran_1`
    UNION
    SELECT * FROM `tran_2`
"""

sql(query_10)

접속된 서버가 존재함

           거래고유번호      가격                 거래일자    고객고유번호
0     T0000000113  210000  2019-02-01 01:36:57  PL563502
1     T0000000114   50000  2019-02-01 01:37:23  HD678019
2     T0000000115  120000  2019-02-01 02:34:19  HD298120
3     T0000000116  210000  2019-02-01 02:47:23  IK452215
4     T0000000117  170000  2019-02-01 04:33:46  PL542865
...           ...     ...                  ...       ...
6781  T0000006894  180000  2019-07-31 21:20:44  HI400734
6782  T0000006895   85000  2019-07-31 21:52:48  AS339451
6783  T0000006896  100000  2019-07-31 23:35:25  OA027325
6784  T0000006897   85000  2019-07-31 23:39:35  TS624738
6785  T0000006898   85000  2019-07-31 23:41:38  AS834214

[6786 rows x 4 columns]

##### 다시 join

In [92]:
# tran_1과 tran_d_1 테이블을 조인 결합

query_11 = """
    SELECT
        t1.transaction_id,
        price,
        payment_date,
        quantity
    FROM
    `tran_1` `t1`
    LEFT JOIN
    `tran_d_1` `td1`
    ON
    t1.transaction_id = td1.transaction_id
"""

sql(query_11)

접속된 서버가 존재함

     transaction_id   price         payment_date  quantity
0       T0000000113  210000  2019-02-01 01:36:57       1.0
1       T0000000114   50000  2019-02-01 01:37:23       1.0
2       T0000000115  120000  2019-02-01 02:34:19       1.0
3       T0000000116  210000  2019-02-01 02:47:23       1.0
4       T0000000117  170000  2019-02-01 04:33:46       2.0
...             ...     ...                  ...       ...
5238    T0000005108  210000  2019-06-15 02:42:41       NaN
5239    T0000005109  150000  2019-06-15 03:36:16       NaN
5240    T0000005110   50000  2019-06-15 03:44:06       NaN
5241    T0000005111  210000  2019-06-15 04:14:06       NaN
5242    T0000005112   50000  2019-06-15 04:42:38       NaN

[5243 rows x 4 columns]

##### 정렬 방식

In [93]:
# sql
query_12 = """
    SELECT * FROM
    `emp` ORDER BY ENAME DESC
"""

sql(query_12)

접속된 서버가 존재함

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
1    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
2    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
3    7788   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
4    7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0
5    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
6    7839    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
7    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
8    7900   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
9    7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
10   7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
11   7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
12   7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
13   7876   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0

In [94]:
# pandas: sort_values()
emp_df.sort_values('ENAME', ascending=False)

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
0    7369   SMITH      CLERK  7902.0  1980-12-17   800.0     0.0    20.0
7    7788   SCOTT    ANALYST  7566.0  1987-06-28  3000.0     0.0    20.0
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
8    7839    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
3    7566   JONES    MANAGER  7839.0  1981-04-02  2975.0     0.0    20.0
11   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
12   7902    FORD    ANALYST  7566.0  1981-12-03  3000.0     0.0    20.0
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
10   7876   ADAMS      CLERK  7788.0  1987-07-13  1100.0     0.0    20.0

##### 그룹화

In [97]:
# sql
# SELECT 문에 그룹화 연산을 적어주어야 함.

query_13 = """
    SELECT
        JOB,
        AVG(SAL) AS SAL_AVG,
        SUM(SAL) AS SAL_SUM
    FROM `emp`
    GROUP BY JOB
"""

sql(query_13)

접속된 서버가 존재함

         JOB      SAL_AVG  SAL_SUM
0      CLERK  1037.500000   4150.0
1   SALESMAN  1400.000000   5600.0
2    MANAGER  2758.333333   8275.0
3    ANALYST  3000.000000   6000.0
4  PRESIDENT  5000.000000   5000.0

In [100]:
# pandas

emp_df[ ['JOB', 'SAL'] ].groupby('JOB').agg(['mean', 'sum', 'count'])

                   SAL
                  mean     sum count
JOB
ANALYST    3000.000000  6000.0     2
CLERK      1037.500000  4150.0     4
MANAGER    2758.333333  8275.0     3
PRESIDENT  5000.000000  5000.0     1
SALESMAN   1400.000000  5600.0     4

##### 서브쿼리

In [102]:
# 부서의 지역이 NEW YORK, CHICAGO인 부서의 번호를 받아서 사원의 정보를 확인

query_14 = """
    SELECT *
    FROM `emp`
    WHERE DEPTNO IN (10, 30)
"""

sql(query_14)

접속된 서버가 존재함

   EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
1   7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
2   7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
3   7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
4   7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
5   7839    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
6   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
7   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
8   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [104]:
query_15 = """
    SELECT DEPTNO
    FROM `dept`
    WHERE LOC IN ('NEW YORK', 'CHICAGO')
"""

sql(query_15)

접속된 서버가 존재함

   DEPTNO
0    10.0
1    30.0

In [105]:
query_16 = """
    SELECT *
    FROM `emp`
    WHERE DEPTNO IN
    (
        SELECT DEPTNO
        FROM `dept`
        WHERE LOC IN ('NEW YORK', 'CHICAGO')
    )
"""

sql(query_16)

접속된 서버가 존재함

   EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
0   7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
1   7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
2   7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
3   7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
4   7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
5   7839    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
6   7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
7   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
8   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

In [109]:
# pandas
# 부서 정보에서 LOC 컬럼이 뉴욕, 시카고인 부서의 번호를 추출

flag_9 = dept_df.loc[
    dept_df['LOC'].isin( ['NEW YORK', "CHICAGO"] ), 'DEPTNO'
]

In [110]:
emp_df.loc[emp_df['DEPTNO'].isin(flag_9), ]

    EMPNO   ENAME        JOB     MGR    HIREDATE     SAL    COMM  DEPTNO
1    7499   ALLEN   SALESMAN  7698.0  1981-02-20  1600.0   300.0    30.0
2    7521    WARD   SALESMAN  7698.0  1981-02-22  1250.0   500.0    30.0
4    7654  MARTIN   SALESMAN  7698.0  1981-09-28  1250.0  1400.0    30.0
5    7698   BLAKE    MANAGER  7839.0  1981-05-01  2850.0     0.0    30.0
6    7782   CLARK    MANAGER  7839.0  1981-06-09  2450.0     0.0    10.0
8    7839    KING  PRESIDENT     0.0  1981-11-17  5000.0     0.0    10.0
9    7844  TURNER   SALESMAN  7698.0  1981-09-08  1500.0     0.0    30.0
11   7900   JAMES      CLERK  7698.0  1981-12-03   950.0     0.0    30.0
13   7934  MILLER      CLERK  7782.0  1982-01-23  1300.0     0.0    10.0

##### Having

In [115]:
# 직종에서 ANALYST을 제외하고 직종별로 그룹화를 하여 SAL의 평균을 구한 뒤
# 평균의 값이 2500 이상인 데이터에서 평균 SAL이 높은 순서대로 출력
# sql


query_17 = """
    SELECT
        JOB,
        AVG(SAL) SAL_AVG
    FROM `emp`
    WHERE JOB != 'ANALYST'
    GROUP BY JOB
    HAVING SAL_AVG >= 2500
    ORDER BY SAL_AVG DESC
    
"""

sql(query_17)

접속된 서버가 존재함

         JOB      SAL_AVG
0  PRESIDENT  5000.000000
1    MANAGER  2758.333333

In [139]:
# pandas

emp_df3 = emp_df[emp_df['JOB'] != 'ANALYST']
emp_df4 = emp_df3.groupby('JOB')[['SAL']].mean()
emp_df4 = pd.DataFrame(emp_df4)
emp_df4
emp_df5 = emp_df4[emp_df4['SAL'] >= 2500]
emp_df5.sort_values('SAL', ascending=False).reset_index()

         JOB          SAL
0  PRESIDENT  5000.000000
1    MANAGER  2758.333333

In [137]:
emp_df3 = emp_df[emp_df['JOB'] != 'ANALYST']
emp_df3.groupby('JOB')[['SAL']].mean()

                   SAL
JOB
CLERK      1037.500000
MANAGER    2758.333333
PRESIDENT  5000.000000
SALESMAN   1400.000000

In [134]:
# 강사님 풀이

df = emp_df.loc[
    emp_df['JOB'] != 'ANALYST'
]

In [135]:
group_df = df[ ['JOB', 'SAL'] ].groupby('JOB').mean()

group_df

                   SAL
JOB
CLERK      1037.500000
MANAGER    2758.333333
PRESIDENT  5000.000000
SALESMAN   1400.000000

In [ ]:
group_df = group_df.loc[
    group_df['SAL'] >= 2500
]

In [132]:
group_df.sort_values('SAL', ascending=False).reset_index()

         JOB          SAL
0  PRESIDENT  5000.000000
1    MANAGER  2758.333333