#### **Pipeline**

- 여러 단계(전처리, 변환, 추정)를 연속적으로 연결하여 실행하는 도구
- 전처리 과정과 학습 모델을 하나의 객체로 결합하여 사용
- 교차검증(K-fold), 파라미터 탐색(GridSearch)에서 유용
- 데이터의 누수를 방지 : scaler를 사용하는 경우에는 train data만 fit, test는 transform


- **parameter**

    - `steps`
        - 필수 항목
        - 파이프라인의 단계들을 각각 별칭과 객체의 쌍으로 묶어서 list 형태로 구성
        - ex) [ ( 'scaler', StandardScaler() ), ('svm', SVC() ) ]
    
    - `verbose`
        - default : False
        - 각 step이 실행될 때 로그를 출력할 것인가? (진행 상황 표기)
    

- **속성**
    
    - `name_steps`
        - 파이프라인의 각 단계를 딕셔너리형처럼 접근하는 방법


- **메서드**

    - `fit(X, y, fit_params)`
        - 순서대로 각 단계의 fit() 실행

    - `fit_transform(X, y, fit_params)`
        - 순서대로 각 단계의 transform() 실행
    
    - `predict(X)`
        - 마지막 단계에서 만들어진 모델에 학습

In [3]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [2]:
iris = pd.read_csv('../csv/iris.csv')
iris.head(3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [4]:
le = LabelEncoder()
iris['species'] = le.fit_transform(iris['species'])
iris['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [5]:
X = iris.drop('species', axis = 1)
y = iris['species']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42, stratify = y
)

In [ ]:
# 파이프라인 생성 → 객체 생성

pipe = Pipeline(
    [
        ( 'scaler', StandardScaler() ),     # step 1
        ( 'model', SVC() )                  # step 2

    ], verbose = True
)

pipe

Pipeline(steps=[('sclaer', StandardScaler()), ('model', SVC())], verbose=True)

In [10]:
pipe.fit(X_train, y_train)

[Pipeline] ............ (step 1 of 2) Processing sclaer, total=   0.0s
[Pipeline] ............. (step 2 of 2) Processing model, total=   0.0s

Pipeline(steps=[('sclaer', StandardScaler()), ('model', SVC())], verbose=True)

In [12]:
pred = pipe.predict(X_test)

In [14]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

#### **GridSearchCV**

- hyper parameter 값들을 탐색하여 최적의 조합을 찾는 방법
- 각 parameter 조합별로 교차검증(CV)을 수행해 평균 성능을 비교
- 최적의 모델과 성능을 자동으로 제공


- **parameter**

    - `estimator`
        - 모델의 선택
        - 학습 모델, Pipeline
        - 고정 파라미터는 모델 선택 과정에서 지정
    
    - `param_grid`
        - 탐색할 parameter의 조합 (dict 형태)
        - ex
            - 학습 모델을 선택 : { 'C' : [0.1, 1, 10], 'kernel' : ['linear', 'rbf'] }
            - Pipeline을 선택 : { 'svm__C' : [0.1, 1, 10], 'svm__kernel' : ['linear', 'rbf']}

    - `scoring`
        - default : None
        - 평가 지표 설정
        - 회귀 모델에 성능 좋은 모델을 찾기 위해서는 neg_mse | mae (오차에 음수형으로 점수를 바꿔주는 작업)

    - `cv`
        - default : None
        - 교차 검증의 횟수
        - 5 → K-fold(5)
        - train, test set을 5회 생성 (회귀에서는 랜덤하게 폴드화 진행)
        - 분류 모델에서는 자동으로 StratifiedKFold가 사용됨 → 계층화 fold
        - Kfold() 입력값으로 사용 가능
    
    - `refit`
        - default : True
        - 최적의 parameter로 전체 데이터를 재학습할 것인가?
        - True로 사용 시 속성에서 best_estimator_ 을 이용하여 모델을 로드
        - False로 사용 시 속성에서 best_params_ 를 이용하여 최적의 parameter를 출력
    
    - `return_train_score`
        - default : False
        - 교차 검증시 훈련 성능 점수까지 반영할 것인가?
        - 호출 시 train_score과 test_score 모두 반환
            - 두 점수가 모두 높다면: Best
            - train 점수는 높고, test 점수는 낮다: 과적합
            - 두 점수가 모두 낮다면: 데이터 자체의 문제이거나 추가적인 튜닝이 필요
        
    - `n_jobs`
        - default : None
        - 병렬 처리할 CPU의 개수를 지정 (-1이면 모든 CPU를 사용)
    
    - `verbose`
        - default : 0
        - 0 : 모든 로그를 표시하지 않음
        - 1 : 로그를 축약하여 표시
        - 2 : 로그를 상세하게 표시
    
    - `error_score`
        - default : np.nan
        - 모델 학습 시 에러가 발생했을 때 점수를 어떻게 표현할 것인가?
    

- **속성**

    - `cv_results`
        - 각 parameter 조합별 성능의 결과 (train/test score, 학습(fit) 시간)
    
    - `best_estimator_`
        - 최적의 parameter로 재학습이 된 모델 객체
    
    - `best_params_`
        - 최적의 성능을 낸 parameter들의 조합
    
    - `best_score_`
        - 최적의 parameter로 조합된 모델의 CV 평균 성능
    
    - `refit_time_`
        - 재학습에 걸린 시간


- **메서드**

    - `fit()`
        - hyper parameter 조합별 CV 시작
    
    - `predict()`
        - 최적의 모델을 이용하여 예측
    
    - `predict_proba()`
        - 분류인 경우, 확률 예측

    - `score`
        - 최적인 모델의 점수를 출력

In [15]:
from sklearn.model_selection import GridSearchCV

In [36]:
# 검증
# SVC 모델 생성

svc = SVC()

# svc에서 사용할 매개변수의 목록들을 작성
grid_dict = {
    'C' : [ 0.1, 1, 10 ],
    'kernel' : [ 'linear', 'rbf' ],
    'gamma' : [ 'scale', 'auto' ]
}

grid = GridSearchCV(
    estimator = svc,
    param_grid = grid_dict,
    cv = 5,
    scoring = 'accuracy',
    verbose = 1,
)

In [37]:
grid_dict

{'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto']}

In [38]:
grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10], 'gamma': ['scale', 'auto'],
                         'kernel': ['linear', 'rbf']},
             scoring='accuracy', verbose=1)

In [39]:
print('최적의 파라미터 조합: ', grid.best_params_)
print('최적의 점수: ', grid.best_score_)
print('최적의 모델: ', grid.best_estimator_)

최적의 파라미터 조합:  {'C': 0.1, 'gamma': 'scale', 'kernel': 'linear'}
최적의 점수:  0.9833333333333334
최적의 모델:  SVC(C=0.1, kernel='linear')

#### K-Fold

- 데이터셋을 K개의 동일 크기 부분(Fold)으로 나눠서 K번 반복
    - 하나의 폴드를 검증용으로 사용, k-1개의 폴드를 학습용으로 사용
- 모든 폴더를 한번씩은 검증용으로 포함을 시켜서 성능을 안정적으로 평가할 수 있는 방법
- 데이터의 개수가 적은 경우 반복 실행 작업을 이용하여 성능을 안정적으로 평가

- **parameter**

    - `n_splits`
        - default : 5
        - 폴드의 개수를 지정
        - 최솟값은 2
    
    - `shuffle`
        - default : False
        - 데이터를 분할하기 전에 섞을지 지정
        - True로 변경하면 폴드 안 데이터가 랜덤하게 구성
    
    - `random_state`
        - default : None
        - `shuffle = True`일 때만 사용
        - 랜덤 시드를 고정
    

- **속성**

    - `n_splits`
        - 분할된 폴드의 개수
    

- **메서드**
    
    - `split(X, y = None)`
        - 학습용 검증용 인덱스를 생성
        - 반복문을 이용하여 (train_index, test_index)로 변환하여 사용


- **장점**
    - 데이터를 폴드화해서 학습/검증을 수행하기 때문에 데이터의 낭비가 없다.
    - train_test_split에 비해서 성능 평가 안정적
- **단점**
    - K번의 학습/예측/평가: 계산 횟수가 늘어난다 → 시간이 증가
    - 데이터의 규모가 커질수록 시간은 크게 증가

- 특수한 경우 변형 KFold 종류
    - StratifiedKFold : 분류 문제에서 클래스의 비율을 유지하며 분할
    - GroupKFold : 그룹 단위로 데이터를 나눠 특정 그룹으로 학습하고 다른 그룹으로 검증
    - RepeatedKFold : KFold를 여러번 반복해 평가 안정성 강화

In [44]:
import numpy as np
from sklearn.model_selection import KFold, StratifiedKFold

In [ ]:
X = np.array(
    ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']
)

# KFold
kfold = KFold(n_splits = 5)

list(kfold.split(X))

for train_idx, test_idx in kfold.split(X):
    print('-' * 60)
    print("학습 데이터의 목록: ", X[train_idx])
    print("검증 데이터의 목록: ", X[test_idx])

------------------------------------------------------------
학습 데이터의 목록:  ['C' 'D' 'E' 'F' 'G' 'H' 'I' 'J']
검증 데이터의 목록:  ['A' 'B']
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'E' 'F' 'G' 'H' 'I' 'J']
검증 데이터의 목록:  ['C' 'D']
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'C' 'D' 'G' 'H' 'I' 'J']
검증 데이터의 목록:  ['E' 'F']
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'C' 'D' 'E' 'F' 'I' 'J']
검증 데이터의 목록:  ['G' 'H']
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H']
검증 데이터의 목록:  ['I' 'J']

In [51]:
kfold = KFold(n_splits = 5, shuffle=True, random_state=42)

list(kfold.split(X))

for train_idx, test_idx in kfold.split(X):
    print('-' * 60)
    print("학습 데이터의 목록: ", X[train_idx])
    print("검증 데이터의 목록: ", X[test_idx])

------------------------------------------------------------
학습 데이터의 목록:  ['A' 'C' 'D' 'E' 'F' 'G' 'H' 'J']
검증 데이터의 목록:  ['B' 'I']
------------------------------------------------------------
학습 데이터의 목록:  ['B' 'C' 'D' 'E' 'G' 'H' 'I' 'J']
검증 데이터의 목록:  ['A' 'F']
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'D' 'E' 'F' 'G' 'I' 'J']
검증 데이터의 목록:  ['C' 'H']
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'C' 'D' 'F' 'G' 'H' 'I']
검증 데이터의 목록:  ['E' 'J']
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'C' 'E' 'F' 'H' 'I' 'J']
검증 데이터의 목록:  ['D' 'G']

In [54]:
y = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

for train_idx, test_idx in kfold.split(X):
    print('-' * 60)
    print("학습 데이터의 목록: ", X[train_idx])
    print("학습 정답의 목록: ", y[train_idx])
    print("검증 데이터의 목록: ", X[test_idx])
    print("검증 정답의 목록: ", y[test_idx])

------------------------------------------------------------
학습 데이터의 목록:  ['A' 'C' 'D' 'E' 'F' 'G' 'H' 'J']
학습 정답의 목록:  [0 2 3 4 5 6 7 9]
검증 데이터의 목록:  ['B' 'I']
검증 정답의 목록:  [1 8]
------------------------------------------------------------
학습 데이터의 목록:  ['B' 'C' 'D' 'E' 'G' 'H' 'I' 'J']
학습 정답의 목록:  [1 2 3 4 6 7 8 9]
검증 데이터의 목록:  ['A' 'F']
검증 정답의 목록:  [0 5]
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'D' 'E' 'F' 'G' 'I' 'J']
학습 정답의 목록:  [0 1 3 4 5 6 8 9]
검증 데이터의 목록:  ['C' 'H']
검증 정답의 목록:  [2 7]
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'C' 'D' 'F' 'G' 'H' 'I']
학습 정답의 목록:  [0 1 2 3 5 6 7 8]
검증 데이터의 목록:  ['E' 'J']
검증 정답의 목록:  [4 9]
------------------------------------------------------------
학습 데이터의 목록:  ['A' 'B' 'C' 'E' 'F' 'H' 'I' 'J']
학습 정답의 목록:  [0 1 2 4 5 7 8 9]
검증 데이터의 목록:  ['D' 'G']
검증 정답의 목록:  [3 6]

**Regression**

In [55]:
from sklearn.svm import SVR

In [56]:
X = iris.drop('species', axis = 1)
y = iris['species']

In [57]:
cv_fold = StratifiedKFold(shuffle=True, random_state=42)

In [58]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42, stratify = y
)

In [60]:
pipe = Pipeline(
    [
        ('scaler', StandardScaler()),
        ('clf', SVC(random_state=42, probability=True))
    ]
)

In [61]:
# clf에서 사용할 파라미터 조합 생성
# GridSearchCV에서 사용할 파라미터 조합 (별칭 _ _ 매개변수명)

params = {
    'clf__C' : [0.1, 1, 10],
    'clf__gamma' : ['scale', 'auto'],
    'clf__kernel' : ['linear', 'rbf']
}

In [62]:
grid_clf = GridSearchCV(
    estimator= pipe,                # 파이프라인으로 생성한 모델을 지정
    param_grid= params,             # dict 형태로 파라미터의 조합
    scoring = 'accuracy',           # 베스트 모델 선정 기준
    cv = cv_fold,                   # 생성해둔 KFold 지정
    refit = True,                   # 재학습 여부
    n_jobs = -1,                    # 모든 CPU를 사용
    return_train_score= True,       # 학습 데이터의 성능을 출력
    verbose = 2                     # 로그 표시를 상세하게
)

In [63]:
grid_clf.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('clf',
                                        SVC(probability=True,
                                            random_state=42))]),
             n_jobs=-1,
             param_grid={'clf__C': [0.1, 1, 10],
                         'clf__gamma': ['scale', 'auto'],
                         'clf__kernel': ['linear', 'rbf']},
             return_train_score=True, scoring='accuracy', verbose=2)

In [64]:
grid_clf.score(X_test, y_test)

0.9333333333333333

In [ ]:
grid_df = pd.DataFrame(grid_clf.cv_results_)
grid_df.sort_values('mean_test_score', ascending=False)

In [67]:
print(grid_clf.best_params_)

{'clf__C': 0.1, 'clf__gamma': 'scale', 'clf__kernel': 'linear'}

In [68]:
svc_final = SVC(C=0.1, gamma='scale', kernel='linear', random_state=42)

In [69]:
svc_final.fit(X_train, y_train)

SVC(C=0.1, kernel='linear', random_state=42)

In [70]:
pred = svc_final.predict(X_test)

In [71]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.90      0.95        10
           2       0.91      1.00      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

##### 연습

1. boston 데이터셋 로드
2. 독립변수, 종속변수로 데이터 분할
3. train, test 8:2
4. KFold 이용하여 10개의 폴드 생성 (shuffle True)
5. 파이프라인 생성 (StandardScaler(), SVR())
6. 파라미터 조합 생성 (svr 모델에서 C(1, 10, 100), kernel('linear', 'rbf'), epsilon(0.1, 0.2, 0.5))
7. GridSearchCV 베스트 모델 선정의 기준은 neg_mean_squared_error
8. 최고의 조합을 찾은 뒤 R2 score를 이용하여 성능을 확인
9. 최적의 파라미터를 이용하여 새로운 모델을 생성하고 성능 R2 score 확인

In [106]:
# 1)
boston = pd.read_csv('../csv/boston.csv')
boston.head(3)

      CRIM    ZN  INDUS  CHAS    NOX  ...    TAX  PTRATIO       B  LSTAT  Price
0  0.00632  18.0   2.31   0.0  0.538  ...  296.0     15.3  396.90   4.98   24.0
1  0.02731   0.0   7.07   0.0  0.469  ...  242.0     17.8  396.90   9.14   21.6
2  0.02729   0.0   7.07   0.0  0.469  ...  242.0     17.8  392.83   4.03   34.7

[3 rows x 14 columns]

In [107]:
# 2)
X = boston.drop('Price', axis = 1)
y = boston['Price']

In [108]:
# 3)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [109]:
# 4)
kfold = KFold(n_splits=10, shuffle=True, random_state=42)

In [110]:
# 5)
pipe = Pipeline(
    [
        ('scaler', StandardScaler()),
        ('reg', SVR())
    ]
)

In [111]:
params = {
    'reg__C' : [1, 10, 100],
    'reg__epsilon' : [0.1, 0.2, 0.5],
    'reg__kernel' : ['linear', 'rbf']
}

In [112]:
grid_reg = GridSearchCV(
    estimator= pipe,
    param_grid= params,
    scoring = 'neg_mean_squared_error',
    cv = kfold,
    refit = True,
    n_jobs = -1,
    return_train_score= True,
    verbose = 2
)

In [113]:
grid_reg.fit(X_train, y_train)

Fitting 10 folds for each of 18 candidates, totalling 180 fits

GridSearchCV(cv=KFold(n_splits=10, random_state=42, shuffle=True),
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('reg', SVR())]),
             n_jobs=-1,
             param_grid={'reg__C': [1, 10, 100],
                         'reg__epsilon': [0.1, 0.2, 0.5],
                         'reg__kernel': ['linear', 'rbf']},
             return_train_score=True, scoring='neg_mean_squared_error',
             verbose=2)

In [114]:
grid_reg.score(X_test, y_test)

-12.063990309898506

In [115]:
print(grid_reg.best_estimator_)

Pipeline(steps=[('scaler', StandardScaler()), ('reg', SVR(C=100, epsilon=0.5))])

In [116]:
pred = grid_reg.predict(X_test)

In [117]:
from sklearn.metrics import r2_score
print(round(r2_score(y_test, pred), 4))

0.8355