#### 웹 크롤링
- 라이브러리
    - requests
        - 웹 서버에 요청을 보내고 응답을 받는 기능
        - 응답 데이터는 bytes, string 형으로 들어온다.
    - bs4
        - BeautifulSoup class를 이용
        - html로 이루어진 문자 데이터를 pasing 작업을 통해서 데이터의 타입을 변경하여 내부의 데이터에 쉽게 접근하여 추출하기 위한 기능
            - `"<html><body><p>Text</p></body></html>"` : 태그를 기준으로 데이터에 접근할 수 있는 함수들이 존재
        - 웹의 기본 구조를 파악하고 사용하면 조금 더 쉽게 접근할 수 있음
            - 태그별 속성의 값
            - 태그의 특징
    - selenium
        - 웹 어플리케이션을 테스트하기 위한 라이브러리
        - 웹 브라우저(chrome, ...)를 python code로 제어
            - 함수를 이용해서 특정 버튼을 클릭
            - 특정 위치에 데이터를 입력
            - ex) 티켓팅 매크로 만들기 등...

- 데이터를 불법적으로 가지고 오는 방법(합법/위법 사이)
    - 사이트들마다 크롤링이 가능한 주소들은 지정되어 있음
    - 상업적인 용도가 아닌 수업에서의 내용은 큰 지장은 없음
    - open API를 추천
        - open API는 실시간으로 데이터가 올라오지 않음
        - 하지만 웹 화면은 실시간으로 데이터가 올라옴

In [1]:
# 라이브러리 설치
!pip install bs4 selenium

Requirement already satisfied: bs4 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (0.0.2)
Requirement already satisfied: selenium in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (4.43.0)
Requirement already satisfied: beautifulsoup4 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from bs4) (4.14.3)
Requirement already satisfied: certifi>=2026.1.4 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from selenium) (2026.2.25)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.6.3)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from selenium) (1.9.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (26.1.0)
Requirement already satisfied: sortedcontainers in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (3.0)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from beautifulsoup4->bs4) (2.8.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import requests
from bs4 import BeautifulSoup as bs

In [3]:
# requests 라이브러리를 이용해서 openapi에서는 데이터의 결과물이 xml, json 형태
# https://www.naver.com 에 요청을 보냈을 때 어떤 데이터를 줄 것인가?

res = requests.get("https://www.naver.com")

# requests.get() https 프로토콜을 이용해서 요청을 보낼 때 에러가 발생하는 경우 http 사용

In [4]:
res.content     # type: bytes

b'   <!doctype html> <html lang="ko" class="fzoom"> <head> <meta charset="utf-8"> <meta name="Referrer" content="origin"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=1190"> <title>NAVER</title> <meta name="apple-mobile-web-app-title" content="NAVER"/> <meta name="robots" content="index,nofollow"/> <meta name="description" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\xa9\x94\xec\x9d\xb8\xec\x97\x90\xec\x84\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xec\xa0\x95\xeb\xb3\xb4\xec\x99\x80 \xec\x9c\xa0\xec\x9a\xa9\xed\x95\x9c \xec\xbb\xa8\xed\x85\x90\xec\xb8\xa0\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x82\x98 \xeb\xb3\xb4\xec\x84\xb8\xec\x9a\x94"/> <meta property="og:title" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84"> <meta property="og:url" content="https://www.naver.com/"> <meta property="og:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta property="og:description" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\xa9\x94\xec\x9d\xb8\xec\x97\x90\xec\x84\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xec\xa0\x95\xeb\xb3\xb4\xec\x99\x80 \xec\x9c\xa0\xec\x9a\xa9\xed\x95\x9c \xec\xbb\xa8\xed\x85\x90\xec\xb8\xa0\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x82\x98 \xeb\xb3\xb4\xec\x84\xb8\xec\x9a\x94"/> <meta name="twitter:card" content="summary"> <meta name="twitter:title" content=""> <meta name="twitter:url" content="https://www.naver.com/"> <meta name="twitter:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta name="twitter:description" content="\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 \xeb\xa9\x94\xec\x9d\xb8\xec\x97\x90\xec\x84\x9c \xeb\x8b\xa4\xec\x96\x91\xed\x95\x9c \xec\xa0\x95\xeb\xb3\xb4\xec\x99\x80 \xec\x9c\xa0\xec\x9a\xa9\xed\x95\x9c \xec\xbb\xa8\xed\x85\x90\xec\xb8\xa0\xeb\xa5\xbc \xeb\xa7\x8c\xeb\x82\x98 \xeb\xb3\xb4\xec\x84\xb8\xec\x9a\x94"/> <meta name="google-site-verification" content="uru5NJKa1Bfr5nv5AdQ26Qat7UrPU_02l-PIZRLzI-g"/> <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?1"> <link rel="apple-touch-icon-precomposed" href="https://s.pstatic.net/static/www/nFavicon96.png"/> <link rel="apple-touch-icon" sizes="114x114" href="https://s.pstatic.net/static/www/u/2014/0328/mma_204243574.png"/> <link rel="apple-touch-icon" href="https://s.pstatic.net/static/www/u/2014/0328/mma_20432863.png"/> <link rel="stylesheet" href="https://ssl.pstatic.net/sstatic/search/pc/css/sp_autocomplete_260205.css"> <link rel="canonical" href="https://www.naver.com/"> <link rel="alternate" media="only screen and (max-width: 767px)" href="https://m.naver.com/"> <script>window.gladsdk=window.gladsdk||{},window.gladsdk.cmd=window.gladsdk.cmd||[],window.ndpsdk=window.ndpsdk||{},window.ndpsdk.cmd=window.ndpsdk.cmd||[],window.ndpsdk.polyfill=window.ndpsdk.polyfill||{cmd:[]};var g_ssc="navertop.v5";window.nsc=g_ssc,window.nmain=window.nmain||{},window.nmain.jsOrigin="www"</script> <script>window.ntm=window.ntm||[]</script> <script async src="https://ssl.pstatic.net/tveta/libs/ndpsdk/prod/ndp-loader.js"></script> <script async src="https://ssl.pstatic.net/tveta/libs/glad/prod/gfp-core.js"></script> <script src="https://ssl.pstatic.net/tveta/libs/assets/js/pc/main/min/pc.veta.core.min.js" defer="defer"></script>  <script>\nwindow["EAGER-DATA"] = window["EAGER-DATA"] || {};\nwindow["EAGER-DATA"]["PC-FEED-WRAPPER"] = {"@type":"BLOCK","blocks":[{"@type":"BLOCK","blocks":[{"@type":"PC-FEED-BLOCK","excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-HEALTH-TOP","@template":"HIGHLIGHTED-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"\xe2\x80\x986kg \xea\xb0\x90\xeb\x9f\x89\xe2\x80\x99 \xec\xb5\x9c\xea\xb0\x95\xed\x9d\xac, \xec\x9a\x94\xec\x9a\x94 \xec\x99\x94\xeb\x8b\xa4\xe2\x80\xa6\xe2\x80\x9c\xe2\x80\x98\xec\x9d\xb4\xea\xb2\x83\xe2\x80\x99 \xeb\x81\x8a\xec\x9e\x90 \xec\x8b\x9d\xec\x9a\x95 \xed\x8f\xad\xeb\xb0\x9c\xe2\x80\x9d \xeb\xad\x98\xea\xb9\x8c?","url":"https://n.news.naver.com/article/296/0000099718","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F296%2F2026%2F04%2F20%2F0000099718_001_20260420150615768.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://media.naver.com/press/296","name":"\xec\xbd\x94\xeb\xa9\x94\xeb\x94\x94\xeb\x8b\xb7\xec\xbb\xb4","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fmimgnews%2Fimage%2Fupload%2Foffice_logo%2F296%2F2025%2F03%2F07%2Flogo_296_100_20250307145636.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a642"},{"@type":"MATERIAL-PC-FEED","title":"\xe2\x80\x9c44kg \xeb\xba\x90\xeb\x8a\x94\xeb\x8d\xb0 \xeb\x8b\xa4\xec\x8b\x9c \xec\xaa\x98\xeb\x8b\xa4\xe2\x80\x9d\xe2\x80\xa6\xea\xb9\x80\xec\x8b\xa0\xec\x98\x81\xec\x9d\xb4 \xec\x9a\x94\xec\x9a\x94\xeb\xa5\xbc \xec\x9d\xb8\xec\xa0\x95\xed\x95\x9c \xec\xa7\x84\xec\xa7\x9c \xec\x9d\xb4\xec\x9c\xa0","url":"https://blog.naver.com/hitthemoney/224243472916","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDdfMTM1%2FMDAxNzc1NTE3NjEzODQy.OSS63kTplYBOjinBJCEN8gvq-fZReEqF3niUSIVktG0g.inRS9KqjJ61fbjwcUlZ5RsQdBQVC9sWS6s_fLBlOK1wg.JPEG%2FIMG%EF%BC%BF2334.JPG%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/hitthemoney","name":"\xeb\xa8\xb8\xeb\x8b\x88\xed\x8c\x8c\xec\x88\x98\xea\xbe\xbc","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNjAzMjJfMjc5%2FMDAxNzc0MTc5ODY2NTI5.k14NNHxzpnwm7UZ28B4x62phG0scx2ogCwkLn_AtBPsg.7nSc9ferAD8KPnatbylpkTr2MoJUlyCD722SYou0KMMg.PNG%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a643"},{"@type":"MATERIAL-PC-FEED","title":"\xec\x97\xb0\xec\xb0\xa8 \xec\x93\xb0\xea\xb3\xa0 \xed\x95\x9c\xea\xb0\x95 10km \xeb\x9b\xb0\xeb\x8a\x94 \xec\x97\xac\xec\x9e\x90, \xec\xa0\x9c\xeb\xb2\x95 \xeb\xa9\x8b\xec\xa0\xb8\xec\x9a\x94","url":"https://blog.naver.com/kudayz/224245568968","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDhfMTMz%2FMDAxNzc1NjQwNjcxOTc1.VTJq-YEL6hBxYtkPAnoQpABIP2mOlJpXkXCS9rk64JAg.mLAjg_RU4cWS0-Z67DDtyPkJ2G_ENaQqPmuiP1WAJosg.JPEG%2FKakaoTalk_20260408_182909640_07.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/kudayz","name":"\xec\xbf\xa0\xec\xa3\xbc","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNDA3MzFfMjAw%2FMDAxNzIyNDA0NDg2MDI3.PTtDS5ubTyHKXUYEkUvjANqMg_wfVHWCzBsDN14V9vAg.hBh1VUUqip_xkWbhTL-m2Y-1NVzaPc7OnT4Wyztg7vgg.JPEG%2FKakaoTalk_20240731_144059728.jpg%2FKakaoTalk_20240731_144059728.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a644"},{"@type":"MATERIAL-PC-FEED","title":"\xea\xb9\x80\xec\xa7\x80\xec\x9b\x90 \xeb\x93\x9c\xeb\xa0\x88\xec\x8a\xa4 \xeb\xaa\xb8\xeb\xa7\xa4 \xec\xb6\xa9\xea\xb2\xa9 \xea\xb7\xbc\xed\x99\xa9 \xe2\x80\x98\xec\x9d\xb4 \xec\x9d\x8c\xec\x8b\x9d\xe2\x80\x99 \xeb\x81\x8a\xea\xb3\xa0 \xeb\x8b\xa4\xec\x9d\xb4\xec\x96\xb4\xed\x8a\xb8 \xec\x84\xb1\xea\xb3\xb5","url":"https://in.naver.com/jinny/contents/internal/942409049184032","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTZfMjYx%2FMDAxNzc2MzE2OTUyMDg3.hhnC_qTYCdUXrieu5CRCM85KTGDo225kSMJlZ1HU9Nog.1JXQFCpn8qa3tZMVYjcrJDs9qZl8-Ig1FQ8s39Ex2dcg.JPEG%2Foutput%EF%BC%BF3911620217.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/supia2728","name":"\xec\xa7\x80\xeb\x8b\x88\xec\xb8\x84","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMjExMTNfOTYg%2FMDAxNjY4MjkzNzY3Njgx.OQzhh0AnLRkjro1VKIHYW59ieYCVvcuj-ZERbN5N_fYg.ByZj2jmt2fJGcoU3x1Asl4Zc7uZ-beBL3z5wsh9rflsg.PNG.supia2728%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a645"},{"@type":"MATERIAL-PC-FEED","title":"\xec\xa4\x91\xeb\x85\x84 \xeb\xb1\x83\xec\x82\xb4 \xeb\xb9\xbc\xeb\x8a\x94 \xec\xb5\x9c\xea\xb3\xa0\xec\x9d\x98 \xec\xb9\xbc\xeb\xa1\x9c\xeb\xa6\xac \xed\x8f\xad\xed\x8c\x8c \xec\x9a\xb4\xeb\x8f\x99","url":"https://tv.naver.com/h/98114587","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260420_165%2FE6VpH_1776690761468Osm7w_JPEG%2F82PN94LM69_03.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://tv.naver.com/impt","name":"\xec\x9e\x84\xed\x94\xbc\xed\x8b\xb0IMPT","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20240603_37%2FR5xey_1717410445431SxjBX_PNG%2F1717410445403.png%22&type=nf40_40&service=navermain"}},"video":{"playTime":"01:23"},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a646"},{"@type":"MATERIAL-PC-FEED","title":"\xeb\xb0\xa5 \xeb\xa8\xb9\xec\x9c\xbc\xeb\xa9\xb4\xec\x84\x9c 17kg \xeb\xba\x80 \xec\x86\xa1\xed\x98\x9c\xea\xb5\x90! \xeb\x8b\xa4\xec\x9d\xb4\xec\x96\xb4\xed\x8a\xb8 \xec\x8b\x9d\xeb\x8b\xa8\xea\xb3\xbc \xec\xa0\x88\xeb\x8c\x80 \xeb\xa8\xb9\xec\xa7\x80 \xec\x95\x8a\xeb\x8a\x94\xeb\x8b\xa4\xeb\x8a\x94 \\"\xec\x9d\xb4\xea\xb2\x83\\"","url":"https://in.naver.com/runddungja/contents/internal/936562286598464","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAzMzFfOTMg%2FMDAxNzc0OTUyNzgzMTEw.Fj9-rcwnY5opqHy3NZ1UZJ6YIOHg-qwEh8jfe4w4rE4g.ImbOCv714r9OcavaWyly499hep5mVoFnukehaNlCOH8g.PNG%2F%EB%95%85%EC%BD%A9%EB%B2%84%ED%84%B0_%28100%29.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/hhj1004w","name":"\xec\xab\x91\xec\x95\x8c\xec\xab\x91\xec\x95\x8c","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMDA5MThfMTc2%2FMDAxNjAwNDA3NTg3MzQ3.iGpQ5T6XITV6FbArPATdBHGrjBrmXQ0MDuLRkohd1zEg.BqmIcUyg1sGNNopgsTiKI8FaFrrIAPR-uXQdj61UHSsg.PNG.hhj1004w%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a647"},{"@type":"MATERIAL-PC-FEED","title":"\xea\xb4\x9c\xec\xb0\xae\xea\xb2\xa0\xec\xa7\x80 \xed\x96\x88\xeb\x8b\xa4\xea\xb0\x80 \xea\xb2\xb0\xea\xb5\xad \'\xec\x9e\xac\xea\xb2\x80\xec\x82\xac\' \xeb\x8c\x80\xec\x9e\xa5\xeb\x82\xb4\xec\x8b\x9c\xea\xb2\xbd \xec\xa0\x84\xeb\x82\xa0 \xec\x9d\x8c\xec\x8b\x9d 3\xec\x9d\xbc\xec\xa0\x84 \xec\x8b\x9d\xec\x82\xac \xed\x95\xb5\xec\x8b\xac","url":"https://in.naver.com/sudy_ys/contents/internal/936119519512256","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAzMzBfMjMz%2FMDAxNzc0ODQ1NTI5MzIx.AYQSubgB94l4d7tGwrfz0s8rprUsRFHI-n-gmroIqMQg.rHXpQbrAGYYynLMg0zzNarSjvKsNI0hpLeLu4qRmJZwg.PNG%2FDesign_-_2026-03-30T133846.147.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/sudy_ys","name":"\xec\x9c\xa4\xec\x8a\xac\xeb\xa7\x98","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTAyMTFfOCAg%2FMDAxNzM5MjUxNzQ4MTc4.nHWZf-bSsmybn_ETM3kF83mO5f1A5cLUmf_oz1eYqNIg.j8fTqwQMqo8ePEEiQxhHZOI5Z9xYyxvAIH_SyqZ9p28g.PNG%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a648"},{"@type":"MATERIAL-PC-FEED","title":"\xed\x99\x94\xec\x82\xac \xec\x99\x9c \xec\x9d\xb4\xeb\xa0\x87\xea\xb2\x8c \xeb\xa7\x90\xeb\x9e\x90\xeb\x82\x98? \xeb\xbc\x88\xeb\xa7\x90\xeb\x9d\xbc\xec\x9d\xb8\xeb\x8d\xb0 \xea\xb7\xbc\xec\x9c\xa1 \xec\x9e\x88\xeb\x8b\xa4, \xeb\xaa\xb8\xeb\xa7\xa4 \xeb\xb3\x80\xed\x99\x94 \xeb\xa7\x8c\xeb\x93\xa0 \xec\x8b\x9d\xeb\x8b\xa8 \xec\x9d\xb4\xec\x9c\xa0","url":"https://in.naver.com/kimyeonwooxo/contents/internal/941892921939840","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTVfMjky%2FMDAxNzc2MjUwMDUyMjU3.KPrN3OrekUp_4teAuWp_ssDVGHYwprzRbUyzufNUvcsg.LyV5NTsCXPbyyECrct3BhxMVg3VfxOqr0LkhoKR08dkg.JPEG%2FIMG%EF%BC%BF6920.JPG%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/kimyeonwooxo","name":"\xec\x97\xb0\xec\xb9\x98\xec\xbd\x94\xec\xb9\x98","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNjAzMjVfMTkg%2FMDAxNzc0NDM2NTUzNDEz.gjPbtSOuYbM8hanUc_vKDzztS_sQIbMUTwoTOBih64sg.BvToyyU6whIsHTr9Bpz_tdt6o_rajqzAfBKPf86P4Jog.JPEG%2FprofileImage.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a649"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-HEALTH-AIRS-PAGE-1","@template":"TWO-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"[\xea\xb4\x91\xea\xb3\xa0] \xeb\x94\xb1 3\xec\x9d\xbc \xec\xa0\x80\xeb\x85\x81\xec\x9c\xbc\xeb\xa1\x9c \xec\x9d\xb4\xea\xb1\xb0 \xeb\xa8\xb9\xec\x9c\xbc\xeb\xa9\xb4 \xeb\xb1\x83\xec\x82\xb4 \xec\xa0\x9c\xeb\x8c\x80\xeb\xa1\x9c \xeb\xb9\xa0\xec\xa7\x88\xeb\x93\xaf\xf0\x9f\xa4\xad  \xec\xa4\x84\xec\x84\x9c\xec\x84\x9c \xeb\xa8\xb9\xeb\x8a\x94\xeb\x8b\xa4\xeb\x8a\x94 \xec\x95\x84\xec\x82\xac\xec\x9d\xb4\xeb\xb3\xbc \xec\x82\xac\xeb\xa8\xb9\xec\xa7\x80\xeb\xa7\x88\xec\x8b\x9c\xea\xb3\xa0 \xec\x9d\xb4\xeb\xa0\x87\xea\xb2\x8c \xeb\xa7\x8c\xeb\x93\xa4\xec\x96\xb4 \xeb\x93\x9c\xec\x84\xb8\xec\x9a\x94  \xed\x8c\x8c\xeb\x8a\x94 \xea\xb2\x83 \xeb\xb3\xb4\xeb\x8b\xa4 \xeb\x8b\xb9\xeb\xa5\x98\xeb\x8f\x84 \xed\x9b\xa8\xec\x94\xac \xec\xa0\x81\xea\xb3\xa0 \xec\x8b\xb8\xec\x9a\x94\xf0\x9f\xa4\x93  \xec\x9c\xa0\xea\xb8\xb0\xeb\x86\x8d \xec\xbd\x94\xec\xbd\x94\xeb\x84\x88\xec\xb9\xa9&\xeb\xb0\x94\xeb\x82\x98\xeb\x82\x98\xec\xb9\xa9 \xeb\x93\xac\xeb\xbf\x8d \xeb\x93\xa4\xec\x96\xb4\xea\xb0\x84  \xec\xbd\x94\xec\xbd\x94\xec\x95\x84\xeb\xaa\xac\xeb\x93\x9c\xeb\xb2\x84\xed\x84\xb0\xf0\x9f\xa5\xa5\xf0\x9f\x8d\x8c\xf0\x9f\xa5\x9c \xec\x97\x90 \xec\x98\xac\xeb\xa6\xac\xea\xb3\xa0\xeb\x8b\xb9\xeb\xa7\x8c \xec\x82\xb4\xec\xa7\x9d \xec\x96\xb9\xec\x97\x88\xeb\x8a\x94\xeb\x8d\xb0  \xeb\x84\x88\xeb\xac\xb4 \xeb\xa7\x9b\xec\x9e\x88\xeb\x84\xa4\xec\x9a\x94.....\xf0\x9f\xab\x90  \xec\x9a\x94 \xec\xbd\x94\xec\xbd\x94\xeb\xb0\x94\xeb\x82\x98\xeb\x82\x98\xec\x95\x84\xeb\xaa\xac\xeb\x93\x9c \xeb\xb2\x84\xed\x84\xb0 \xeb\xb6\x80\xeb\xa1\x9c\xeb\x94\x94\xec\x97\x90\xec\x84\x9c\xeb\xa7\x8c \xeb\xa8\xb9\xec\x96\xb4\xeb\xb3\xbc\xec\x88\x98 \xec\x9e\x88\xeb\x8a\x94\xeb\x8d\xb0   \xf0\x9f\x87\xba\xf0\x9f\x87\xb8\xeb\xaf\xb8\xea\xb5\xad \xec\x9c\xa0\xea\xb8\xb0\xeb\x86\x8d\xec\x9d\xb8\xec\xa6\x9d ","url":"https://m.naver.com/shorts?serviceType=CLIP&mediaType=VOD&seedMediaId=1540F1B56E738ED6779FC3DADB16946B8A38&recType=CLIP_PC&recId=%7B%22targetProfileId%22%3A%22tonylove1206%22%2C%22open%22%3Atrue%7D","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fclip-service-phinf.pstatic.net%2FMjAyNjA0MjFfMjUy%2FMDAxNzc2Njk3ODA3Njkz.UwuEvVIuRJJUiMJOIn-0UHcU9W0794nXHERPjf2Uxjsg.TATdwoIQ04Ie6dks1F48eyuqCeEDBU_htpsJwwzd878g.JPEG%2FPublishThumb_20260421_000426_430.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://clip.naver.com/@body_theory","name":"bodytheory","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fclip-service-phinf.pstatic.net%2FMjAyNTA4MjVfMTU4%2FMDAxNzU2MDk2NTM5NDg3.t5dYB1JLUIbtZojgqAu0FVx4JTVKqYrbGxGM86Y9CI0g.G3heVo9VZEwQ5KIV2OhERTjkRGDmDGgFT6tAu5lqJxQg.JPEG%2Fimage.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:18"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cbe"},{"@type":"MATERIAL-PC-FEED","title":"\xeb\x8b\xa4\xec\x9d\xb4\xec\x96\xb4\xed\x8a\xb8\xec\x8b\x9d\xeb\x8b\xa8, \xec\x97\xac\xeb\xa6\x84 \xec\xa0\x84 \xec\x9d\xb4\xeb\xa0\x87\xea\xb2\x8c \xeb\xa8\xb9\xec\x9c\xbc\xeb\xa9\xb4 \xeb\xaa\xb8\xec\x9d\xb4 \xeb\x8b\xac\xeb\x9d\xbc\xec\xa7\x91\xeb\x8b\x88\xeb\x8b\xa4","url":"https://in.naver.com/aayomin/contents/internal/939123202250496","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDdfMzUg%2FMDAxNzc1NTcyNTAzODMw.i5u2BXytiC_t2i5SCSSLn2SkF3sBhJuJokhfLeztKbIg.l2Ykjy-bJ33nNTdPgpMb1E-OyQ12Nw2EOIVac27PhSEg.PNG%2F%EC%A0%9C%EB%AA%A9%EC%9D%84_%EC%9E%85%EB%A0%A5%ED%95%B4%EC%A3%BC%EC%84%B8%EC%9A%94_-001_-_2026-04-07T233453.511.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/jelly-yoon","name":"\xec\xa0\xa4\xeb\xa6\xac\xec\x9c\xa4","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTEyMjBfMjQ4%2FMDAxNzY2MjMwNDE0Njkz.-d15RXP8cNvPB1z4o3RPpvtXlwkht4BNea15K_tJwIUg.-RLmW94-4Pfx24Tb6GkTUXzJYVPBl-wnlnhw3dzDVFAg.JPEG%2FprofileImage.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cbf"},{"@type":"MATERIAL-PC-FEED","title":"\\"10\xeb\x85\x84\xec\xa7\xb8 \xed\x95\x98\xeb\xa3\xa8 \xed\x95\x9c \xeb\x81\xbc!\\" \xea\xb0\x95\xeb\xaf\xbc\xea\xb2\xbd, 167cm\xc2\xb752kg \xec\x9c\xa0\xec\xa7\x80\xed\x95\x98\xeb\x8a\x94 \xec\x9e\x90\xea\xb8\xb0\xea\xb4\x80\xeb\xa6\xac \xeb\x81\x9d\xed\x8c\x90\xec\x99\x95","url":"https://blog.naver.com/noonnu049/224248244983","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTBfOTgg%2FMDAxNzc1ODE5MTAwMDgx.DLvrzeUOyDUCfjW9geqe7NFYEjMhB4jqjmUol1mksdgg.fZYiY6wIql4sCY17vOqzydQ-5LbddDT9ms1IrrRcyZ8g.JPEG%2F900_1775819099699.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/noonnu049","name":"\xeb\x88\x88\xeb\x88\x84\xeb\x82\x9c\xeb\x82\x98","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNjAzMjRfMjEy%2FMDAxNzc0MzEzNTczMzI3.VRF5605E7HOrE8GHk2AZuTrubHpPq0DcpRJUEx-mwswg.TnzAr9ke14rtICTc8LrIHpnMoWaSFWgHpYa_bfT-K2cg.PNG%2FChatGPT_Image_2026%25EB%2585%2584_3%25EC%259B%2594_24%25EC%259D%25BC_%25EC%2598%25A4%25EC%25A0%2584_09_50_08.png%2FChatGPT%2BImage%2B2026%25EB%2585%2584%2B3%25EC%259B%2594%2B24%25EC%259D%25BC%2B%25EC%2598%25A4%25EC%25A0%2584%2B09_50_08.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc0"},{"@type":"MATERIAL-PC-FEED","title":"\xe2\x80\x9c\xeb\x94\xb8\xec\x97\x90\xea\xb2\x8c \xec\xa7\x90\xeb\x90\x98\xea\xb8\xb0 \xec\x8b\xab\xeb\x8b\xa4\xe2\x80\x9d\xeb\x8d\x98 60\xeb\x8c\x80 \xea\xb0\x80\xec\x9e\xa5, 3\xeb\xaa\x85 \xec\x82\xb4\xeb\xa6\xac\xea\xb3\xa0 \xeb\x96\xa0\xeb\x82\x98","url":"https://n.news.naver.com/article/011/0004612949","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F011%2F2026%2F04%2F21%2F0004612949_001_20260421114907436.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://media.naver.com/press/011","name":"\xec\x84\x9c\xec\x9a\xb8\xea\xb2\xbd\xec\xa0\x9c","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fmimgnews%2Fimage%2Fupload%2Foffice_logo%2F011%2F2025%2F03%2F07%2Flogo_011_100_20250307145637.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc1"},{"@type":"MATERIAL-PC-FEED","title":"\xec\x98\xa4\xec\x9a\xb4\xec\x99\x84 \xed\x95\x98\xec\xb2\xb4 \xed\x9e\x99","url":"https://cafe.naver.com/bodygood/1264910?art=ZXh0ZXJuYWwtc2VydmljZS1uYXZlci1haXJz.eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYWZlVHlwZSI6IkNBRkVfVVJMIiwiYXJ0aWNsZUlkIjoxMjY0OTEwLCJjYWZlVXJsIjoiYm9keWdvb2QiLCJpc3N1ZWRBdCI6MTc3Njc0OTg2MDQwM30.2sfzVKl7O8TkcT81S4yjngXH49M5jeA1eOqWjn2PGow","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fcafeptthumb-phinf.pstatic.net%2FMjAyNjA0MTZfOTAg%2FMDAxNzc2MzExOTI1ODA2.F_P4Dg56j62MgRgiluQiO8EDznrnJrPUupfhHCrI4FEg.AG5HiZaTRlGgmHb2UnjrrcL7IOwthwZb0p_kQ0MT-Lsg.JPEG%2F1776311677974.jpg%7C912x1840%22&type=ff364_236&service=navermain"},"source":{"url":"https://cafe.naver.com/bodygood","name":"\xeb\x84\xa4\xec\x9d\xb4\xeb\xb2\x84 NO.1 \xed\x97\xac\xec\x8a\xa4\xec\xb9\xb4\xed\x8e\x98/\xed\x97\x

In [5]:
res.text        # type: str

'   <!doctype html> <html lang="ko" class="fzoom"> <head> <meta charset="utf-8"> <meta name="Referrer" content="origin"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=1190"> <title>NAVER</title> <meta name="apple-mobile-web-app-title" content="NAVER"/> <meta name="robots" content="index,nofollow"/> <meta name="description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta property="og:title" content="네이버"> <meta property="og:url" content="https://www.naver.com/"> <meta property="og:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta property="og:description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta name="twitter:card" content="summary"> <meta name="twitter:title" content=""> <meta name="twitter:url" content="https://www.naver.com/"> <meta name="twitter:image" content="https://s.pstatic.net/static/www/mobile/edit/2016/0705/mobile_212852414260.png"> <meta name="twitter:description" content="네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요"/> <meta name="google-site-verification" content="uru5NJKa1Bfr5nv5AdQ26Qat7UrPU_02l-PIZRLzI-g"/> <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?1"> <link rel="apple-touch-icon-precomposed" href="https://s.pstatic.net/static/www/nFavicon96.png"/> <link rel="apple-touch-icon" sizes="114x114" href="https://s.pstatic.net/static/www/u/2014/0328/mma_204243574.png"/> <link rel="apple-touch-icon" href="https://s.pstatic.net/static/www/u/2014/0328/mma_20432863.png"/> <link rel="stylesheet" href="https://ssl.pstatic.net/sstatic/search/pc/css/sp_autocomplete_260205.css"> <link rel="canonical" href="https://www.naver.com/"> <link rel="alternate" media="only screen and (max-width: 767px)" href="https://m.naver.com/"> <script>window.gladsdk=window.gladsdk||{},window.gladsdk.cmd=window.gladsdk.cmd||[],window.ndpsdk=window.ndpsdk||{},window.ndpsdk.cmd=window.ndpsdk.cmd||[],window.ndpsdk.polyfill=window.ndpsdk.polyfill||{cmd:[]};var g_ssc="navertop.v5";window.nsc=g_ssc,window.nmain=window.nmain||{},window.nmain.jsOrigin="www"</script> <script>window.ntm=window.ntm||[]</script> <script async src="https://ssl.pstatic.net/tveta/libs/ndpsdk/prod/ndp-loader.js"></script> <script async src="https://ssl.pstatic.net/tveta/libs/glad/prod/gfp-core.js"></script> <script src="https://ssl.pstatic.net/tveta/libs/assets/js/pc/main/min/pc.veta.core.min.js" defer="defer"></script>  <script>\nwindow["EAGER-DATA"] = window["EAGER-DATA"] || {};\nwindow["EAGER-DATA"]["PC-FEED-WRAPPER"] = {"@type":"BLOCK","blocks":[{"@type":"BLOCK","blocks":[{"@type":"PC-FEED-BLOCK","excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-HEALTH-TOP","@template":"HIGHLIGHTED-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"‘6kg 감량’ 최강희, 요요 왔다…“‘이것’ 끊자 식욕 폭발” 뭘까?","url":"https://n.news.naver.com/article/296/0000099718","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F296%2F2026%2F04%2F20%2F0000099718_001_20260420150615768.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://media.naver.com/press/296","name":"코메디닷컴","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fmimgnews%2Fimage%2Fupload%2Foffice_logo%2F296%2F2025%2F03%2F07%2Flogo_296_100_20250307145636.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a642"},{"@type":"MATERIAL-PC-FEED","title":"“44kg 뺐는데 다시 쪘다”…김신영이 요요를 인정한 진짜 이유","url":"https://blog.naver.com/hitthemoney/224243472916","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDdfMTM1%2FMDAxNzc1NTE3NjEzODQy.OSS63kTplYBOjinBJCEN8gvq-fZReEqF3niUSIVktG0g.inRS9KqjJ61fbjwcUlZ5RsQdBQVC9sWS6s_fLBlOK1wg.JPEG%2FIMG%EF%BC%BF2334.JPG%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/hitthemoney","name":"머니파수꾼","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNjAzMjJfMjc5%2FMDAxNzc0MTc5ODY2NTI5.k14NNHxzpnwm7UZ28B4x62phG0scx2ogCwkLn_AtBPsg.7nSc9ferAD8KPnatbylpkTr2MoJUlyCD722SYou0KMMg.PNG%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a643"},{"@type":"MATERIAL-PC-FEED","title":"연차 쓰고 한강 10km 뛰는 여자, 제법 멋져요","url":"https://blog.naver.com/kudayz/224245568968","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDhfMTMz%2FMDAxNzc1NjQwNjcxOTc1.VTJq-YEL6hBxYtkPAnoQpABIP2mOlJpXkXCS9rk64JAg.mLAjg_RU4cWS0-Z67DDtyPkJ2G_ENaQqPmuiP1WAJosg.JPEG%2FKakaoTalk_20260408_182909640_07.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/kudayz","name":"쿠주","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNDA3MzFfMjAw%2FMDAxNzIyNDA0NDg2MDI3.PTtDS5ubTyHKXUYEkUvjANqMg_wfVHWCzBsDN14V9vAg.hBh1VUUqip_xkWbhTL-m2Y-1NVzaPc7OnT4Wyztg7vgg.JPEG%2FKakaoTalk_20240731_144059728.jpg%2FKakaoTalk_20240731_144059728.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a644"},{"@type":"MATERIAL-PC-FEED","title":"김지원 드레스 몸매 충격 근황 ‘이 음식’ 끊고 다이어트 성공","url":"https://in.naver.com/jinny/contents/internal/942409049184032","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTZfMjYx%2FMDAxNzc2MzE2OTUyMDg3.hhnC_qTYCdUXrieu5CRCM85KTGDo225kSMJlZ1HU9Nog.1JXQFCpn8qa3tZMVYjcrJDs9qZl8-Ig1FQ8s39Ex2dcg.JPEG%2Foutput%EF%BC%BF3911620217.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/supia2728","name":"지니츄","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMjExMTNfOTYg%2FMDAxNjY4MjkzNzY3Njgx.OQzhh0AnLRkjro1VKIHYW59ieYCVvcuj-ZERbN5N_fYg.ByZj2jmt2fJGcoU3x1Asl4Zc7uZ-beBL3z5wsh9rflsg.PNG.supia2728%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a645"},{"@type":"MATERIAL-PC-FEED","title":"중년 뱃살 빼는 최고의 칼로리 폭파 운동","url":"https://tv.naver.com/h/98114587","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260420_165%2FE6VpH_1776690761468Osm7w_JPEG%2F82PN94LM69_03.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://tv.naver.com/impt","name":"임피티IMPT","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20240603_37%2FR5xey_1717410445431SxjBX_PNG%2F1717410445403.png%22&type=nf40_40&service=navermain"}},"video":{"playTime":"01:23"},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a646"},{"@type":"MATERIAL-PC-FEED","title":"밥 먹으면서 17kg 뺀 송혜교! 다이어트 식단과 절대 먹지 않는다는 \\"이것\\"","url":"https://in.naver.com/runddungja/contents/internal/936562286598464","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAzMzFfOTMg%2FMDAxNzc0OTUyNzgzMTEw.Fj9-rcwnY5opqHy3NZ1UZJ6YIOHg-qwEh8jfe4w4rE4g.ImbOCv714r9OcavaWyly499hep5mVoFnukehaNlCOH8g.PNG%2F%EB%95%85%EC%BD%A9%EB%B2%84%ED%84%B0_%28100%29.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/hhj1004w","name":"쫑알쫑알","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMDA5MThfMTc2%2FMDAxNjAwNDA3NTg3MzQ3.iGpQ5T6XITV6FbArPATdBHGrjBrmXQ0MDuLRkohd1zEg.BqmIcUyg1sGNNopgsTiKI8FaFrrIAPR-uXQdj61UHSsg.PNG.hhj1004w%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a647"},{"@type":"MATERIAL-PC-FEED","title":"괜찮겠지 했다가 결국 \'재검사\' 대장내시경 전날 음식 3일전 식사 핵심","url":"https://in.naver.com/sudy_ys/contents/internal/936119519512256","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjAzMzBfMjMz%2FMDAxNzc0ODQ1NTI5MzIx.AYQSubgB94l4d7tGwrfz0s8rprUsRFHI-n-gmroIqMQg.rHXpQbrAGYYynLMg0zzNarSjvKsNI0hpLeLu4qRmJZwg.PNG%2FDesign_-_2026-03-30T133846.147.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/sudy_ys","name":"윤슬맘","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTAyMTFfOCAg%2FMDAxNzM5MjUxNzQ4MTc4.nHWZf-bSsmybn_ETM3kF83mO5f1A5cLUmf_oz1eYqNIg.j8fTqwQMqo8ePEEiQxhHZOI5Z9xYyxvAIH_SyqZ9p28g.PNG%2FprofileImage.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a648"},{"@type":"MATERIAL-PC-FEED","title":"화사 왜 이렇게 말랐나? 뼈말라인데 근육 있다, 몸매 변화 만든 식단 이유","url":"https://in.naver.com/kimyeonwooxo/contents/internal/941892921939840","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTVfMjky%2FMDAxNzc2MjUwMDUyMjU3.KPrN3OrekUp_4teAuWp_ssDVGHYwprzRbUyzufNUvcsg.LyV5NTsCXPbyyECrct3BhxMVg3VfxOqr0LkhoKR08dkg.JPEG%2FIMG%EF%BC%BF6920.JPG%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/kimyeonwooxo","name":"연치코치","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNjAzMjVfMTkg%2FMDAxNzc0NDM2NTUzNDEz.gjPbtSOuYbM8hanUc_vKDzztS_sQIbMUTwoTOBih64sg.BvToyyU6whIsHTr9Bpz_tdt6o_rajqzAfBKPf86P4Jog.JPEG%2FprofileImage.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"6548800558a9ce6eb3e8a649"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-HEALTH-AIRS-PAGE-1","@template":"TWO-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"[광고] 딱 3일 저녁으로 이거 먹으면 뱃살 제대로 빠질듯🤭  줄서서 먹는다는 아사이볼 사먹지마시고 이렇게 만들어 드세요  파는 것 보다 당류도 훨씬 적고 싸요🤓  유기농 코코너칩&바나나칩 듬뿍 들어간  코코아몬드버터🥥🍌🥜 에 올리고당만 살짝 얹었는데  너무 맛있네요.....🫐  요 코코바나나아몬드 버터 부로디에서만 먹어볼수 있는데   🇺🇸미국 유기농인증 ","url":"https://m.naver.com/shorts?serviceType=CLIP&mediaType=VOD&seedMediaId=1540F1B56E738ED6779FC3DADB16946B8A38&recType=CLIP_PC&recId=%7B%22targetProfileId%22%3A%22tonylove1206%22%2C%22open%22%3Atrue%7D","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fclip-service-phinf.pstatic.net%2FMjAyNjA0MjFfMjUy%2FMDAxNzc2Njk3ODA3Njkz.UwuEvVIuRJJUiMJOIn-0UHcU9W0794nXHERPjf2Uxjsg.TATdwoIQ04Ie6dks1F48eyuqCeEDBU_htpsJwwzd878g.JPEG%2FPublishThumb_20260421_000426_430.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://clip.naver.com/@body_theory","name":"bodytheory","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fclip-service-phinf.pstatic.net%2FMjAyNTA4MjVfMTU4%2FMDAxNzU2MDk2NTM5NDg3.t5dYB1JLUIbtZojgqAu0FVx4JTVKqYrbGxGM86Y9CI0g.G3heVo9VZEwQ5KIV2OhERTjkRGDmDGgFT6tAu5lqJxQg.JPEG%2Fimage.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:18"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cbe"},{"@type":"MATERIAL-PC-FEED","title":"다이어트식단, 여름 전 이렇게 먹으면 몸이 달라집니다","url":"https://in.naver.com/aayomin/contents/internal/939123202250496","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDdfMzUg%2FMDAxNzc1NTcyNTAzODMw.i5u2BXytiC_t2i5SCSSLn2SkF3sBhJuJokhfLeztKbIg.l2Ykjy-bJ33nNTdPgpMb1E-OyQ12Nw2EOIVac27PhSEg.PNG%2F%EC%A0%9C%EB%AA%A9%EC%9D%84_%EC%9E%85%EB%A0%A5%ED%95%B4%EC%A3%BC%EC%84%B8%EC%9A%94_-001_-_2026-04-07T233453.511.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/jelly-yoon","name":"젤리윤","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTEyMjBfMjQ4%2FMDAxNzY2MjMwNDE0Njkz.-d15RXP8cNvPB1z4o3RPpvtXlwkht4BNea15K_tJwIUg.-RLmW94-4Pfx24Tb6GkTUXzJYVPBl-wnlnhw3dzDVFAg.JPEG%2FprofileImage.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cbf"},{"@type":"MATERIAL-PC-FEED","title":"\\"10년째 하루 한 끼!\\" 강민경, 167cm·52kg 유지하는 자기관리 끝판왕","url":"https://blog.naver.com/noonnu049/224248244983","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTBfOTgg%2FMDAxNzc1ODE5MTAwMDgx.DLvrzeUOyDUCfjW9geqe7NFYEjMhB4jqjmUol1mksdgg.fZYiY6wIql4sCY17vOqzydQ-5LbddDT9ms1IrrRcyZ8g.JPEG%2F900_1775819099699.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/noonnu049","name":"눈누난나","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNjAzMjRfMjEy%2FMDAxNzc0MzEzNTczMzI3.VRF5605E7HOrE8GHk2AZuTrubHpPq0DcpRJUEx-mwswg.TnzAr9ke14rtICTc8LrIHpnMoWaSFWgHpYa_bfT-K2cg.PNG%2FChatGPT_Image_2026%25EB%2585%2584_3%25EC%259B%2594_24%25EC%259D%25BC_%25EC%2598%25A4%25EC%25A0%2584_09_50_08.png%2FChatGPT%2BImage%2B2026%25EB%2585%2584%2B3%25EC%259B%2594%2B24%25EC%259D%25BC%2B%25EC%2598%25A4%25EC%25A0%2584%2B09_50_08.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc0"},{"@type":"MATERIAL-PC-FEED","title":"“딸에게 짐되기 싫다”던 60대 가장, 3명 살리고 떠나","url":"https://n.news.naver.com/article/011/0004612949","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F011%2F2026%2F04%2F21%2F0004612949_001_20260421114907436.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://media.naver.com/press/011","name":"서울경제","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fmimgnews%2Fimage%2Fupload%2Foffice_logo%2F011%2F2025%2F03%2F07%2Flogo_011_100_20250307145637.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc1"},{"@type":"MATERIAL-PC-FEED","title":"오운완 하체 힙","url":"https://cafe.naver.com/bodygood/1264910?art=ZXh0ZXJuYWwtc2VydmljZS1uYXZlci1haXJz.eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjYWZlVHlwZSI6IkNBRkVfVVJMIiwiYXJ0aWNsZUlkIjoxMjY0OTEwLCJjYWZlVXJsIjoiYm9keWdvb2QiLCJpc3N1ZWRBdCI6MTc3Njc0OTg2MDQwM30.2sfzVKl7O8TkcT81S4yjngXH49M5jeA1eOqWjn2PGow","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fcafeptthumb-phinf.pstatic.net%2FMjAyNjA0MTZfOTAg%2FMDAxNzc2MzExOTI1ODA2.F_P4Dg56j62MgRgiluQiO8EDznrnJrPUupfhHCrI4FEg.AG5HiZaTRlGgmHb2UnjrrcL7IOwthwZb0p_kQ0MT-Lsg.JPEG%2F1776311677974.jpg%7C912x1840%22&type=ff364_236&service=navermain"},"source":{"url":"https://cafe.naver.com/bodygood","name":"네이버 NO.1 헬스카페/헬스매니아 몸짱 클럽/최다헬스정보,회원","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fcafeptthumb-phinf.pstatic.net%2FMjAyMTA3MTRfMjUy%2FMDAxNjI2MjMwOTczNDcz.WcaAQrGkRP3P6JCjUN9kpLFk9j4XGJSg_l2WnDJo_Uwg.LAElxQwq4wvWl0844daz90jvyiB0GLKUI3wsafdBHEAg.JPEG%2F%25ED%2597%25AC%25EB%25A7%25A4%25EC%25B9%25B4%25ED%258E%2598%25EB%25A1%259C%25EA%25B3%25A0_150x150.jpg%3Ftype%3Df40_40_mask%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc2"},{"@type":"MATERIAL-PC-FEED","title":"식초 이렇게 먹으면 식도 싹 녹는다!","url":"https://tv.naver.com/h/97973768","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20260418_108%2F9HpTY_17764992765320CQic_JPEG%2FlswPYYdpUk_01.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://tv.naver.com/livinggenius","name":"건강천재 - 건강정보","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Ftvcast.phinf%2F20240617_65%2FuE7J8_1718607099914M8eRc_PNG%2F1718607099910.png%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:30"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc3"},{"@type":"MATERIAL-PC-FEED","title":"우연히 전지현님이 직접 얘기한 몸매 관리 비법 봤는데 제가 해온 방식이랑 너무 비슷해서 놀랍고 반갑더라고요. 일부러 따라한 건 아닌데 결국 가장 현실적이면서 제일 잘 빠졌던 방식이기 때문에 공통점이 있는게 아닐까 싶어 영상만들고 정리했으니 참조하세요!  ✔️ 공복 러닝 운동  ✔️ 낮보다 저녁을 참기 힘드니 점심은 가볍게 저녁은 먹고 싶은 걸 먹되 되도록 ","url":"https://m.naver.com/shorts?serviceType=CLIP&mediaType=VOD&seedMediaId=FE98354F747413C862270A6DD4AD13278429&recType=CLIP_PC&recId=%7B%22targetProfileId%22%3A%22feelnowhere%22%2C%22open%22%3Atrue%7D","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fclip-service-phinf.pstatic.net%2FMjAyNjA0MThfNDcg%2FMDAxNzc2NDk1OTE4ODU0.0QN_h3ghOPuRmB8UfNGX4tOQtRVsokePL2RO_zruC5Qg.jPtfU8zQvr9bNrNR67iJ_fkRpEvyAyTvj-X4Mz9iy-Qg.JPEG%2FPublishThumb_20260418_160513_482.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://clip.naver.com/@feelnowhere","name":"지나우","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fclip-service-phinf.pstatic.net%2FMjAyNTA4MjFfNDcg%2FMDAxNzU1NzA0NjUxOTI4.l4STlBYJnRwDPWnlaa1HDM-zrzt-pVL7FoxNtVMnhJ4g.VYVGBdJBKzf5pTfnAqiGCMMCB31DpHpubIYBiE1ScDYg.JPEG%2Fimage.jpg%22&type=nf40_40&service=navermain"}},"video":{"playTime":"00:18"},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc4"},{"@type":"MATERIAL-PC-FEED","title":"\\"국민연금 2배 훌쩍 넘게\\" 받고 싶다면 이렇게 하세요","url":"https://in.naver.com/ymi5025/contents/internal/938228023367360","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MDVfMjU4%2FMDAxNzc1MzU5NjYxMDQ0.vl8vyZc7CBmjdVYGvs5I2VZ21WEbddRJ8LqTWCQAzJ8g.YD6re33D0BCPsZomPIzeJnPaxudhRoqZFg5VDH5GnOcg.PNG%2Fimage.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/ymi5025","name":"주니대디","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNTEyMzBfMzgg%2FMDAxNzY3MDU2MTUzMTgx.Y3obd-fCP-3FwJrq7BaZl3nscivETVD3CCYMAyqzyowg.-_Bs0UIbyA_JQXg-4sWYI97wtZ_0NAu-7iL7DYNAwAQg.JPEG%2FprofileImage.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc5"}],"excludeInPaging":false,"positionForPaging":0,"realtime":false,"needCologger":false,"ad":false,"@type":"PC-FEED-BLOCK","@code":"PC-FEED-HEALTH-AIRS-PAGE-2","@template":"TWO-COLUMNS"},{"@type":"PC-FEED-BLOCK","materials":[{"@type":"MATERIAL-PC-FEED","title":"“단 음식 당길 때 먹어라” 영양사 추천 간식 4가지, 뭘까?","url":"https://n.news.naver.com/article/346/0000108451","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fimgnews%2Fimage%2F346%2F2026%2F04%2F21%2F0000108451_001_20260421122110129.jpg%22&type=ff364_236&service=navermain"},"source":{"url":"https://media.naver.com/press/346","name":"헬스조선","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22https%3A%2F%2Fs.pstatic.net%2Fmimgnews%2Fimage%2Fupload%2Foffice_logo%2F346%2F2025%2F03%2F27%2Flogo_346_100_20250327110759.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc6"},{"@type":"MATERIAL-PC-FEED","title":"내분비내과 전문의들이 극찬한 당뇨 정상수치 뚝 떨어뜨리는 음식 5가지","url":"https://in.naver.com/donam180/contents/internal/941457991841760","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTJfMTUg%2FMDAxNzc1OTc5MTQwMTUx.gvtqo79u509oPJV1GKCPjpBcBlxaDaTlBWELmXRvQ34g.nzHMWOl7pg5mKrBk_WNGLo4R74K_N-Y4isloEEiNgQUg.PNG%2F006.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/andudtk12","name":"건강탐구생활","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyNDA0MDJfMTk5%2FMDAxNzEyMDUzOTE2NjE3.D65rwk-3BxsqYrr_FBk5fLFPkUMLLnKGxXXjgZ0pp4Ug.6SX5RkM1dxO8zBckk2bGdyBRBDOgeUJoyw80s6UCY4wg.PNG%2F002.png%2F002.png%22&type=nf40_40&service=navermain"}},"showLiveBadge":false,"_id":"654ad80598c6dbca70ba6cc7"},{"@type":"MATERIAL-PC-FEED","title":"\\"이제 뼈말라 시대는 끝!\\" 장원영, 애플힙 장착하고 핏 갈아엎은 근황","url":"https://blog.naver.com/rider_doo/224253347716","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogfiles.naver.net%2FMjAyNjA0MTVfMTY1%2FMDAxNzc2MjM1MzY5MDAw.JwlyB3lDAdUn8GtKvYt9PVy_UuFgP6MxQWI0BoMUo2Ug.egAs_x0YFDjos5g6OgUPyDEGirFjEdxxbMSFE4C7d-Yg.PNG%2Fimage.png%22&type=ff364_236&service=navermain"},"source":{"url":"https://blog.naver.com/rider_doo","name":"운동하는 슬기처럼","image":{"url":"https://s.pstatic.net/dthumb.phinf/?src=%22http%3A%2F%2Fblogpfthumb.phinf.naver.net%2FMjAyMzA4MTZfMjA0%2FMDAxNjkyMTY0ODc1MDA1.3O7HsTP0LoKAe08kKyz75s4H5Z9DjJwHA1nYuz39hkcg.ahMgI20SF9jhreMvXotO2VlRzRxA93d7fjuzC28pHrgg.JPEG.lts6390%2FKakaoTalk_20230516_110906111.jpg%2FKakaoTalk_20230516_110906111.jpg%22&type=nf40_40&service=navermain"}},"showLiveBadge"

In [6]:
html_text = res.text

In [7]:
# 문자열에서 특정 문자의 위치를 찾는 함수: find()
html_text.find("네이버")

378

In [8]:
html_text[378:410]

'네이버 메인에서 다양한 정보와 유용한 컨텐츠를 만나 보세요'

In [9]:
# 문자 형태로 이루어진 html 문서를 BeautifulSoup class를 이용해서 객체 변환
# 문자 데이터에서는 특정 영역의 content를 추출하기 어렵다.
# BeautifulSoup에 내장된 함수를 이용해서 데이터를 추출하기 위해 class 생성 시 데이터를 대입

soup = bs(html_text, 'html.parser')

In [10]:
type(soup)

bs4.BeautifulSoup

- 태그의 이름을 기준으로 검색
    - soup.태그명
        - 해당 html 문서 안에서 해당 태그 중 첫번째 태그를 되돌려준다.
        - 문자열 함수에서 find() 함수와 비슷한 부분
    - soup.태그명.string
        - 첫번째 태그에서 콘텐츠(태그 안에 데이터)를 되돌려준다.
            - ex) `<p>Test</p>` → 'Test'
    - soup.태그명[속성명]
        - 첫번째 태그에서 특정 속성의 값을 되돌려준다.
            - ex) `<a href = "https://www.naver.com">네이버</a>`
            - → `https://www.naver.com`

In [11]:
print(soup.a)               # a 태그: 하이퍼링크
print(soup.a.string)        # content 출력
print(soup.a['href'])       # 속성값 출력

<a href="#topAsideButton"><span>상단영역 바로가기</span></a>
상단영역 바로가기
#topAsideButton

- 내장함수
    - find()
        - html 문서 안에서 특정 태그의 첫번째 정보를 출력
        - find(속성명 = 속성값)
            - 태그들 중 특정 속성에 특정한 값을 가진 태그의 첫번째 정보를 출력
        - 함수의 결과값의 타입은 TAG 데이터의 타입으로 되돌려준다.
    - find_all()
        - html 문서 안에서 특정 태그의 모든 정보를 출력
        - limit 매개변수
            - 찾는 태그의 개수를 지정
        - 함수의 결과값의 타입은 ResultSet 타입으로 되돌려준다.
        - find(), find_all() 함수는 Tag 타입에서는 사용이 가능
        - ResultSet에서는 사용이 불가능
    - ResultSet 타입은 Tag 데이터들이 모여있는 리스트의 형태와 흡사

In [12]:
type(soup)

bs4.BeautifulSoup

In [13]:
type(soup.find('a'))

bs4.element.Tag

In [14]:
type(soup.find_all('a'))

bs4.element.ResultSet

In [15]:
soup.find('a')

In [16]:
soup.find_all('a')      # 1차로 보내준 부분에서의 a 태그

[<a href="#topAsideButton"><span>상단영역 바로가기</span></a>,
 <a href="#shortcutArea"><span>서비스 메뉴 바로가기</span></a>,
 <a href="#newsstand"><span>새소식 블록 바로가기</span></a>,
 <a href="#shopping"><span>쇼핑 블록 바로가기</span></a>,
 <a href="#feed"><span>관심사 블록 바로가기</span></a>,
 <a href="#account"><span>MY 영역 바로가기</span></a>,
 <a href="#widgetboard"><span>위젯 보드 바로가기</span></a>,
 <a href="#viewSetting"><span>보기 설정 바로가기</span></a>]

In [17]:
a_tag = soup.find('a')

In [18]:
a_tag.find('span')

In [19]:
a_list = soup.find_all('a')

In [20]:
a_list.find('span')

AttributeError: ResultSet object has no attribute "find". You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [21]:
# 모든 a 태그에서 모든 content를 추출하여 새로운 리스트로 생성
# a_list에 있는 첫번째 tag를 선택하여 .string 을 이용한 텍스트 추출(8번 반복)
# a_list는 type이 ResultSet인데 for문에서 바로 사용이 가능할까?

a_datas = []

for tag_data in a_list:
    # print(tag_data.string)
    # break
    a_datas.append(tag_data.string)

In [22]:
a_datas

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [23]:
# map() + lambda
# python에서 기본 제공 map의 결과를 list로 변환

list(
    map(
        lambda x: x.string,
        a_list
    )
)

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

In [24]:
[data.string for data in a_list]
# 실제 데이터가 들어가는 부분은 앞에 있는 data (string 붙은 부분)
# a_list 뒤에 뭔가 들어간다면 그것은 조건식

['상단영역 바로가기',
 '서비스 메뉴 바로가기',
 '새소식 블록 바로가기',
 '쇼핑 블록 바로가기',
 '관심사 블록 바로가기',
 'MY 영역 바로가기',
 '위젯 보드 바로가기',
 '보기 설정 바로가기']

### 네이버 증권

In [1]:
import requests
from bs4 import BeautifulSoup as bs

In [ ]:
# 네이버 증권 사이트 크롤링
# requests 라이브러리를 이용해서 html 문서를 받는다.
result = requests.get('https://finance.naver.com')

# 응답 데이터를 문자형으로 변환: BeautifulSoup 파싱
soup = bs(result.text, 'html.parser')

In [ ]:
soup

In [ ]:
# html 문서 안에서 태그명이 div이고 class 속성의 값이 section_sise_top인 태그를 모두 찾아서 길이를 구하자

len(
    soup.find_all(
        'div',
        attrs = {
            'class' : 'section_sise_top'
        }
    )
)

1

In [28]:
# 1개라면 find_all()이 아닌 find()를 이용해서 data 추출
div_data = soup.find(
    'div',
    attrs = {
        'class': 'section_sise_top'
    }
)

In [29]:
div_data

<div class="section_sise_top">
<h2 class="h_type"><span>TOP 종목</span></h2>
<!-- KRX, NXT 탭 -->
<div class="area_tab_type">
<ul class="top_tab_list">
<!-- [D] 선택된 탭 'is_active' -->
<li class="top_tab_item top_tab_krx is_active">
<a class="top_tab_link" href="#" onclick="clickcr(this, 'top.krx', '', '', event);return false;">KRX</a>
</li>
<li class="top_tab_item top_tab_nxt">
<a class="top_tab_link" href="#" onclick="clickcr(this, 'top.nxt', '', '', event);return false;">NXT</a>
</li>
</ul>
<div class="text_nxt">
                                넥스트레이드(NXT)
                                <button class="buttton_tooltip" type="button">
<span class="icon">
<span class="blind">도움말</span>
</span>
</button>
<div class="area_tooltip">
<p>
<strong>넥스트레이드(NXT)</strong>
                                        넥스트레이드(NXT)란 대한민국
                                        최초의 대체거래소(ATS,
                                        Alternative Trading
                                        System)입니다. 아래는
                                        넥스트레이드에서 거래가 가능한
                                        종목들입니다.
                                    </p>
<span class="arrow"></span>
</div>
</div>
</div>
<!-- //KRX, NXT 탭 -->
<ul class="tab_sort_list">
<!-- [D] 선택된 탭 'is_active' -->
<li class="tab_sort_item is_active"><a class="link tab_sort_sale" href="#" onclick="clickcr(this, 'spe.sale', '', '', event);return false;"><span class="tab1"><span class="blind">거래상위</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_ceiling" href="#" onclick="clickcr(this, 'spe.ceiling', '', '', event);return false;"><span class="tab2"><span class="blind">상승</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_bottom" href="#" onclick="clickcr(this, 'spe.bottom', '', '', event);return false;"><span class="tab3"><span class="blind">하락</span></span></a></li>
<li class="tab_sort_item"><a class="link tab_sort_value" href="#" onclick="clickcr(this, 'spe.value', '', '', event);return false;"><span class="tab4"><span class="blind">시가총액 상위</span></span></a></li>
</ul>
<div class="group_type krx_group_type tab1 is_active">
<table class="tbl_home">
<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems1">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>182</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 9</td>
<td>
<em class="down">
				-4.71%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=114800" onclick="clickcr(this, 'spe.slist', '114800', '2', event);">KODEX 인버스</a></th>
<td>1,396</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 36</td>
<td>
<em class="down">
				-2.51%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=462330" onclick="clickcr(this, 'spe.slist', '462330', '3', event);">KODEX 2차전지산업레버리지</a></th>
<td>2,565</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 410</td>
<td>
<em class="up">
				+19.03%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=047040" onclick="clickcr(this, 'spe.slist', '047040', '4', event);">대우건설</a></th>
<td>33,150</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 5,050</td>
<td>
<em class="up">
				+17.97%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078130" onclick="clickcr(this, 'spe.slist', '078130', '5', event);">국일제지</a></th>
<td>470</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 108</td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=065420" onclick="clickcr(this, 'spe.slist', '065420', '6', event);">에스아이리소스</a></th>
<td>309</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 10</td>
<td>
<em class="up">
				+3.34%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=131760" onclick="clickcr(this, 'spe.slist', '131760', '7', event);">파인텍</a></th>
<td>2,015</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 442</td>
<td>
<em class="up">
				+28.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=203650" onclick="clickcr(this, 'spe.slist', '203650', '8', event);">드림시큐리티</a></th>
<td>3,915</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 35</td>
<td>
<em class="up">
				+0.90%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=184230" onclick="clickcr(this, 'spe.slist', '184230', '9', event);">SGA솔루션즈</a></th>
<td>1,097</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 51</td>
<td>
<em class="up">
				+4.88%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=530036" onclick="clickcr(this, 'spe.slist', '530036', '10', event);">삼성 인버스 2X WTI원유 선물 ETN</a></th>
<td>23</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1</td>
<td>
<em class="up">
				+4.55%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=092220" onclick="clickcr(this, 'spe.slist', '092220', '11', event);">KEC</a></th>
<td>1,372</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 149</td>
<td>
<em class="up">
				+12.18%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=222080" onclick="clickcr(this, 'spe.slist', '222080', '12', event);">씨아이에스</a></th>
<td>16,310</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,760</td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011930" onclick="clickcr(this, 'spe.slist', '011930', '13', event);">신성이엔지</a></th>
<td>3,945</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 45</td>
<td>
<em class="up">
				+1.15%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011000" onclick="clickcr(this, 'spe.slist', '011000', '14', event);">진원생명과학</a></th>
<td>1,415</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 93</td>
<td>
<em class="up">
				+7.03%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252710" onclick="clickcr(this, 'spe.slist', '252710', '15', event);">TIGER 200선물인버스2X</a></th>
<td>192</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 12</td>
<td>
<em class="down">
				-5.88%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/sise_quant.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">거래상위 더보기</span></em></a>
</div>
<div class="group_type nxt_group_type tab1 is_active" style="display:none">
<table class="tbl_home">
<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="nxt_topItems1">
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=014940" onclick="clickcr(this, 'spe.slist', '014940', '1', event);">오리엔탈정공</a></th>
<td>8,520</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 500</td>
<td>
<em class="up">
				+6.23%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=005930" onclick="clickcr(this, 'spe.slist', '005930', '2', event);">삼성전자</a></th>
<td>218,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,500</td>
<td>
<em class="up">
				+1.63%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=006360" onclick="clickcr(this, 'spe.slist', '006360', '3', event);">GS건설</a></th>
<td>42,700</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 4,650</td>
<td>
<em class="up">
				+12.22%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=004980" onclick="clickcr(this, 'spe.slist', '004980', '4', event);">성신양회</a></th>
<td>11,780</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 750</td>
<td>
<em class="up">
				+6.80%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=010140" onclick="clickcr(this, 'spe.slist', '010140', '5', event);">삼성중공업</a></th>
<td>30,050</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,500</td>
<td>
<em class="up">
				+5.25%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=378340" onclick="clickcr(this, 'spe.slist', '378340', '6', event);">필에너지</a></th>
<td>19,650</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,120</td>
<td>
<em class="up">
				+18.87%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=161000" onclick="clickcr(this, 'spe.slist', '161000', '7', event);">애경케미칼</a></th>
<td>15,250</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,400</td>
<td>
<em class="up">
				+10.11%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=077970" onclick="clickcr(this, 'spe.slist', '077970', '8', event);">STX엔진</a></th>
<td>51,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 4,800</td>
<td>
<em class="up">
				+10.39%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=034020" onclick="clickcr(this, 'spe.slist', '034020', '9', event);">두산에너빌리티</a></th>
<td>115,400</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 4,400</td>
<td>
<em class="up">
				+3.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=101730" onclick="clickcr(this, 'spe.slist', '101730', '10', event);">위메이드맥스</a></th>
<td>6,680</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 160</td>
<td>
<em class="up">
				+2.45%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=336370" onclick="clickcr(this, 'spe.slist', '336370', '11', event);">솔루스첨단소재</a></th>
<td>14,150</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,140</td>
<td>
<em class="up">
				+28.52%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=005440" onclick="clickcr(this, 'spe.slist', '005440', '12', event);">현대지에프홀딩스</a></th>
<td>14,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 720</td>
<td>
<em class="up">
				+5.06%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=028050" onclick="clickcr(this, 'spe.slist', '028050', '13', event);">삼성E&amp;A</a></th>
<td>51,450</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 2,150</td>
<td>
<em class="up">
				+4.36%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=107640" onclick="clickcr(this, 'spe.slist', '107640', '14', event);">한중엔시에스</a></th>
<td>72,500</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 16,700</td>
<td>
<em class="up">
				+29.93%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=114190" onclick="clickcr(this, 'spe.slist', '114190', '15', event);">강원에너지</a></th>
<td>15,590</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,030</td>
<td>
<em class="up">
				+7.07%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/nxt_sise_quant.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">거래상위 더보기</span></em></a>
</div>
<div class="group_type krx_group_type tab2">
<table class="tbl_home">
<caption>상승 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems2">
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=045510" onclick="clickcr(this, 'spe.clist', '045510', '1', event);">정원엔시스</a></th>
<td>1,297</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 299 </td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=222080" onclick="clickcr(this, 'spe.clist', '222080', '2', event);">씨아이에스</a></th>
<td>16,310</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 3,760 </td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=036930" onclick="clickcr(this, 'spe.clist', '036930', '3', event);">주성엔지니어링</a></th>
<td>118,900</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 27,400 </td>
<td>
<em class="up">
				+29.95%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=256940" onclick="clickcr(this, 'spe.clist', '256940', '4', event);">킵스파마</a></th>
<td>10,850</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 2,500 </td>
<td>
<em class="up">
				+29.94%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=107640" onclick="clickcr(this, 'spe.clist', '107640', '5', event);">한중엔시에스</a></th>
<td>72,500</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 16,700 </td>
<td>
<em class="up">
				+29.93%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=312610" onclick="clickcr(this, 'spe.clist', '312610', '6', event);">에이에프더블류</a></th>
<td>1,424</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 328 </td>
<td>
<em class="up">
				+29.93%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=900100" onclick="clickcr(this, 'spe.clist', '900100', '7', event);">애머릿지</a></th>
<td>508</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 117 </td>
<td>
<em class="up">
				+29.92%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=073570" onclick="clickcr(this, 'spe.clist', '073570', '8', event);">리튬포어스</a></th>
<td>756</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 174 </td>
<td>
<em class="up">
				+29.90%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=189330" onclick="clickcr(this, 'spe.clist', '189330', '9', event);">씨이랩</a></th>
<td>8,950</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 2,060 </td>
<td>
<em class="up">
				+29.90%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=424760" onclick="clickcr(this, 'spe.clist', '424760', '10', event);">벨로크</a></th>
<td>2,370</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 545 </td>
<td>
<em class="up">
				+29.86%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078130" onclick="clickcr(this, 'spe.clist', '078130', '11', event);">국일제지</a></th>
<td>470</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 108 </td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=131400" onclick="clickcr(this, 'spe.clist', '131400', '12', event);">이브이첨단소재</a></th>
<td>2,050</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 471 </td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=051980" onclick="clickcr(this, 'spe.clist', '051980', '13', event);">중앙첨단소재</a></th>
<td>2,135</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 489 </td>
<td>
<em class="up">
				+29.71%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=127980" onclick="clickcr(this, 'spe.clist', '127980', '14', event);">화인써키트</a></th>
<td>6,800</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1,540 </td>
<td>
<em class="up">
				+29.28%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=336370" onclick="clickcr(this, 'spe.clist', '336370', '15', event);">솔루스첨단소재</a></th>
<td>14,140</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,130 </td>
<td>
<em class="up">
				+28.43%
				</em>
</td>
</tr>
</tbody>
</table>
<a class="btn_more" href="/sise/sise_rise.naver" onclick="clickcr(this, 'spe.more', '', '', event);"><em class="btn_more4"><span class="blind">상승 더보기</span></em></a>
</div>
<div class="group_type nxt_group_type tab2" style="display:none">
<table class="tbl_home">
<caption>상승 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="nxt_topItems2">
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=107640" onclick="clickcr(this, 'spe.clist', '107640', '1', event);">한중엔시에스</a></th>
<td>72,500</td>
<td><em class="bu_p bu_pup2"><span class="blind">상한가</span></em> 16,700 </td>
<td>
<em class="up">
				+29.93%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=336370" onclick="clickcr(this, 'spe.clist', '336370', '2', event);">솔루스첨단소재</a></th>
<td>14,150</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,140 </td>
<td>
<em class="up">
				+28.52%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=006400" onclick="clickcr(this, 'spe.clist', '006400', '3', event);">삼성SDI</a></th>
<td>643,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 105,000 </td>
<td>
<em class="up">
				+19.52%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=378340" onclick="clickcr(this, 'spe.clist', '378340', '4', event);">필에너지</a></th>
<td>19,650</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,120 </td>
<td>
<em class="up">
				+18.87%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=348370" onclick="clickcr(this, 'spe.clist', '348370', '5', event);">엔켐</a></th>
<td>48,950</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 7,200 </td>
<td>
<em class="up">
				+17.25%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=469610" onclick="clickcr(this, 'spe.clist', '469610', '6', event);">이노테크</a></th>
<td>26,700</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,850 </td>
<td>
<em class="up">
				+16.85%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=171090" onclick="clickcr(this, 'spe.clist', '171090', '7', event);">선익시스템</a></th>
<td>117,300</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 16,400 </td>
<td>
<em class="up">
				+16.25%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=443060" onclick="clickcr(this, 'spe.clist', '443060', '8', event);">HD현대마린솔루션</a></th>
<td>226,000</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 30,300 </td>
<td>
<em class="up">
				+15.48%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=0008Z0" onclick="clickcr(this, 'spe.clist', '0008Z0', '9', event);">에스엔시스</a></th>
<td>41,250</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 5,400 </td>
<td>
<em class="up">
				+15.06%
				</em>
</td>
</tr>
<tr class="up">

In [30]:
# div_data에서 table 태그 중 class 값이 tbl_home인 태그의 개수가 어떻게 되는가?
len(
    div_data.find_all(
        'table',
        attrs = {
            'class' : 'tbl_home'
        }
    )
)

8

krx 거래상위 테이블 가져오기: 다른 테이블들은 반복

In [32]:
# 8개의 테이블을 모두 찾는다.

tables = div_data.find_all(
    'table',
    attrs = {
        'class': 'tbl_home'
    }
)

In [ ]:
tables[0]

# thead는 테이블의 제목 (column 이름 → 따로 추출하여 columns 사용)
# tbody는 테이블의 데이터 (values → 따로 추출하여 values 사용)

<table class="tbl_home">
<caption>거래상위 TOP 종목<span>종목명에 대한 현재가, 전일대비, 등락률로 구분되어 있습니다.</span></caption>
<colgroup>
<col width="40%"/>
<col/>
</colgroup>
<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>
<tbody id="_topItems1">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>182</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 9</td>
<td>
<em class="down">
				-4.71%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=114800" onclick="clickcr(this, 'spe.slist', '114800', '2', event);">KODEX 인버스</a></th>
<td>1,396</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 36</td>
<td>
<em class="down">
				-2.51%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=462330" onclick="clickcr(this, 'spe.slist', '462330', '3', event);">KODEX 2차전지산업레버리지</a></th>
<td>2,565</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 410</td>
<td>
<em class="up">
				+19.03%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=047040" onclick="clickcr(this, 'spe.slist', '047040', '4', event);">대우건설</a></th>
<td>33,150</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 5,050</td>
<td>
<em class="up">
				+17.97%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078130" onclick="clickcr(this, 'spe.slist', '078130', '5', event);">국일제지</a></th>
<td>470</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 108</td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=065420" onclick="clickcr(this, 'spe.slist', '065420', '6', event);">에스아이리소스</a></th>
<td>309</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 10</td>
<td>
<em class="up">
				+3.34%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=131760" onclick="clickcr(this, 'spe.slist', '131760', '7', event);">파인텍</a></th>
<td>2,015</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 442</td>
<td>
<em class="up">
				+28.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=203650" onclick="clickcr(this, 'spe.slist', '203650', '8', event);">드림시큐리티</a></th>
<td>3,915</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 35</td>
<td>
<em class="up">
				+0.90%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=184230" onclick="clickcr(this, 'spe.slist', '184230', '9', event);">SGA솔루션즈</a></th>
<td>1,097</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 51</td>
<td>
<em class="up">
				+4.88%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=530036" onclick="clickcr(this, 'spe.slist', '530036', '10', event);">삼성 인버스 2X WTI원유 선물 ETN</a></th>
<td>23</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1</td>
<td>
<em class="up">
				+4.55%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=092220" onclick="clickcr(this, 'spe.slist', '092220', '11', event);">KEC</a></th>
<td>1,372</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 149</td>
<td>
<em class="up">
				+12.18%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=222080" onclick="clickcr(this, 'spe.slist', '222080', '12', event);">씨아이에스</a></th>
<td>16,310</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,760</td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011930" onclick="clickcr(this, 'spe.slist', '011930', '13', event);">신성이엔지</a></th>
<td>3,945</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 45</td>
<td>
<em class="up">
				+1.15%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011000" onclick="clickcr(this, 'spe.slist', '011000', '14', event);">진원생명과학</a></th>
<td>1,415</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 93</td>
<td>
<em class="up">
				+7.03%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252710" onclick="clickcr(this, 'spe.slist', '252710', '15', event);">TIGER 200선물인버스2X</a></th>
<td>192</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 12</td>
<td>
<em class="down">
				-5.88%
				</em>
</td>
</tr>
</tbody>
</table>

In [35]:
# 반복문에서 사용할 변수명을 그대로 이용하여 1차 작업
table_data = tables[0]

In [ ]:
# columns에서 사용할 데이터들을 추출 → table 데이터에서 thead 태그를 추출
head_data = table_data.find('thead')

In [37]:
head_data

<thead>
<tr>
<th scope="col">종목명</th>
<th scope="col">현재가</th>
<th scope="col">전일대비</th>
<th scope="col">등락률</th>
</tr>
</thead>

In [39]:
# head_data에서 th 태그를 모두 찾는다
th_list = head_data.find_all('th')
# 각각 th 태그에서 콘텐츠를 추출하여 리스트로 만든다.
    # 콘텐츠를 추출하는 방법은 string // get_text()
th_list[0].get_text()

'종목명'

In [40]:
cols = []
for th in th_list:
    cols.append(th.string)

cols

['종목명', '현재가', '전일대비', '등락률']

In [41]:
cols2 = list(
    map(
        lambda x: x.string,
        th_list
    )
)

cols2

['종목명', '현재가', '전일대비', '등락률']

In [42]:
cols3 = [th.string for th in th_list]
cols3

['종목명', '현재가', '전일대비', '등락률']

In [44]:
# values에서 사용할 데이터들을 추출
body_data = table_data.find('tbody')
body_data

<tbody id="_topItems1">
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>182</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 9</td>
<td>
<em class="down">
				-4.71%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=114800" onclick="clickcr(this, 'spe.slist', '114800', '2', event);">KODEX 인버스</a></th>
<td>1,396</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 36</td>
<td>
<em class="down">
				-2.51%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=462330" onclick="clickcr(this, 'spe.slist', '462330', '3', event);">KODEX 2차전지산업레버리지</a></th>
<td>2,565</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 410</td>
<td>
<em class="up">
				+19.03%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=047040" onclick="clickcr(this, 'spe.slist', '047040', '4', event);">대우건설</a></th>
<td>33,150</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 5,050</td>
<td>
<em class="up">
				+17.97%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=078130" onclick="clickcr(this, 'spe.slist', '078130', '5', event);">국일제지</a></th>
<td>470</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 108</td>
<td>
<em class="up">
				+29.83%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=065420" onclick="clickcr(this, 'spe.slist', '065420', '6', event);">에스아이리소스</a></th>
<td>309</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 10</td>
<td>
<em class="up">
				+3.34%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=131760" onclick="clickcr(this, 'spe.slist', '131760', '7', event);">파인텍</a></th>
<td>2,015</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 442</td>
<td>
<em class="up">
				+28.10%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=203650" onclick="clickcr(this, 'spe.slist', '203650', '8', event);">드림시큐리티</a></th>
<td>3,915</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 35</td>
<td>
<em class="up">
				+0.90%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=184230" onclick="clickcr(this, 'spe.slist', '184230', '9', event);">SGA솔루션즈</a></th>
<td>1,097</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 51</td>
<td>
<em class="up">
				+4.88%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=530036" onclick="clickcr(this, 'spe.slist', '530036', '10', event);">삼성 인버스 2X WTI원유 선물 ETN</a></th>
<td>23</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 1</td>
<td>
<em class="up">
				+4.55%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=092220" onclick="clickcr(this, 'spe.slist', '092220', '11', event);">KEC</a></th>
<td>1,372</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 149</td>
<td>
<em class="up">
				+12.18%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=222080" onclick="clickcr(this, 'spe.slist', '222080', '12', event);">씨아이에스</a></th>
<td>16,310</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 3,760</td>
<td>
<em class="up">
				+29.96%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011930" onclick="clickcr(this, 'spe.slist', '011930', '13', event);">신성이엔지</a></th>
<td>3,945</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 45</td>
<td>
<em class="up">
				+1.15%
				</em>
</td>
</tr>
<tr class="up">
<th scope="row"><a href="/item/main.naver?code=011000" onclick="clickcr(this, 'spe.slist', '011000', '14', event);">진원생명과학</a></th>
<td>1,415</td>
<td><em class="bu_p bu_pup"><span class="blind">상승</span></em> 93</td>
<td>
<em class="up">
				+7.03%
				</em>
</td>
</tr>
<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252710" onclick="clickcr(this, 'spe.slist', '252710', '15', event);">TIGER 200선물인버스2X</a></th>
<td>192</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 12</td>
<td>
<em class="down">
				-5.88%
				</em>
</td>
</tr>
</tbody>

In [ ]:
# tr을 모두 찾는다.

tr_list = body_data.find_all(
    'tr'
)

len(tr_list)

15

In [48]:
# 첫번째 tr 데이터에서 value를 추출: 15번 반복
tr = tr_list[0]
tr

<tr class="down">
<th scope="row"><a href="/item/main.naver?code=252670" onclick="clickcr(this, 'spe.slist', '252670', '1', event);">KODEX 200선물인버스2X</a></th>
<td>182</td>
<td><em class="bu_p bu_pdn"><span class="blind">하락</span></em> 9</td>
<td>
<em class="down">
				-4.71%
				</em>
</td>
</tr>

In [50]:
# 두 개의 태그를 모두 찾는다?
row_list = tr.find_all(['th', 'td'])

In [53]:
row_list[2].get_text()

'하락 9'

In [55]:
value_data = [data.get_text().strip() for data in row_list]
value_data

['KODEX 200선물인버스2X', '182', '하락 9', '-4.71%']

In [57]:
values = []

for tr in tr_list:
    row_list = tr.find_all(['th', 'td'])
    value_data = [data.get_text().strip() for data in row_list]
    values.append(value_data)

values

[['KODEX 200선물인버스2X', '182', '하락 9', '-4.71%'],
 ['KODEX 인버스', '1,396', '하락 36', '-2.51%'],
 ['KODEX 2차전지산업레버리지', '2,565', '상승 410', '+19.03%'],
 ['대우건설', '33,150', '상승 5,050', '+17.97%'],
 ['국일제지', '470', '상승 108', '+29.83%'],
 ['에스아이리소스', '309', '상승 10', '+3.34%'],
 ['파인텍', '2,015', '상승 442', '+28.10%'],
 ['드림시큐리티', '3,915', '상승 35', '+0.90%'],
 ['SGA솔루션즈', '1,097', '상승 51', '+4.88%'],
 ['삼성 인버스 2X WTI원유 선물 ETN', '23', '상승 1', '+4.55%'],
 ['KEC', '1,372', '상승 149', '+12.18%'],
 ['씨아이에스', '16,310', '상승 3,760', '+29.96%'],
 ['신성이엔지', '3,945', '상승 45', '+1.15%'],
 ['진원생명과학', '1,415', '상승 93', '+7.03%'],
 ['TIGER 200선물인버스2X', '192', '하락 12', '-5.88%']]

In [2]:
import pandas as pd

In [60]:
pd.DataFrame(values, columns=cols)

                       종목명     현재가      전일대비      등락률
0         KODEX 200선물인버스2X     182      하락 9   -4.71%
1                KODEX 인버스   1,396     하락 36   -2.51%
2         KODEX 2차전지산업레버리지   2,565    상승 410  +19.03%
3                     대우건설  33,150  상승 5,050  +17.97%
4                     국일제지     470    상승 108  +29.83%
5                  에스아이리소스     309     상승 10   +3.34%
6                      파인텍   2,015    상승 442  +28.10%
7                   드림시큐리티   3,915     상승 35   +0.90%
8                  SGA솔루션즈   1,097     상승 51   +4.88%
9   삼성 인버스 2X WTI원유 선물 ETN      23      상승 1   +4.55%
10                     KEC   1,372    상승 149  +12.18%
11                   씨아이에스  16,310  상승 3,760  +29.96%
12                   신성이엔지   3,945     상승 45   +1.15%
13                  진원생명과학   1,415     상승 93   +7.03%
14        TIGER 200선물인버스2X     192     하락 12   -5.88%

In [61]:
# 8개의 테이블 중 1개 완성
    # 8번 반복을 하는 반복문을 생성 
    # → 각각의 데이터프레임이 생성 
    # → 각각 다른 전역변수에 저장(globals)

# 전역변수 이름을 반복 실행할 때마다 변경하기 위한 기본값
vari_num = 1

for table_data in tables:
    # thead 추출: columns
    head_data = table_data.find('thead')
    cols = [th.string for th in th_list]

    # tbody 추출: values
    body_data = table_data.find('tbody')
    tr_list = body_data.find_all('tr')

    values = []

    for tr in tr_list:
        row_list = tr.find_all(['th', 'td'])
        value_data = [data.get_text().strip() for data in row_list]
        values.append(value_data)

    globals()[f"df{vari_num}"] = pd.DataFrame(values, columns=cols)
    vari_num += 1

In [69]:
df8

          종목명        현재가        전일대비      등락률
0        삼성전자    218,000    상승 3,500   +1.63%
1      SK하이닉스  1,222,000   상승 56,000   +4.80%
2         현대차    545,000   상승 18,000   +3.42%
3    LG에너지솔루션    472,500   상승 43,500  +10.14%
4       SK스퀘어    714,000   상승 13,000   +1.85%
5     두산에너빌리티    115,400    상승 4,400   +3.96%
6    삼성바이오로직스  1,596,000    하락 9,000   -0.56%
7   한화에어로스페이스  1,395,000   하락 30,000   -2.11%
8          기아    160,300    상승 2,900   +1.84%
9     HD현대중공업    569,000   상승 45,000   +8.59%
10       KB금융    160,200      하락 700   -0.44%
11       삼성전기    771,000   상승 91,000  +13.38%
12      삼성SDI    643,000  상승 105,000  +19.52%
13       삼성생명    255,250    상승 1,750   +0.69%
14       삼성물산    304,000    상승 4,000   +1.33%

In [70]:
!pip install html5lib

Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: six>=1.9 in c:\users\hkssn\appdata\roaming\python\python314\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, html5lib

   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   -------------------- ------------------- 1/2 [html5lib]
   ---------------------------------------- 2/2 [html5lib]

Successfully installed html5lib-1.1 webencodings-0.5.1

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

In [3]:
res = requests.get('https://finance.naver.com')
soup = bs(res.text, 'html.parser')

In [4]:
div_data = soup.find(
    'div',
    attrs = {
        'class': 'section_sise_top'
    }
)

In [5]:
type(div_data)

bs4.element.Tag

In [6]:
type(str(div_data))

str

In [7]:
str_div_data = str(div_data)

In [8]:
from io import StringIO

In [9]:
# html 문서 안에서 table 안에 데이터를 크롤링하려면
# pandas 호출

pd.read_html(StringIO(str(div_data)), encoding='cp949')

[                       종목명    현재가      전일대비       등락률
 0         KODEX 200선물인버스2X    175      하락 6    -3.31%
 1                KODEX 인버스   1371     하락 20    -1.44%
 2                      KEC   1771     하락 72    -3.91%
 3               키움히어로제2호스팩   5890  상승 3,890  +194.50%
 4                 오가닉티코스메틱    178     상승 33   +22.76%
 5                     대원전선   7780  상승 1,340   +20.81%
 6                    신성이엔지   4440    상승 310    +7.51%
 7   삼성 인버스 2X WTI원유 선물 ETN     21        보합     0.00%
 8                     대우건설  35000  상승 2,450    +7.53%
 9         KODEX 2차전지산업레버리지   2515    하락 120    -4.55%
 10                     파인텍   1722    하락 318   -15.59%
 11        TIGER 200선물인버스2X    185      하락 5    -2.63%
 12       KODEX 코스닥150선물인버스   2007      상승 7    +0.35%
 13                    국일제지    424     하락 24    -5.36%
 14                  동일스틸럭스   1556    상승 251   +19.23%,
             종목명      현재가       전일대비      등락률
 0            후성    14610     상승 510   +3.62%
 1          삼성전자   225750   상승 8,250   +3.79%
 2         삼성중공업    32500     상승 700   +2.20%
 3          명신산업    12030     상승 560   +4.88%
 4       LS마린솔루션    38250   상승 4,500  +13.33%
 5       두산에너빌리티   122600   상승 6,700   +5.78%
 6       솔루스첨단소재    15410   상승 1,910  +14.15%
 7         애경케미칼    17440   하락 1,660   -8.69%
 8         서울반도체    11060     상승 290   +2.69%
 9          GS건설    42550     상승 850   +2.04%
 10         DS단석    25950     하락 300   -1.14%
 11      아이티엠반도체    18600     상승 770   +4.32%
 12  LS ELECTRIC   210000  상승 15,800   +8.14%
 13       SK하이닉스  1250000  상승 27,000   +2.21%
 14          티엠씨    30750   상승 1,650   +5.67%,
                      종목명     현재가       전일대비       등락률
 0             키움히어로제2호스팩    5890   상승 3,890  +194.50%
 1                  대원전선우    5330  상한가 1,230   +30.00%
 2                     3S    1816    상한가 419   +29.99%
 3                   나노캠텍    1015    상한가 234   +29.96%
 4                  코스텍시스   32650   상승 7,150   +28.04%
 5                   서전기전    6750   상승 1,310   +24.08%
 6               오가닉티코스메틱     178      상승 33   +22.76%
 7                   가온전선  220000  상승 40,000   +22.22%
 8                  태영건설우   14650   상승 2,650   +22.08%
 9                   대원전선    7780   상승 1,340   +20.81%
 10                동일스틸럭스    1556     상승 251   +19.23%
 11                  네오리진    1696     상승 266   +18.60%
 12                사피엔반도체   43200   상승 6,550   +17.87%
 13                  인스코비     517      상승 78   +17.77%
 14  한투 레버리지WTI원유선물 ETN B   55000   상승 7,740   +16.38%,
             종목명     현재가       전일대비      등락률
 0          가온전선  220000  상승 40,000  +22.22%
 1        사피엔반도체   43500   상승 6,850  +18.69%
 2       솔루스첨단소재   15410   상승 1,910  +14.15%
 3       LS마린솔루션   38250   상승 4,500  +13.33%
 4   LS ELECTRIC  210000  상승 15,800   +8.14%
 5       LS에코에너지   64800   상승 4,800   +8.00%
 6           유니드   92600   상승 6,700   +7.80%
 7          제룡전기   55100   상승 3,100   +5.96%
 8          한전기술  191000  상승 10,600   +5.88%
 9       두산에너빌리티  122600   상승 6,700   +5.78%
 10          티엠씨   30750   상승 1,650   +5.67%
 11         일진전기   92400   상승 4,900   +5.60%
 12        해성디에스   72100   상승 3,600   +5.26%
 13           쿠콘   31550   상승 1,550   +5.17%
 14        달바글로벌  224000  상승 11,000   +5.16%,
                              종목명    현재가       전일대비      등락률
 0                            파인텍   1722    하락 -318  -15.59%
 1                        에이에프더블류   1578    하락 -273  -14.75%
 2                          정원엔시스   1456    하락 -230  -13.64%
 3                         티웨이홀딩스    266     하락 -39  -12.79%
 4    신한 블룸버그 인버스2X WTI원유선물 ETN B   3275    하락 -455  -12.20%
 5    삼성 블룸버그 인버스2X WTI원유선물 ETN B   3290    하락 -445  -11.91%
 6                        SGA솔루션즈    948    하락 -120  -11.24%
 7     메리츠 인버스 2X WTI원유 선물 ETN(H)   3415    하락 -430  -11.18%
 8   하나 S&P 인버스 2X WTI원유 선물 ETN B   3350    하락 -400  -10.67%
 9                            이니텍   3055    하락 -360  -10.54%
 10  KB S&P 인버스 2X WTI원유 선물 ETN B   3400    하락 -400  -10.53%
 11         한투 인버스2XWTI원유선물 ETN B   3360    하락 -385  -10.28%
 12                          대동기어  19350  하락 -2,100   -9.79%
 13                           제이오  12250  하락 -1,310   -9.66%
 14                            포톤   3155    하락 -335   -9.60%,
           종목명     현재가        전일대비     등락률
 0       애경케미칼   17440   하락 -1,660  -8.69%
 1        삼양컴텍   13310     하락 -790  -5.60%
 2          엔켐   50400   하락 -2,900  -5.44%
 3      덕산테코피아   23975   하락 -1,375  -5.42%
 4        필에너지   20700   하락 -1,150  -5.26%
 5       삼천당제약  382500  하락 -20,500  -5.09%
 6        기가비스   89000   하락 -4,500  -4.81%
 7     아이쓰리시스템  107200   하락 -5,200  -4.63%
 8   이수스페셜티케미컬  124200   하락 -5,900  -4.53%
 9   HD현대마린솔루션  222000  하락 -10,500  -4.52%
 10       율촌화학   26450   하락 -1,250  -4.51%
 11      삼화콘덴서   62500   하락 -2,900  -4.43%
 12     오리엔탈정공    8220     하락 -380  -4.42%
 13     위메이드맥스    6290     하락 -290  -4.41%
 14     OCI홀딩스  300500  하락 -13,500  -4.30%,
           종목명      현재가       전일대비     등락률
 0        삼성전자   226000   상승 8,500  +3.91%
 1      SK하이닉스  1248500  상승 25,500  +2.09%
 2       삼성전자우   158700   상승 7,400  +4.89%
 3         현대차   543000   상승 2,000  +0.37%
 4    LG에너지솔루션   466500  하락 18,000  -3.72%
 5       SK스퀘어   735000  상승 15,000  +2.08%
 6     두산에너빌리티   122500   상승 6,600  +5.69%
 7   한화에어로스페이스  1407000   하락 9,000  -0.64%
 8    삼성바이오로직스  1554000   하락 7,000  -0.45%
 9     HD현대중공업   624000  하락 17,000  -2.65%
 10         기아   160800     상승 800  +0.50%
 11       삼성전기   792000  하락 20,000  -2.46%
 12       KB금융   155100   하락 2,300  -1.46%
 13      삼성SDI   643000  하락 16,000  -2.43%
 14       삼성생명   253500   상승 6,000  +2.42%,
           종목명      현재가       전일대비     등락률
 0        삼성전자   225750   상승 8,250  +3.79%
 1      SK하이닉스  1250000  상승 27,000  +2.21%
 2         현대차   543000   상승 2,000  +0.37%
 3    LG에너지솔루션   466000  하락 18,500  -3.82%
 4       SK스퀘어   737000  상승 17,000  +2.36%
 5     두산에너빌리티   122600   상승 6,700  +5.78%
 6   한화에어로스페이스  1406000  하락 10,000  -0.71%
 7    삼성바이오로직스  1556000   하락 5,000  -0.32%
 8     HD현대중공업   624000  하락 17,000  -2.65%
 9          기아   160700     상승 700  +0.44%
 10       삼성전기   792000  하락 20,000  -2.46%
 11       KB금융   155600   하락 1,800  -1.14%
 12      삼성SDI   642500  하락 16,500  -2.50%
 13       삼성생명   254000   상승 6,500  +2.63%
 14       삼성물산   311500  상승 10,500  +3.49%]