### 데이터의 분할

- 분석 모델을 학습하고 성과를 확인하기 위해서 데이터를 Train, Test 세트로 나눠주는 작업
- 독립 변수와 종속 변수 모두 Train, Test 데이터로 나눠준다.
- 데이터를 분할하는 일반적인 비율
    - Train : Test = 7:3 // 8:2
    - Train : Validation : Test = 6:2:2
        - 데이터의 양이 많은 경우 검증 셋을 생성하여 2번의 검증 작업
    - k-fold 교차검증, 장점: 신뢰도 상승, 단점: 오래 걸림
    - 유의할 점
        - 데이터의 불균형 문제
        - 데이터의 균형을 알맞게 분할하는 작업이 필요
- sklearn 안에 train_test_split() 함수를 이용하여 데이터를 분할
    - train_test_split(X, y, test_size = None, random_state = None, shuffle = True, stratify = None)
        - X: 독립 변수(문제)
        - y: 종속 변수(정답)
        - test_size: test 데이터의 비율 (0~1)
        - random_state: 임의의 데이터를 추출하는 과정에서 seed 값을 지정
        - shuffle: 데이터를 섞을 것인가(시계열 데이터셋인 경우에는 False)
        - stratify: 특정 변수를 지정하면 해당 변수를 기준으로 계층화. 해당 변수의 비율을 유지하도록 데이터 분할

In [1]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [2]:
iris_data = load_iris()

In [3]:
iris = pd.DataFrame(iris_data['data'], columns = iris_data['feature_names'])

iris['class'] = iris_data['target']

iris.head()

   sepal length (cm)  sepal width (cm)  ...  petal width (cm)  class
0                5.1               3.5  ...               0.2      0
1                4.9               3.0  ...               0.2      0
2                4.7               3.2  ...               0.2      0
3                4.6               3.1  ...               0.2      0
4                5.0               3.6  ...               0.2      0

[5 rows x 5 columns]

In [4]:
# target 데이터들을 변환

iris['class'] = iris['class'].map(
    lambda x: iris_data['target_names'][x]
)

In [5]:
iris

     sepal length (cm)  sepal width (cm)  ...  petal width (cm)      class
0                  5.1               3.5  ...               0.2     setosa
1                  4.9               3.0  ...               0.2     setosa
2                  4.7               3.2  ...               0.2     setosa
3                  4.6               3.1  ...               0.2     setosa
4                  5.0               3.6  ...               0.2     setosa
..                 ...               ...  ...               ...        ...
145                6.7               3.0  ...               2.3  virginica
146                6.3               2.5  ...               1.9  virginica
147                6.5               3.0  ...               2.0  virginica
148                6.2               3.4  ...               2.3  virginica
149                5.9               3.0  ...               1.8  virginica

[150 rows x 5 columns]

In [6]:
iris['class'].value_counts()

class
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [7]:
X = iris.drop('class', axis=1)
y = iris['class']

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.3, random_state = 42
)

In [9]:
# 데이터의 개수를 확인
print(f'X_train: {X_train.shape}, X_test: {X_test.shape}')
print(f'y_train: {y_train.shape}, y_test: {y_test.shape}')

X_train: (105, 4), X_test: (45, 4)
y_train: (105,), y_test: (45,)

In [10]:
y_train.value_counts()

class
versicolor    37
virginica     37
setosa        31
Name: count, dtype: int64

In [ ]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(
    X, y, test_size = 0.3, shuffle=False, random_state=42
)

In [12]:
y_train2.value_counts()

class
setosa        50
versicolor    50
virginica      5
Name: count, dtype: int64

In [ ]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(
    X, y, test_size = 0.3, stratify=y, random_state=42
)

In [14]:
y_train3.value_counts()

class
setosa        35
virginica     35
versicolor    35
Name: count, dtype: int64