### Pandas, Series, DataFrame

In [3]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=2.3.3 in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hkssn\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\hkssn\appdata\local\programs\python\python314\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\hkssn\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [35]:
# 1차원 데이터인 Series 형태 생성

series_1 = pd.Series([5000, 6000, 6500, 6500])

In [36]:
series_1

0    5000
1    6000
2    6500
3    6500
dtype: int64

In [37]:
series_2 = pd.Series([5000, 6000, 6500, 6500],
                    index = ['아메리카노', '카페라떼', '카페모카', '마끼아또'])

In [38]:
series_2

# dtype에서는 데이터(5000, 6000 등)의 유형을 보여줌
    # 아메리카노, 카페라떼 등은 index임

아메리카노    5000
카페라떼     6000
카페모카     6500
마끼아또     6500
dtype: int64

In [39]:
# 특정 데이터에 접근하려면 index를 기준으로 데이터를 추출
series_2['아메리카노']
# 1차원 데이터 Series에서 필터의 값이 단일 데이터라면: 데이터 차원의 수는 1 감소
    # 1차원 데이터 → 단일 데이터(0차원 데이터)

np.int64(5000)

In [40]:
# Series 안에는 변수가 적어도 2개가 존재
    # 클래스를 생성할 때 2개의 데이터를 입력값으로 사용했기 때문
# 그러면 클래스 안에 values, index 변수의 데이터를 수정이 가능한가?
    # 가능
# Series에서 index 값을 바꾸려면

# series_1.index = ['a', 'b', 'c']
    # Error
    # 본래 series_1의 index는 4개였기에 4개를 써야 함

series_1.index = ['a', 'b', 'c', 'd']

# 인덱스에 데이터가 대입이 된다 → 원본의 Series 데이터가 변화

In [41]:
series_1

a    5000
b    6000
c    6500
d    6500
dtype: int64

In [42]:
# 인덱스의 값을 변경하는 함수 존재
    # 함수 호출 시 출력 확인 가능 → 원본의 데이터는 유지된다는 뜻

series_1.rename(
    index={
    'a': 1
    }
)

1    5000
b    6000
c    6500
d    6500
dtype: int64

In [43]:
series_1

# 원본 데이터 유지 중

a    5000
b    6000
c    6500
d    6500
dtype: int64

In [44]:
series_1.rename(index={ 'a' : 1 }, inplace=True)
print(series_1)

# 덮어씌워주는 방식도 가능

1    5000
b    6000
c    6500
d    6500
dtype: int64

In [45]:
series_11 = series_1.copy()

# 잘못된 코드
series_11 = series_11.rename(
    index = {
        'c' : 5
    }, inplace=True
)

In [46]:
series_11

# 출력값이 아무것도 없다. 이유는?
# inplace=True 일 때 return 값이 없으므로 series_11=None이라 한 것과 같다.
    # 빈 공간을 가지는 변수를 생성하는 것과 같은 것

In [47]:
# Series에서 values이 타입들이 각각 다르다면 dtype은 뭐라고 나올 것인가?
series_3 = pd.Series([1, 'kim', True])

In [48]:
series_3

# dtype: object 출력

0       1
1     kim
2    True
dtype: object

In [49]:
# Series에는 2개의 변수가 존재
# values, index
# index 값을 바꾸고 싶다면?

print(series_2.index)
print(series_2.values)

Index(['아메리카노', '카페라떼', '카페모카', '마끼아또'], dtype='str')
[5000 6000 6500 6500]

In [50]:
print(series_2.index[1])
series_2.index[1] = '오곡라떼'

카페라떼

TypeError: Index does not support mutable operations

In [51]:
series_2 = series_2.rename(index={'카페라떼' : '오곡라떼' })
print(series_2)

아메리카노    5000
오곡라떼     6000
카페모카     6500
마끼아또     6500
dtype: int64

In [52]:
# 그렇다면 values는?

series_2.values[1] = 6300

ValueError: assignment destination is read-only

In [53]:
series_2['오곡라떼'] = 6300
print(series_2)

아메리카노    5000
오곡라떼     6300
카페모카     6500
마끼아또     6500
dtype: int64

In [54]:
# DataFrame(2차원 데이터 생성)

values = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
cols = ['A', 'B', 'C']

# 일반적으로 index는 기본값 사용, columns은 만들어서 변경

df = pd.DataFrame(values, columns=cols)

In [55]:
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [56]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [58]:
# Series와 DataFrame은 모두 pandas 안에 있는 클래스
    # → 사용하는 함수들도 같은 이름의 함수가 많다.
# DataFrame은 Series를 상속 받아서 사용
    # ex. rename()
        # Series에서는 index 값을 변경할 때 사용
        # DataFrame에서는 index의 값과 columns의 값을 모두 변경할 수 있음
            # 오버라이드의 예시!

df2 = df.rename(columns={
    "C" : "D"
})

In [59]:
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [60]:
df2

   A  B  D
0  1  2  3
1  4  5  6
2  7  8  9

In [61]:
df3 = df
df3

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [62]:
df3.rename(
    index={
        0:10
    }, inplace=True
)

In [ ]:
df
# Series, DataFrame도 list와 같이 =을 이용해서 복사를 하게 되면 얕은 복사
    # 같은 주소를 사용한다.

    A  B  C
10  1  2  3
1   4  5  6
2   7  8  9

In [65]:
df4 = df.copy()

# 깊은 복사

In [ ]:
df4.rename(index={10:0}, inplace=True)

In [67]:
df4

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [69]:
df

    A  B  C
10  1  2  3
1   4  5  6
2   7  8  9

In [70]:
# 함수를 이용해서 DataFrame을 수정한다.
# 컬럼의 이름을 변경하는 함수

def func_1(data):
    # 방법 1: rename 함수 이용
        # 특정 column의 이름을 변경할 때
    # 방법 2: DataFrame.columns 변수를 선택해서 변경
        # 모든 column의 이름을 변경할 때
        # (column의 개수와 같은 길이의 데이터를 대입)

    data.columns = ['a', 'b', 'c']
    return data

In [71]:
func_1(df)

    a  b  c
10  1  2  3
1   4  5  6
2   7  8  9

In [ ]:
df

# 할당을 하지 않았는데 데이터가 바뀌어져 있다.
    # func_1() 함수가 처음 하는 일이 data = df
        # 즉, 얕은 복사가 일어난다는 것
            # 원본 데이터 유지가 되지 않는다

# 데이터의 원본을 유지하려면 .copy() 함수를 사용해서 데이터를 복사

    a  b  c
10  1  2  3
1   4  5  6
2   7  8  9

In [74]:
# 함수를 이용해서 DataFrame을 수정한다.
# 컬럼의 이름을 변경하는 함수

def func_1(data):
    result = data.copy()
    result.columns = ['a', 'b', 'c']
    return result

In [75]:
func_1(df2)

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

In [76]:
df2

   A  B  D
0  1  2  3
1  4  5  6
2  7  8  9

### 데이터 load

#### pandas 라이브러리에서 외부의 데이터를 로드하는 함수들
- csv, tsv
    - 가장 단순한 형태의 데이터 파일
    - pandas에 내장된 read_csv() 함수를 사용해서 데이터 로드
    - csv는 데이터를 ',' 기준으로 나눠준다.
        - read_csv(경로)를 이용하여 로드
    - tsv는 데이터를 '  '(탭) 기준으로 나눠준다.
        - read_csv() 함수에서 sep 매개변수에 인자값을 '\t'로 설정

- json
    - 많이 사용하는 데이터 파일 (특히 웹에서)
    - python으로 생각하면 dict 형태와 같다.
    - pandas에서 read_json() 함수를 사용해서 데이터 로드

- xml
    - html 구조 언어와 같이 tag를 이용해서 데이터가 구성
        - ex) <data>'abc'</data>
    - pandas에서 read_xml() 함수를 사용해서 데이터 로드

- 전부 DataFrame으로 바꿔준다.
- 위 3개의 read_xxx() 함수들은 공통적으로 encoding 이라는 매개변수가 존재
    - 기본값은 'UTF-8'
    - 데이터 파일을 로드하는데 해당 데이터셋에 한글이 존재하는 경우에 종종 에러가 발생
        - 이때 인자값을 'CP949', 'EUC-KR'로 사용하면 데이터 로드가 가능

    - 엑셀 파일을 로드하는 함수에는 encoding 매개변수가 존재하지 않는다.

- excel(xls, xlsx)
    - 엑셀 데이터 파일
    - pandas에서 read_excel() 함수를 사용해서 데이터 로드
    - 특정 엑셀 파일을 로드할 때 추가적인 라이브러리 설치가 필요한 경우가 존재
        - 특정 라이브러리가 존재하지 않는다면 모듈을 찾을 수 없습니다 라는 에러가 발생
            - 에러 발생시 해당 라이브러리를 설치 (openpyxl)

- 모든 read_xxx() 함수에서 첫번째 인자값은 파일의 경로를 입력

#### 경로

- 절대 경로
    - 절대적인 주소 값
    - 환경이 변하더라도 같은 위치를 언제나 지정
    - ex) url, window 기준 c:/users/admin/document/a.txt

- 상대 경로
    - 상대적인 주소 값
    - 환경이 변할 때 위치도 변한다.
    - ex) 옆집
    - 종류
        - ./ → 현재 작업중인 경로 (내가 지금 수정하고 있는 파일의 위치)
            - 생략 가능
        - ../ → 현재 작업중인 경로에서 상위 경로로 이동
        - 폴더명 → 하위 폴더로 이동

In [ ]:
# 절대 경로를 이용하여 데이터 파일을 로드
df = pd.read_csv(r'C:\Users\hkssn\OneDrive\바탕 화면\multicam\csv\corona.csv')
    # 떼끄놀로지야...
        # 떼끄놀로지 아니야...

# 절대 경로를 윈도우 메뉴로 복사하는 경우 에러가 발생 (\ 때문에)

# 헐 개떼끄놀로지 미쳤다 나는 한번도 이래본적이 없는데
    # r-string... r-string... 와 미쳤ㄷㅏ
    # 우리 학교 교수님은 이거 아실까 아시는데 왜 안 가르쳐주셨을까

In [ ]:
# 상대 경로를 이용해서 데이터 파일을 로드
    # 추천!
    # url 같은 경우는 절대 경로를 사용

df2 = pd.read_csv('../csv/corona.csv')

In [81]:
# 데이터들의 상위 5개 출력
df.head()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
0,0,2022-06-08 09:09:05.982,24305,18188200,904,20220608,00:00,NaN,NaN,NaN
1,1,2022-06-07 09:09:00.897,24299,18174842,903,20220607,00:00,2022-06-08 09:10:36.846,NaN,NaN
2,2,2022-06-06 09:00:06.734,24279,18168670,902,20220606,00:00,2022-06-08 09:10:50.441,NaN,NaN
3,3,2022-06-05 08:53:19.426,24258,18163648,901,20220605,00:00,2022-06-08 09:11:04.758,NaN,NaN
4,4,2022-06-04 08:56:49.219,24238,18153814,900,20220604,00:00,2022-06-08 09:11:26.303,NaN,NaN

In [83]:
# 데이터들의 마지막 n개를 출력
df.tail()

,Unnamed: 0,createDt,deathCnt,decideCnt,seq,stateDt,stateTime,updateDt,accExamCnt,accDefRate
815,815,2020-03-14 00:00:00.000,72,8086,55,20200314,00:00,2021-10-07 10:30:51.51,261335.0,3.318000
816,816,2020-03-13 00:00:00.000,67,7979,54,20200313,00:00,2021-10-07 10:30:51.51,248647.0,3.458499
817,817,2020-03-12 00:00:00.000,66,7869,53,20200312,00:00,2021-10-07 10:30:51.51,234998.0,3.621744
818,818,2020-03-11 00:00:00.000,60,7755,52,20200311,00:00,2021-10-07 10:30:51.51,222395.0,3.804175
819,819,2020-03-10 00:00:00.000,54,7513,51,20200310,00:00,2021-10-07 10:30:51.51,210144.0,3.919308

In [ ]:
# 데이터의 정보를 출력하는 함수

df.info()

# <class 'pandas.DataFrame'> : 데이터 타입
# 인덱스의 범위
# 세번째 줄부터는 data columns 목록 (총 10개), 해당하는 컬럼

<class 'pandas.DataFrame'>
RangeIndex: 820 entries, 0 to 819
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  820 non-null    int64
 1   createDt    820 non-null    str
 2   deathCnt    820 non-null    int64
 3   decideCnt   820 non-null    int64
 4   seq         820 non-null    int64
 5   stateDt     820 non-null    int64
 6   stateTime   820 non-null    str
 7   updateDt    817 non-null    str
 8   accExamCnt  692 non-null    float64
 9   accDefRate  623 non-null    float64
dtypes: float64(2), int64(5), str(3)
memory usage: 64.2 KB

In [ ]:
# 결측치 → 데이터가 없다.
# 데이터가 손상이 생겼다. // DB에서 해당 데이터가 입력이 되지 않았다.
# 결측치는 주요 확인 ( info() 함수를 사용하여 non-null count 확인 )
# 결측치를 찾는 함수가 존재 (결측치: na // nan, 존재 유무: is)
    # isna()
# 결과값 bool 형태를 합산 → index를 기준으로 합산 // column을 기준으로 합산

df.isna().sum()

# isna() == True인 값들만 합산

Unnamed: 0      0
createDt        0
deathCnt        0
decideCnt       0
seq             0
stateDt         0
stateTime       0
updateDt        3
accExamCnt    128
accDefRate    197
dtype: int64

In [ ]:
df.isna().sum(axis='columns')

# DataFrame 안에 sum() 함수는 기본적으로 column을 기준으로 합산
    # 매개변수는 축(axis)
    # axis default는 rows, 또는 0
    # columns로 바꿔주거나, 1로 바꿔주면 index 기준 합산

# index별 결측치 개수를 보여줌

0      3
1      2
2      2
3      2
4      2
      ..
815    0
816    0
817    0
818    0
819    0
Length: 820, dtype: int64

In [89]:
# any()
# or 조건식을 사용해서 T/F 값을 반환

df.isna().any()

Unnamed: 0    False
createDt      False
deathCnt      False
decideCnt     False
seq           False
stateDt       False
stateTime     False
updateDt       True
accExamCnt     True
accDefRate     True
dtype: bool

In [90]:
df.isna().any(axis=1)

0       True
1       True
2       True
3       True
4       True
       ...
815    False
816    False
817    False
818    False
819    False
Length: 820, dtype: bool

In [91]:
# 반대로 and 조건의 경우 all()
df.isna().all()

Unnamed: 0    False
createDt      False
deathCnt      False
decideCnt     False
seq           False
stateDt       False
stateTime     False
updateDt      False
accExamCnt    False
accDefRate    False
dtype: bool

In [92]:
# is: 존재의 유무, in: 포함 여부
# isna()는 결측치의 존재 유무였다면
    # 함수명에 어떤 데이터를 찾을 것인가가 지정
        # 인자 없이도 구동 가능
# isin()은 특정 데이터가 포함되어있는가?
    # 1차원 dataset이 필수 인자

In [94]:
# 통계 요약 정보를 출력하는 함수
# describe() → dtype이 숫자형인 데이터들의 통계정보를 출력
# 결측치: 값이 없는 것
# 이상치: 예를 들어 값이 1, 2, 3, 4, 5 뿐인 데이터에서 9 등의 값
# 극단치: 너무 심하게 값이 크거나 작은 데이터

df.describe()

,Unnamed: 0,deathCnt,decideCnt,seq,stateDt,accExamCnt,accDefRate
count,820.000000,820.000000,8.200000e+02,820.000000,8.200000e+02,6.920000e+02,623.000000
mean,409.500000,3927.832927,1.913097e+06,472.393902,2.020897e+07,7.545057e+06,1.556435
std,236.857904,6164.310693,4.857030e+06,249.701095,7.118265e+03,6.172020e+06,0.543014
min,0.000000,54.000000,7.513000e+03,51.000000,2.020031e+07,2.101440e+05,0.902205
25%,204.750000,415.750000,2.393525e+04,256.750000,2.020100e+07,1.934309e+06,1.078089
50%,409.500000,1812.500000,1.185640e+05,461.500000,2.021042e+07,6.368310e+06,1.416159
75%,614.250000,3120.500000,3.979915e+05,698.250000,2.021112e+07,1.216890e+07,1.816009
max,819.000000,24305.000000,1.818820e+07,904.000000,2.022061e+07,2.151807e+07,3.919308

In [ ]:
# tsv 파일을 로드
# sep = '\t' 가 핵심!

chipotle = pd.read_csv('../csv/num_1/chipotle.tsv', sep='\t')

In [97]:
chipotle.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [100]:
# 주민등록.csv 파일을 로드

df3 = pd.read_csv('../csv/주민등록.csv', encoding='CP949')

In [101]:
df3.head()

,자치구코드(atdrc_code_se),자치구명(atdrc_nm),년월(년월),총인구수(tot_popltn_co),세대수(tot_hshld_co),세대당인구(hshld_popltn_avrg_co),남자인구수(male_popltn_co),여자인구수(female_popltn_co),적재일시(ldadng_dt)
0,금천구,11110,201907,228755,171426,2.44,319062,118352,2018-01-05 16:52:25
1,서대문구,11290,201607,153780,186744,2.12,75614,116393,2018-12-05 10:20:57
2,양천구,11740,201804,594315,61091,2.22,192817,307237,2020-11-03 10:50:11
3,은평구,11200,202004,345156,168865,2.13,229690,204108,2018-01-05 16:52:25
4,마포구,11260,201902,394788,168482,2.52,61714,146951,2018-01-05 16:52:25

In [102]:
df4 = pd.read_json('../csv/2022/202202_expense_list.json')

In [104]:
df4.head(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,25844143,2022년 2월 사업소 도로사업소 서부도로사업소 업무추진비 - 기관운영 시책추진 부서운영,http://opengov.seoul.go.kr/expense/25844143,사업소,도로사업소,서부도로사업소,,,2022,2,0,0,,서부도로사업소 기전과,2022-02-11 14:52,다농마트(마포구 월드컵로 235),부서운영 물품구입,기전과장 외 48명,제로페이,230630

In [107]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.4-cp314-cp314-win_amd64.whl.metadata (3.2 kB)
Downloading lxml-6.0.4-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.1 MB ? eta -:--:--
   ---------- ----------------------------- 1.0/4.1 MB 3.9 MB/s eta 0:00:01
   ------------------ --------------------- 1.8/4.1 MB 3.5 MB/s eta 0:00:01
   ------------------------- -------------- 2.6/4.1 MB 3.7 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.1 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 4.0 MB/s  0:00:01
Installing collected packages: lxml
Successfully installed lxml-6.0.4

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [108]:
# lxml 에러 → lxml 라이브러리 설치

df5 = pd.read_xml('../csv/2022/202202_expense_list.xml')

In [110]:
df5.head(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,25844143,2022년 2월 사업소 도로사업소 서부도로사업소 업무추진비 - 기관운영 시책추진 부서운영,http://opengov.seoul.go.kr/expense/25844143,사업소,도로사업소,서부도로사업소,NaN,NaN,2022,2,0,0,NaN,서부도로사업소 기전과,2022-02-11 14:52,다농마트(마포구 월드컵로 235),부서운영 물품구입,기전과장 외 48명,제로페이,230630

In [112]:
!pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [113]:
# excel 파일 로드
# modulenotfound
# openpyxl 라이브러리 설치 필요

df6 = pd.read_excel('../csv/2022/202202_expense_list.xlsx')

In [115]:
df6.head(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,25844143,2022년 2월 사업소 도로사업소 서부도로사업소 업무추진비 - 기관운영 시책추진 부서운영,http://opengov.seoul.go.kr/expense/25844143,사업소,도로사업소,서부도로사업소,NaN,NaN,2022,2,0,0,NaN,서부도로사업소 기전과,2022-02-11 14:52,다농마트(마포구 월드컵로 235),부서운영 물품구입,기전과장 외 48명,제로페이,230630

In [116]:
import numpy as np

In [ ]:
_value = [
    [1, 2, np.nan, 4, 5],
    [1, np.nan, 3, 4, 5],
    [1, 2, 3, 4, np.nan]
]

_cols = ['a', 'b', 'c', 'd', 'e']

df = pd.DataFrame(_value, columns=_cols)
df

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  NaN  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [119]:
# 결측치는 연산이 되지 않는다
# 결측치에 뭘 더하든 빼든 곱하든 나누든 아무튼 무언가를 하든 결과는 결측치

print(3 * np.nan)
print(4 + np.nan)
print(np.nan - 5)
print(np.nan / 6)

nan
nan
nan
nan

In [120]:
np.nan == np.nan

False

In [121]:
# pandas에서는 데이터 연산을 할 때 결측치를 제외하고 연산이 가능
# R언어에는 결측치가 포함된 데이터셋을 연산을 하면 결측치 도출

df.sum()

a     3.0
b     4.0
c     6.0
d    12.0
e    10.0
dtype: float64

In [122]:
# df에 비교 연산자를 사용하면?
df == 1

      a      b      c      d      e
0  True  False  False  False  False
1  True  False  False  False  False
2  True  False  False  False  False

In [128]:
print(df == np.nan)

print('-'*40)

print(df.isna())

       a      b      c      d      e
0  False  False  False  False  False
1  False  False  False  False  False
2  False  False  False  False  False
----------------------------------------
       a      b      c      d      e
0  False  False   True  False  False
1  False   True  False  False  False
2  False  False  False  False   True

#### 결측치의 처리
1. 결측치 데이터를 제거
    - 결측치가 포함되어있는 column을 제거
        - 해당 column의 data가 중요하지 않은 경우
    - 결측치가 포함되어있는 index를 제거
        - 일반적으로 결측치가 포함되어있는 index의 수가 전체 data의 수보다 5% 미만인 경우
        - 결측치가 포함된 index의 데이터 신뢰도가 떨어지는 경우
    - 결측치를 제거하는 함수
        - 결측치(na) + 버리다/지우다(drop)
        - dropna()
            - 매개변수 axis : 기준이 되는 축 지정
                - default rows(0)
                - 결측치가 포함되어있는 인덱스를 제거
                - 값을 columns나 1로 변경하면 결측치가 포함된 column을 제거
            - 매개변수 inplace
                - default False
                - 원본 데이터(class 내부에 저장된 변수 데이터)를 변경할 것인가 지정

2. 결측치를 특정한 값으로 채워준다
    - 채우다(fill) + 결측치(na)
    - fillna()
        - 인자에 특정 데이터를 입력
            - 결측치가 해당 인자 값으로 치환
    - ffill: front fill
        - 결측치 직전의 데이터로 대체
    - bfill: back fill
        - 결측치 직후의 데이터로 대체

##### 결측치를 제거

In [129]:
# 결측치가 포함된 index를 제거 → 모든 index가 제거
# 결측치가 포함된 column을 제거 → a, d column을 제외한 모든 column이 제거

df.dropna(axis='columns')

   a  d
0  1  4
1  1  4
2  1  4

In [130]:
df.dropna()

Empty DataFrame
Columns: [a, b, c, d, e]
Index: []

##### 결측치 대체

In [131]:
df.fillna(10)

   a     b     c  d     e
0  1   2.0  10.0  4   5.0
1  1  10.0   3.0  4   5.0
2  1   2.0   3.0  4  10.0

In [132]:
df.ffill()

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  2.0  3.0  4  5.0
2  1  2.0  3.0  4  5.0

In [133]:
df.bfill()

   a    b    c  d    e
0  1  2.0  3.0  4  5.0
1  1  2.0  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [135]:
# 특정 column은 선택한 Series//DataFrame에 fillna() 사용

df['b'].fillna(20, inplace=True)

C:\Users\hkssn\AppData\Local\Temp\ipykernel_24708\2714047177.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['b'].fillna(20, inplace=True)

0     2.0
1    20.0
2     2.0
Name: b, dtype: float64

In [ ]:
df

# inplace=True를 했는데 바뀌지 않는다...?

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  NaN  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [ ]:
# 주로 쓰는 방법

df['b'] = df['b'].fillna(20)
df

# 이 때 df['b']에 할당하는 것이 아닌 df에 할당하면 시리즈가 되어버림
    # 말 그대로 할당이니까

   a     b    c  d    e
0  1   2.0  NaN  4  5.0
1  1  20.0  3.0  4  5.0
2  1   2.0  3.0  4  NaN

#### DataFrame의 Filter

- df.loc[ index의 조건식, column의 조건식 ]
    - index의 값을 기준으로 filter (index가 같은 경우(True)에만 출력)
    - column의 값을 기준으로 filter (column이 같은 경우(True)에만 출력)
    - 시작 : 종료
        - → 시작값부터 종료값까지 (종료가 포함)

- df.iloc[ index의 위치, column의 위치 ]
    - index의 위치를 기준으로 filter
    - column의 위치를 기준으로 filter
    - 시작 : 종료
        - → 시작 위치부터 종료 위치 전까지 (종료 위치는 미포함)

- 특정 column의 data를 확인
    - df[단일 column]
        - → 조건이 단일이라면 df는 Series로 변환하여 추출
    - df[ [col1, col2, ...] ]
        - → 조건이 복수의 타입 (ex: list, tuple) 이라면 df로 추출

In [ ]:
df

   a     b    c  d    e
0  1   2.0  NaN  4  5.0
1  1  20.0  3.0  4  5.0
2  1   2.0  3.0  4  NaN

In [ ]:
# loc를 이용하여 filter
# index의 값이 0부터 2까지

df.loc[0:1]

   a     b    c  d    e
0  1   2.0  NaN  4  5.0
1  1  20.0  3.0  4  5.0
2  1   2.0  3.0  4  NaN

In [ ]:
#     a	b	c	d	e
# 0	1	2.0	NaN	4	5.0
# 1	1	20.0	3.0	4	5.0
# 2	1	2.0	3.0	4	NaN

In [141]:
df.iloc[0:2]

   a     b    c  d    e
0  1   2.0  NaN  4  5.0
1  1  20.0  3.0  4  5.0

In [142]:
# index의 조건이 단일인 경우 → 차원이 1개 축소

df.index = ['A', 'B', 'C']

In [ ]:
# 컬럼의 조건식 a 인덱스의 조건식은 시작부터 끝까지

print(type(df.loc[:, 'a']))
print(type(df.loc[:, ['a']])) # 단일 데이터임에도 df 출력

<class 'pandas.Series'>
<class 'pandas.DataFrame'>

In [146]:
df['b']

A     2.0
B    20.0
C     2.0
Name: b, dtype: float64

In [147]:
flag = df['b'] == 2.0
df.loc[flag,]

   a    b    c  d    e
A  1  2.0  NaN  4  5.0
C  1  2.0  3.0  4  NaN

In [ ]:
# 결측치가 포함되어있는 데이터를 확인
# 인덱스의 조건식으로 결측치가 포함되어있는가?
# 결측치가 포함되어 있는 데이터 filtering

flag_null = df.isna().any(axis=1)
df.loc[flag_null,]

   a    b    c  d    e
A  1  2.0  NaN  4  5.0
C  1  2.0  3.0  4  NaN

In [152]:
flag_not_null = ~df.isna().any(axis=1)
df.loc[flag_not_null,]

   a     b    c  d    e
B  1  20.0  3.0  4  5.0

In [ ]:
# - 붙여주기

df.loc[-flag_null,]

   a     b    c  d    e
B  1  20.0  3.0  4  5.0

In [155]:
# 나는 너무 바보같이했어
df.loc[~flag_null,]

   a     b    c  d    e
B  1  20.0  3.0  4  5.0

In [159]:
# 반복문으로 같은 과정 만들기
# values 데이터들을 하나씩 추출하여 not() 함수를 이용해서 부정 처리

flag_list = []

for i in flag_null:
    flag_list.append(not(i))

flag_list

[False, True, False]

In [ ]:
df.loc[flag_list,]          # 리스트도 사용 가능

   a     b    c  d    e
B  1  20.0  3.0  4  5.0

In [162]:
# map()
    # 1차원 데이터를 각각 원소별 변환이 필요할때 사용하는 함수
# map( 함수, 1차원 데이터 )

list_1 = [1, 2, 3, 4]

def func_1(x):
    return x ** 2


list(
    map(
        func_1, list_1
    )
)

[1, 4, 9, 16]

In [164]:
# map() + lambda 함수
    # 내가 벽 느꼈던 lambda...

# lambda 함수: 이름 없는 함수 (단순한 계산식을 사용할 때)
    # 휘발성 함수: 한번 사용하고 사라짐
    # lambda 매개변수: 매개변수의 연산
    # return 만들 필요도 없음
        # 네 처음 쓰는 사람 저요 헷갈려하는 거 저요 약간 벽느꼈어요

list(
    map(
        lambda x : x ** 2,
        list_1
    )
)

[1, 4, 9, 16]

In [165]:
# 기존 파이썬 내장 함수인 map() 은 func, list 모두 요구
    # 출력값 map data
# Series 내장 함수로 map()이 있음
    # Series.map()
    # 데이터는 Series 함수가 담고 있으므로, 우리가 적어줄 것은 'func'뿐
    # 출력값도 series (Series 내장 함수이기에)

In [ ]:
# Series 안에 map 함수 존재

print(flag_null)

flag_null.map(
    # x 라는 매개변수에는 True, False, True가 순차적으로 입력
        # 이 때 x의 data type은 bool
        # bool 에는 not() 사용 가능
    lambda x : not(x)
)

# lambda 함수는 연산이 간단한 경우에만 사용

A     True
B    False
C     True
dtype: bool

A    False
B     True
C    False
dtype: bool

In [170]:
def func_2(x):
    return not(x)

flag_null.map(func_2)

A    False
B     True
C    False
dtype: bool

In [2]:
import pandas as pd
import numpy as np

_value = [
    [1, 2, np.nan, 4, 5],
    [1, np.nan, 3, 4, 5],
    [1, 2, 3, 4, np.nan]
]

_cols = ['a', 'b', 'c', 'd', 'e']

df = pd.DataFrame(_value, columns=_cols)
df

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  NaN  3.0  4  5.0
2  1  2.0  3.0  4  NaN

In [3]:
df.loc[0:1]

   a    b    c  d    e
0  1  2.0  NaN  4  5.0
1  1  NaN  3.0  4  5.0

In [4]:
df.iloc[0:1]

   a    b   c  d    e
0  1  2.0 NaN  4  5.0