In [1]:
import pandas as pd

### tran_1, tran_2: concat()

In [2]:
tran_1 = pd.read_csv('../csv/tran_1.csv')
tran_2 = pd.read_csv('../csv/tran_2.csv')

In [3]:
tran_1.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [4]:
tran_2.head(1)

  transaction_id   price         payment_date customer_id
0    T0000005113  295000  2019-06-15 07:20:27    TS169261

In [5]:
tran_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  5000 non-null   str
 1   price           5000 non-null   int64
 2   payment_date    5000 non-null   str
 3   customer_id     5000 non-null   str
dtypes: int64(1), str(3)
memory usage: 156.4 KB

In [6]:
tran_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1786 entries, 0 to 1785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  1786 non-null   str
 1   price           1786 non-null   int64
 2   payment_date    1786 non-null   str
 3   customer_id     1786 non-null   str
dtypes: int64(1), str(3)
memory usage: 55.9 KB

In [7]:
# pandas에서 concat 함수를 호출하면 inplace 사용 불가
# 저장할 변수 따로 지정

tran = pd.concat(
    [tran_1, tran_2], axis=0, ignore_index=True
)

In [8]:
tran.info()

<class 'pandas.DataFrame'>
RangeIndex: 6786 entries, 0 to 6785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6786 non-null   str
 1   price           6786 non-null   int64
 2   payment_date    6786 non-null   str
 3   customer_id     6786 non-null   str
dtypes: int64(1), str(3)
memory usage: 212.2 KB

### tran_d_1, tran_d_2: concat()

In [9]:
# tran_d_1.csv, tran_d_2.csv load

tran_d_1 = pd.read_csv('../csv/tran_d_1.csv')
tran_d_2 = pd.read_csv('../csv/tran_d_2.csv')

In [10]:
tran_d_1.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [11]:
tran_d_2.head(1)

   detail_id transaction_id item_id  quantity
0       5000    T0000004870    S002         3

In [12]:
tran_d_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       5000 non-null   int64
 1   transaction_id  5000 non-null   str
 2   item_id         5000 non-null   str
 3   quantity        5000 non-null   int64
dtypes: int64(2), str(2)
memory usage: 156.4 KB

In [13]:
tran_d_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       2144 non-null   int64
 1   transaction_id  2144 non-null   str
 2   item_id         2144 non-null   str
 3   quantity        2144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 67.1 KB

In [14]:
tran_d = pd.concat(
    [tran_d_1, tran_d_2], axis=0, ignore_index=True
)

tran_d

      detail_id transaction_id item_id  quantity
0             0    T0000000113    S005         1
1             1    T0000000114    S001         1
2             2    T0000000115    S003         1
3             3    T0000000116    S005         1
4             4    T0000000117    S002         2
...         ...            ...     ...       ...
7139       7139    T0000006894    S004         1
7140       7140    T0000006895    S002         1
7141       7141    T0000006896    S001         2
7142       7142    T0000006897    S002         1
7143       7143    T0000006898    S002         1

[7144 rows x 4 columns]

In [15]:
tran_d.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   str
 2   item_id         7144 non-null   str
 3   quantity        7144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 223.4 KB

### tran, tran_d: merge()

In [16]:
tran.info()

<class 'pandas.DataFrame'>
RangeIndex: 6786 entries, 0 to 6785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6786 non-null   str
 1   price           6786 non-null   int64
 2   payment_date    6786 non-null   str
 3   customer_id     6786 non-null   str
dtypes: int64(1), str(3)
memory usage: 212.2 KB

In [17]:
tran_d.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   str
 2   item_id         7144 non-null   str
 3   quantity        7144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 223.4 KB

In [18]:
# tran과 tran_d 데이터프레임을 결합
# 테이블의 구조는 다르게 구성 → 단순한 행결합 불가능
# 인덱스의 개수가 다르다 → 6786, 7144개의 데이터
    # tran: 거래 발생 로그
    # tran_d: 거래 발생 시 품목에 대한 로그
    # 두 데이터의 성격이 달라서 row 개수의 차이가 있을 수 있음

tran_d['transaction_id'].value_counts()

transaction_id
T0000000790    4
T0000000231    3
T0000000383    3
T0000000397    3
T0000000513    3
              ..
T0000006894    1
T0000006895    1
T0000006896    1
T0000006897    1
T0000006898    1
Name: count, Length: 6786, dtype: int64

In [19]:
# 데이터프레임의 고유값
    # tran: transaction_id
    # tran_d: detail_id

In [20]:
tran['transaction_id'].describe()

count            6786
unique           6786
top       T0000000113
freq                1
Name: transaction_id, dtype: object

In [21]:
tran_d['detail_id'].describe()

count    7144.000000
mean     3571.500000
std      2062.439494
min         0.000000
25%      1785.750000
50%      3571.500000
75%      5357.250000
max      7143.000000
Name: detail_id, dtype: float64

In [22]:
# 두 개의 데이터프레임이 공통적으로 가지고 있는 컬럼은?
    # transaction_id → join 결합 가능

pd.merge(
    tran, tran_d,
    on = 'transaction_id',
    how = 'inner'
)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1
1,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1
2,T0000000115,120000,2019-02-01 02:34:19,HD298120,2,S003,1
3,T0000000116,210000,2019-02-01 02:47:23,IK452215,3,S005,1
4,T0000000117,170000,2019-02-01 04:33:46,PL542865,4,S002,2
...,...,...,...,...,...,...,...
7139,T0000006894,180000,2019-07-31 21:20:44,HI400734,7139,S004,1
7140,T0000006895,85000,2019-07-31 21:52:48,AS339451,7140,S002,1
7141,T0000006896,100000,2019-07-31 23:35:25,OA027325,7141,S001,2
7142,T0000006897,85000,2019-07-31 23:39:35,TS624738,7142,S002,1
7143,T0000006898,85000,2019-07-31 23:41:38,AS834214,7143,S002,1

In [23]:
pd.merge(
    tran, tran_d,
    on = 'transaction_id',
    how = 'left'
)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1
1,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1
2,T0000000115,120000,2019-02-01 02:34:19,HD298120,2,S003,1
3,T0000000116,210000,2019-02-01 02:47:23,IK452215,3,S005,1
4,T0000000117,170000,2019-02-01 04:33:46,PL542865,4,S002,2
...,...,...,...,...,...,...,...
7139,T0000006894,180000,2019-07-31 21:20:44,HI400734,7139,S004,1
7140,T0000006895,85000,2019-07-31 21:52:48,AS339451,7140,S002,1
7141,T0000006896,100000,2019-07-31 23:35:25,OA027325,7141,S001,2
7142,T0000006897,85000,2019-07-31 23:39:35,TS624738,7142,S002,1
7143,T0000006898,85000,2019-07-31 23:41:38,AS834214,7143,S002,1

In [24]:
pd.merge(
    tran, tran_d,
    on = 'transaction_id',
    how = 'right'
)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1
1,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1
2,T0000000115,120000,2019-02-01 02:34:19,HD298120,2,S003,1
3,T0000000116,210000,2019-02-01 02:47:23,IK452215,3,S005,1
4,T0000000117,170000,2019-02-01 04:33:46,PL542865,4,S002,2
...,...,...,...,...,...,...,...
7139,T0000006894,180000,2019-07-31 21:20:44,HI400734,7139,S004,1
7140,T0000006895,85000,2019-07-31 21:52:48,AS339451,7140,S002,1
7141,T0000006896,100000,2019-07-31 23:35:25,OA027325,7141,S001,2
7142,T0000006897,85000,2019-07-31 23:39:35,TS624738,7142,S002,1
7143,T0000006898,85000,2019-07-31 23:41:38,AS834214,7143,S002,1

In [58]:
transaction = pd.merge(
    tran, tran_d,
    on = 'transaction_id',
    how = 'outer'
)

In [26]:
transaction

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1
1,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1
2,T0000000115,120000,2019-02-01 02:34:19,HD298120,2,S003,1
3,T0000000116,210000,2019-02-01 02:47:23,IK452215,3,S005,1
4,T0000000117,170000,2019-02-01 04:33:46,PL542865,4,S002,2
...,...,...,...,...,...,...,...
7139,T0000006894,180000,2019-07-31 21:20:44,HI400734,7139,S004,1
7140,T0000006895,85000,2019-07-31 21:52:48,AS339451,7140,S002,1
7141,T0000006896,100000,2019-07-31 23:35:25,OA027325,7141,S001,2
7142,T0000006897,85000,2019-07-31 23:39:35,TS624738,7142,S002,1
7143,T0000006898,85000,2019-07-31 23:41:38,AS834214,7143,S002,1

### 데이터 결합 연습

1. transaction df와 csv 폴더 안 item_master 파일 로드하여 결합
2. 결합된 데이터에 csv 폴더 안 customer_master 파일 로드하여 결합
3. payment_date column의 데이터를 시계열로 변환

In [27]:
# 1

item = pd.read_csv('../csv/item_master.csv')
item

  item_id item_name  item_price
0    S001      PC-A       50000
1    S002      PC-B       85000
2    S003      PC-C      120000
3    S004      PC-D      180000
4    S005      PC-E      210000

In [28]:
item.info()     # item_id

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item_id     5 non-null      str
 1   item_name   5 non-null      str
 2   item_price  5 non-null      int64
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [29]:
transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   str
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   str
 3   customer_id     7144 non-null   str
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   str
 6   quantity        7144 non-null   int64
dtypes: int64(3), str(4)
memory usage: 390.8 KB

In [30]:
tran_item = pd.merge(
    transaction, item,
    on = 'item_id',
    how = 'left'
)

In [31]:
# 2)

cust = pd.read_csv('../csv/customer_master.csv')
cust.head(1)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0

In [32]:
cust.info()     # customer_id

<class 'pandas.DataFrame'>
RangeIndex: 4192 entries, 0 to 4191
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4192 non-null   str
 1   name         4192 non-null   str
 2   class        4192 non-null   str
 3   gender       4192 non-null   str
 4   start_date   4192 non-null   str
 5   end_date     1350 non-null   str
 6   campaign_id  4192 non-null   str
 7   is_deleted   4192 non-null   int64
dtypes: int64(1), str(7)
memory usage: 262.1 KB

In [33]:
tran_item.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   str
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   str
 3   customer_id     7144 non-null   str
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   str
 6   quantity        7144 non-null   int64
 7   item_name       7144 non-null   str
 8   item_price      7144 non-null   int64
dtypes: int64(4), str(5)
memory usage: 502.4 KB

In [34]:
tran_ic = pd.merge(
    tran_item, cust,
    on = 'customer_id',
    how = 'left'
)

tran_ic.head(1)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1,PC-E,210000,XX,C01,M,2018-07-01 00:00:00,NaN,CA1,0.0

In [35]:
# 3)

tran_ic['payment_date'] = pd.to_datetime(tran_ic['payment_date'])
tran_ic.head(1)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1,PC-E,210000,XX,C01,M,2018-07-01 00:00:00,NaN,CA1,0.0

In [36]:
tran_ic.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   str
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   datetime64[us]
 3   customer_id     7144 non-null   str
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   str
 6   quantity        7144 non-null   int64
 7   item_name       7144 non-null   str
 8   item_price      7144 non-null   int64
 9   name            6069 non-null   str
 10  class           6069 non-null   str
 11  gender          6069 non-null   str
 12  start_date      6069 non-null   str
 13  end_date        1978 non-null   str
 14  campaign_id     6069 non-null   str
 15  is_deleted      6069 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(4), str(10)
memory usage: 893.1 KB

### 강사님 풀이

In [59]:
item_master = pd.read_csv('../csv/item_master.csv')
customer_master = pd.read_csv('../csv/customer_master.csv')

In [38]:
# 1)
# df에서 작업을 하는데도 inplace=True가 없다

df = transaction.merge(
    item_master,
    on='item_id',
    how='inner',
)

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   str
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   str
 3   customer_id     7144 non-null   str
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   str
 6   quantity        7144 non-null   int64
 7   item_name       7144 non-null   str
 8   item_price      7144 non-null   int64
dtypes: int64(4), str(5)
memory usage: 502.4 KB

In [40]:
# 2)
# how에 따라서 index 값이 많이 달라짐

customer_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 4192 entries, 0 to 4191
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4192 non-null   str
 1   name         4192 non-null   str
 2   class        4192 non-null   str
 3   gender       4192 non-null   str
 4   start_date   4192 non-null   str
 5   end_date     1350 non-null   str
 6   campaign_id  4192 non-null   str
 7   is_deleted   4192 non-null   int64
dtypes: int64(1), str(7)
memory usage: 262.1 KB

In [41]:
pd.merge(
    df, customer_master,
    on = 'customer_id',
    how = 'right'
).info()

<class 'pandas.DataFrame'>
RangeIndex: 7709 entries, 0 to 7708
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6069 non-null   str
 1   price           6069 non-null   float64
 2   payment_date    6069 non-null   str
 3   customer_id     7709 non-null   str
 4   detail_id       6069 non-null   float64
 5   item_id         6069 non-null   str
 6   quantity        6069 non-null   float64
 7   item_name       6069 non-null   str
 8   item_price      6069 non-null   float64
 9   name            7709 non-null   str
 10  class           7709 non-null   str
 11  gender          7709 non-null   str
 12  start_date      7709 non-null   str
 13  end_date        2493 non-null   str
 14  campaign_id     7709 non-null   str
 15  is_deleted      7709 non-null   int64
dtypes: float64(4), int64(1), str(11)
memory usage: 963.8 KB

In [42]:
df = pd.merge(
    df, customer_master,
    on = 'customer_id',
    how = 'inner'
)

In [64]:
list_1 = transaction['customer_id'].unique()
list_2 = customer_master['customer_id'].unique()

In [65]:
new_list = []

for customer in list_1:
    if customer not in list_2:
        # 고객의 ID가 list_2에 존재하지 않는다면
        new_list.append(customer)

new_list

['GD029189',
 'PL674172',
 'HI364290',
 'AS866028',
 'TS301045',
 'OA567188',
 'GD011312',
 'GD960920',
 'TS508850',
 'OA861572',
 'GD246033',
 'PL470875',
 'GD883278',
 'IK397678',
 'HI988473',
 'HI978950',
 'GD021809',
 'GD288833',
 'PL807633',
 'HI780705',
 'IK345440',
 'GD727041',
 'IK844273',
 'OA222039',
 'GD804496',
 'TS771339',
 'PL896084',
 'IK943660',
 'GD638254',
 'PL598638',
 'AS369586',
 'IK466573',
 'GD956496',
 'HI791416',
 'OA911257',
 'HD622485',
 'IK423708',
 'OA142331',
 'GD098828',
 'AS230629',
 'TS855513',
 'TS372874',
 'HD827887',
 'TS179639',
 'AS921368',
 'HI303118',
 'TS808488',
 'HI654320',
 'HD430217',
 'OA283746',
 'TS962550',
 'PL600990',
 'TS451704',
 'AS895302',
 'HD673446',
 'TS722923',
 'OA228291',
 'TS674550',
 'HI183093',
 'HI231462',
 'AS112674',
 'PL538095',
 'IK627931',
 'PL563001',
 'HI247905',
 'PL243765',
 'IK013691',
 'GD850851',
 'TS825520',
 'IK289800',
 'HI733623',
 'GD378835',
 'HI487042',
 'PL484153',
 'TS645665',
 'TS667446',
 'TS985967',
 'IK590154',
 'HI026312',
 'OA760273',
 'OA186884',
 'AS047815',
 'GD150760',
 'PL471011',
 'OA348005',
 'HD108205',
 'OA275501',
 'IK183913',
 'HI561542',
 'HI407816',
 'OA378430',
 'HI754267',
 'PL070030',
 'TS120796',
 'PL212792',
 'AS780890',
 'GD902176',
 'HI400734',
 'IK330019',
 'HD628998',
 'AS882678',
 'OA653324',
 'HI400606',
 'PL634625',
 'HI318091',
 'HI898602',
 'PL301503',
 'HD411688',
 'PL195594',
 'HI626820',
 'HI358653',
 'PL265818',
 'HD123842',
 'AS979183',
 'GD968190',
 'HI672548',
 'HD838779',
 'IK609024',
 'OA118869',
 'TS851428',
 'GD455127',
 'HD962462',
 'AS375220',
 'TS248015',
 'TS425666',
 'GD727286',
 'AS278780',
 'HD461880',
 'OA019548',
 'HI690734',
 'PL681254',
 'OA144055',
 'HD558047',
 'PL591140',
 'PL534834',
 'GD643063',
 'OA195904',
 'HI944908',
 'AS352269',
 'PL980829',
 'IK453239',
 'IK419862',
 'TS474137',
 'GD185040',
 'PL550068',
 'HD761271',
 'TS568764',
 'HI355281',
 'HD938156',
 'GD993938',
 'OA490350',
 'HD912521',
 'PL229747',
 'HD724900',
 'PL486566',
 'IK547632',
 'TS822034',
 'TS683058',
 'PL252397',
 'TS580222',
 'TS624738',
 'AS605111',
 'OA336098',
 'OA959426',
 'HI262793',
 'OA256309',
 'AS644996',
 'PL399121',
 'IK993568',
 'HD668790',
 'TS060125',
 'GD094299',
 'IK818641',
 'IK110954',
 'GD265984',
 'PL102045',
 'HI090280',
 'OA181249',
 'TS257398',
 'AS834628',
 'GD150899',
 'TS355204',
 'PL820272',
 'AS125481',
 'IK476630',
 'TS064786',
 'AS120487',
 'TS045314',
 'AS793257',
 'TS340142',
 'AS033208',
 'HI535598',
 'AS772027',
 'TS898614',
 'PL160503',
 'AS355098',
 'PL167583',
 'GD688950',
 'IK952589',
 'HD992446',
 'HI040881',
 'GD083109',
 'GD034021',
 'OA214023',
 'HD502728',
 'GD308876',
 'OA441791',
 'OA301378',
 'GD154170',
 'OA518938',
 'TS752438',
 'TS260832',
 'IK071733',
 'HI025685',
 'OA765757',
 'AS129796',
 'TS506913',
 'HI078880',
 'OA506453',
 'IK419506',
 'AS568755',
 'AS310768',
 'OA473384',
 'GD843122',
 'HI008566',
 'TS641433',
 'AS892734',
 'AS033898',
 'PL585092',
 'IK963761',
 'OA829464',
 'GD990639',
 'PL447530',
 'PL901816',
 'IK759414',
 'HI510103',
 'TS733060',
 'GD191213',
 'IK163405',
 'HD049383',
 'IK453679',
 'IK299592',
 'IK855920',
 'PL212885',
 'IK424256',
 'TS533240',
 'TS830677',
 'AS639935',
 'IK544197',
 'AS168089',
 'IK153469',
 'HD639099',
 'IK725315',
 'TS562162',
 'HI327600',
 'IK015043',
 'IK597697',
 'PL990239',
 'IK121456',
 'IK099799',
 'TS117978',
 'OA086657',
 'HD794402',
 'HI322241',
 'TS414273',
 'OA373649',
 'PL958111',
 'OA419499',
 'HD214093',
 'PL263245',
 'AS463573',
 'AS727393',
 'AS648839',
 'GD606287',
 'GD854836',
 'OA288436',
 'TS945876',
 'PL690532',
 'HD523310',
 'OA913755',
 'OA310931',
 'AS541179',
 'HI897445',
 'PL613382',
 'GD818751',
 'GD569284',
 'TS290297',
 'OA770389',
 'IK431399',
 'IK866166',
 'TS567737',
 'IK074758',
 'GD124507',
 'AS303022',
 'OA283278',
 'HD247559',
 'OA139077',
 'PL368937',
 'HD940282',
 'IK253267',
 'HI414861',
 'HI995754',
 'IK426871',
 'TS721555',
 'PL557508',
 'HD826841',
 'TS724169',
 'HD184889',
 'PL204290',
 'PL365264',
 'PL170857',
 'AS984476',
 'HI523163',
 'GD132214',
 'IK224764',
 'TS342077',
 'HD794427',
 'GD465345',
 'PL086937',
 'HI444425',
 'GD238109',
 'IK431694',
 'IK504560',
 'HD656297',
 'AS548391',
 'IK487798',
 'GD542439',
 'AS325900',
 'AS711277',
 'HI174776',
 'PL570346',
 'TS806450',
 'AS459936',
 'HD001989',
 'TS215112',
 'HD237842',
 'OA603276',
 'IK349052',
 'AS346715',
 'GD071442',
 'TS875763',
 'PL498703',
 'OA406727',
 'HD502657',
 'PL560462',
 'HI345781',
 'HI715559',
 'GD942457',
 'OA314234',
 'PL697195',
 'HD735632',
 'HD044650',
 'TS291302',
 'OA514276',
 'PL853016',
 'OA254984',
 'HD444151',
 'HD500570',
 'TS267517',
 'PL344424',
 'TS399940',
 'OA168067',
 'HD797921',
 'PL287707',
 'AS192134',
 'AS215309',
 'HI748457',
 'OA497830',
 'IK163905',
 'TS753499',
 'GD192169',
 'IK951311',
 'PL411913',
 'HI139822',
 'HI265546',
 'GD026761',
 'OA237366',
 'OA828946',
 'AS111667',
 'PL870239',
 'TS717899',
 'OA770978',
 'IK299335',
 'HD544869',
 'HI601096',
 'HD438863',
 'PL776592',
 'PL083738',
 'OA012423',
 'HI926999',
 'AS366153',
 'HI295053',
 'OA352170',
 'TS563606',
 'OA093559',
 'OA184387',
 'HI648050',
 'AS886949',
 'OA229900',
 'IK631512',
 'AS123190',
 'HI616611',
 'AS369861',
 'PL804383',
 'OA681007',
 'TS716875',
 'OA838720',
 'HD648882',
 'TS981486',
 'IK420707',
 'HD078028',
 'HD685797',
 'TS429065',
 'TS860951',
 'OA639613',
 'PL866564',
 'IK529029',
 'TS934599',
 'PL049894',
 'IK863423',
 'PL466152',
 'HD660527',
 'PL511118',
 'TS012855',
 'TS712179',
 'OA096648',
 'TS418116',
 'IK432395',
 'GD695904',
 'OA717373',
 'GD569028',
 'GD653232',
 'TS909340',
 'HI422196',
 'GD936161',
 'HI678851',
 'TS069597',
 'AS754176',
 'HI844603',
 'HI248527',
 'GD399384',
 'TS972650',
 'IK164996',
 'PL509689',
 'PL660484',
 'IK777110',
 'HI900832',
 'PL852001',
 'OA481390',
 'HD939520',
 'HD755168',
 'TS897204',
 'GD550784',
 'HD434419',
 'TS005920',
 'AS228133',
 'IK911976',
 'AS034137',
 'HI009305',
 'TS344882',
 'PL361201',
 'AS905186',
 'HD880785',
 'IK311957',
 'GD905295',
 'PL482487']

In [66]:
[customer for customer in list_1 if customer not in list_2]

['GD029189',
 'PL674172',
 'HI364290',
 'AS866028',
 'TS301045',
 'OA567188',
 'GD011312',
 'GD960920',
 'TS508850',
 'OA861572',
 'GD246033',
 'PL470875',
 'GD883278',
 'IK397678',
 'HI988473',
 'HI978950',
 'GD021809',
 'GD288833',
 'PL807633',
 'HI780705',
 'IK345440',
 'GD727041',
 'IK844273',
 'OA222039',
 'GD804496',
 'TS771339',
 'PL896084',
 'IK943660',
 'GD638254',
 'PL598638',
 'AS369586',
 'IK466573',
 'GD956496',
 'HI791416',
 'OA911257',
 'HD622485',
 'IK423708',
 'OA142331',
 'GD098828',
 'AS230629',
 'TS855513',
 'TS372874',
 'HD827887',
 'TS179639',
 'AS921368',
 'HI303118',
 'TS808488',
 'HI654320',
 'HD430217',
 'OA283746',
 'TS962550',
 'PL600990',
 'TS451704',
 'AS895302',
 'HD673446',
 'TS722923',
 'OA228291',
 'TS674550',
 'HI183093',
 'HI231462',
 'AS112674',
 'PL538095',
 'IK627931',
 'PL563001',
 'HI247905',
 'PL243765',
 'IK013691',
 'GD850851',
 'TS825520',
 'IK289800',
 'HI733623',
 'GD378835',
 'HI487042',
 'PL484153',
 'TS645665',
 'TS667446',
 'TS985967',
 'IK590154',
 'HI026312',
 'OA760273',
 'OA186884',
 'AS047815',
 'GD150760',
 'PL471011',
 'OA348005',
 'HD108205',
 'OA275501',
 'IK183913',
 'HI561542',
 'HI407816',
 'OA378430',
 'HI754267',
 'PL070030',
 'TS120796',
 'PL212792',
 'AS780890',
 'GD902176',
 'HI400734',
 'IK330019',
 'HD628998',
 'AS882678',
 'OA653324',
 'HI400606',
 'PL634625',
 'HI318091',
 'HI898602',
 'PL301503',
 'HD411688',
 'PL195594',
 'HI626820',
 'HI358653',
 'PL265818',
 'HD123842',
 'AS979183',
 'GD968190',
 'HI672548',
 'HD838779',
 'IK609024',
 'OA118869',
 'TS851428',
 'GD455127',
 'HD962462',
 'AS375220',
 'TS248015',
 'TS425666',
 'GD727286',
 'AS278780',
 'HD461880',
 'OA019548',
 'HI690734',
 'PL681254',
 'OA144055',
 'HD558047',
 'PL591140',
 'PL534834',
 'GD643063',
 'OA195904',
 'HI944908',
 'AS352269',
 'PL980829',
 'IK453239',
 'IK419862',
 'TS474137',
 'GD185040',
 'PL550068',
 'HD761271',
 'TS568764',
 'HI355281',
 'HD938156',
 'GD993938',
 'OA490350',
 'HD912521',
 'PL229747',
 'HD724900',
 'PL486566',
 'IK547632',
 'TS822034',
 'TS683058',
 'PL252397',
 'TS580222',
 'TS624738',
 'AS605111',
 'OA336098',
 'OA959426',
 'HI262793',
 'OA256309',
 'AS644996',
 'PL399121',
 'IK993568',
 'HD668790',
 'TS060125',
 'GD094299',
 'IK818641',
 'IK110954',
 'GD265984',
 'PL102045',
 'HI090280',
 'OA181249',
 'TS257398',
 'AS834628',
 'GD150899',
 'TS355204',
 'PL820272',
 'AS125481',
 'IK476630',
 'TS064786',
 'AS120487',
 'TS045314',
 'AS793257',
 'TS340142',
 'AS033208',
 'HI535598',
 'AS772027',
 'TS898614',
 'PL160503',
 'AS355098',
 'PL167583',
 'GD688950',
 'IK952589',
 'HD992446',
 'HI040881',
 'GD083109',
 'GD034021',
 'OA214023',
 'HD502728',
 'GD308876',
 'OA441791',
 'OA301378',
 'GD154170',
 'OA518938',
 'TS752438',
 'TS260832',
 'IK071733',
 'HI025685',
 'OA765757',
 'AS129796',
 'TS506913',
 'HI078880',
 'OA506453',
 'IK419506',
 'AS568755',
 'AS310768',
 'OA473384',
 'GD843122',
 'HI008566',
 'TS641433',
 'AS892734',
 'AS033898',
 'PL585092',
 'IK963761',
 'OA829464',
 'GD990639',
 'PL447530',
 'PL901816',
 'IK759414',
 'HI510103',
 'TS733060',
 'GD191213',
 'IK163405',
 'HD049383',
 'IK453679',
 'IK299592',
 'IK855920',
 'PL212885',
 'IK424256',
 'TS533240',
 'TS830677',
 'AS639935',
 'IK544197',
 'AS168089',
 'IK153469',
 'HD639099',
 'IK725315',
 'TS562162',
 'HI327600',
 'IK015043',
 'IK597697',
 'PL990239',
 'IK121456',
 'IK099799',
 'TS117978',
 'OA086657',
 'HD794402',
 'HI322241',
 'TS414273',
 'OA373649',
 'PL958111',
 'OA419499',
 'HD214093',
 'PL263245',
 'AS463573',
 'AS727393',
 'AS648839',
 'GD606287',
 'GD854836',
 'OA288436',
 'TS945876',
 'PL690532',
 'HD523310',
 'OA913755',
 'OA310931',
 'AS541179',
 'HI897445',
 'PL613382',
 'GD818751',
 'GD569284',
 'TS290297',
 'OA770389',
 'IK431399',
 'IK866166',
 'TS567737',
 'IK074758',
 'GD124507',
 'AS303022',
 'OA283278',
 'HD247559',
 'OA139077',
 'PL368937',
 'HD940282',
 'IK253267',
 'HI414861',
 'HI995754',
 'IK426871',
 'TS721555',
 'PL557508',
 'HD826841',
 'TS724169',
 'HD184889',
 'PL204290',
 'PL365264',
 'PL170857',
 'AS984476',
 'HI523163',
 'GD132214',
 'IK224764',
 'TS342077',
 'HD794427',
 'GD465345',
 'PL086937',
 'HI444425',
 'GD238109',
 'IK431694',
 'IK504560',
 'HD656297',
 'AS548391',
 'IK487798',
 'GD542439',
 'AS325900',
 'AS711277',
 'HI174776',
 'PL570346',
 'TS806450',
 'AS459936',
 'HD001989',
 'TS215112',
 'HD237842',
 'OA603276',
 'IK349052',
 'AS346715',
 'GD071442',
 'TS875763',
 'PL498703',
 'OA406727',
 'HD502657',
 'PL560462',
 'HI345781',
 'HI715559',
 'GD942457',
 'OA314234',
 'PL697195',
 'HD735632',
 'HD044650',
 'TS291302',
 'OA514276',
 'PL853016',
 'OA254984',
 'HD444151',
 'HD500570',
 'TS267517',
 'PL344424',
 'TS399940',
 'OA168067',
 'HD797921',
 'PL287707',
 'AS192134',
 'AS215309',
 'HI748457',
 'OA497830',
 'IK163905',
 'TS753499',
 'GD192169',
 'IK951311',
 'PL411913',
 'HI139822',
 'HI265546',
 'GD026761',
 'OA237366',
 'OA828946',
 'AS111667',
 'PL870239',
 'TS717899',
 'OA770978',
 'IK299335',
 'HD544869',
 'HI601096',
 'HD438863',
 'PL776592',
 'PL083738',
 'OA012423',
 'HI926999',
 'AS366153',
 'HI295053',
 'OA352170',
 'TS563606',
 'OA093559',
 'OA184387',
 'HI648050',
 'AS886949',
 'OA229900',
 'IK631512',
 'AS123190',
 'HI616611',
 'AS369861',
 'PL804383',
 'OA681007',
 'TS716875',
 'OA838720',
 'HD648882',
 'TS981486',
 'IK420707',
 'HD078028',
 'HD685797',
 'TS429065',
 'TS860951',
 'OA639613',
 'PL866564',
 'IK529029',
 'TS934599',
 'PL049894',
 'IK863423',
 'PL466152',
 'HD660527',
 'PL511118',
 'TS012855',
 'TS712179',
 'OA096648',
 'TS418116',
 'IK432395',
 'GD695904',
 'OA717373',
 'GD569028',
 'GD653232',
 'TS909340',
 'HI422196',
 'GD936161',
 'HI678851',
 'TS069597',
 'AS754176',
 'HI844603',
 'HI248527',
 'GD399384',
 'TS972650',
 'IK164996',
 'PL509689',
 'PL660484',
 'IK777110',
 'HI900832',
 'PL852001',
 'OA481390',
 'HD939520',
 'HD755168',
 'TS897204',
 'GD550784',
 'HD434419',
 'TS005920',
 'AS228133',
 'IK911976',
 'AS034137',
 'HI009305',
 'TS344882',
 'PL361201',
 'AS905186',
 'HD880785',
 'IK311957',
 'GD905295',
 'PL482487']

In [68]:
len(set(transaction['customer_id']) - set(customer_master['customer_id']))

466

In [43]:
# 3)
# 문자를 시계열로 변경 (datetime.strptime() // to_datetime())

df['payment_date']

0       2019-02-01 01:36:57
1       2019-02-01 01:37:23
2       2019-02-01 02:34:19
3       2019-02-01 02:47:23
4       2019-02-01 04:33:46
               ...
6064    2019-07-31 20:28:20
6065    2019-07-31 21:17:39
6066    2019-07-31 21:52:48
6067    2019-07-31 23:35:25
6068    2019-07-31 23:41:38
Name: payment_date, Length: 6069, dtype: str

In [44]:
df['payment_date'] = pd.to_datetime(df['payment_date'])
df.info()
# dtype: datetime64

<class 'pandas.DataFrame'>
RangeIndex: 6069 entries, 0 to 6068
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6069 non-null   str
 1   price           6069 non-null   int64
 2   payment_date    6069 non-null   datetime64[us]
 3   customer_id     6069 non-null   str
 4   detail_id       6069 non-null   int64
 5   item_id         6069 non-null   str
 6   quantity        6069 non-null   int64
 7   item_name       6069 non-null   str
 8   item_price      6069 non-null   int64
 9   name            6069 non-null   str
 10  class           6069 non-null   str
 11  gender          6069 non-null   str
 12  start_date      6069 non-null   str
 13  end_date        1978 non-null   str
 14  campaign_id     6069 non-null   str
 15  is_deleted      6069 non-null   int64
dtypes: datetime64[us](1), int64(5), str(10)
memory usage: 758.8 KB

In [45]:
# strptime() 함수를 이용한다면
# strptime 함수는 Series 형태 변환 불가
    # Series 데이터에서 value들을 하나씩 뽑아서 함수에 넣는다. (map())

from datetime import datetime

In [46]:
df['payment_date'].map(
    lambda x: datetime.strptime(x, '%Y-%m-%d %H:%M:%S')
)

TypeError: strptime() argument 1 must be str, not Timestamp

### 다른 과정

In [47]:
# 요일별 판매가 된 제품들의 총 판매 개수의 합계가 어떻게 되는가?
# 요일이라는 새로운 변수를 생성 : 시계열에서 요일만 따로 추출

df['payment_date'].dt.strftime('%w')
# 0: 일요일

# 다른 방법
# df['payment_date'].dt.weekday
# 0: 월요일

0       5
1       5
2       5
3       5
4       5
       ..
6064    3
6065    3
6066    3
6067    3
6068    3
Name: payment_date, Length: 6069, dtype: str

In [ ]:
df['요일'] = df['payment_date'].dt.strftime('%A')

In [ ]:
df.head(1)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price,name,class,gender,start_date,end_date,campaign_id,is_deleted,요일
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1,PC-E,210000,XX,C01,M,2018-07-01 00:00:00,NaN,CA1,0,Friday

In [ ]:
# 요일, item_id를 기준으로 그룹화: quantity 합산

df[['요일', 'item_id', 'quantity']].groupby(['요일', 'item_id']).sum()

                   quantity
요일        item_id
Friday    S001          406
          S002          250
          S003          140
          S004          105
          S005          225
Monday    S001          363
          S002          201
          S003          132
          S004           97
          S005          207
Saturday  S001          367
          S002          182
          S003          141
          S004          102
          S005          231
Sunday    S001          390
          S002          236
          S003          121
          S004          121
          S005          210
Thursday  S001          334
          S002          206
          S003          128
          S004          103
          S005          227
Tuesday   S001          336
          S002          227
          S003          121
          S004          107
          S005          212
Wednesday S001          382
          S002          216
          S003           98
          S004          122
          S005          241