### 특정한 경로에 있는 데이터 파일들을 한번에 load (+모듈화 작업)

1. 일반적으로 경로를 설정하고 파일의 이름을 저장하는 방법을 사용
    - 절대 경로
    - 상대 경로

2. 특정 경로에 존재하는 파일의 목록을 확인해서 read_xxx()
    - os 라이브러리
    - glob 라이브러리 + os 라이브러리

3. 파일의 목록을 가지고 있다면 반복문을 이용해서 데이터들을 load
    - 각각의 변수에 데이터를 대입
        - join 결합을 하기 위해 우선 각각 변수에 대입
    - 하나의 데이터프레임으로 결합하여 변수에 저장
        - 같은 구조의 데이터들을 로드하는 경우 하나의 df로 결합(단순 행결합)

In [7]:
# 라이브러리 로드

import os
from glob import glob
import pandas as pd

In [8]:
# os 라이브러리를 이용하여 파일의 목록을 load
# cmd의 명령어를 함수화
    # dir → 현재 경로에서 파일의 목록을 보여주는 명령어
# python에서 목록들을 볼 수 있는 데이터의 형태는 list

# ∴ 함수의 이름이 listdir()
# listdir(): 해당 경로에 있는 모든 파일의 목록을 출력
# os.listdir('경로')

os.listdir('../csv/2017')

['201701_expense_list.csv',
 '201702_expense_list.csv',
 '201703_expense_list.csv',
 '201704_expense_list.csv',
 '201705_expense_list.csv',
 '201706_expense_list.csv',
 '201707_expense_list.csv',
 '201708_expense_list.csv',
 '201709_expense_list.csv',
 '201710_expense_list.csv',
 '201711_expense_list.csv',
 '201712_expense_list.csv']

In [9]:
file_path = '../csv/2017/'
file_list = os.listdir(file_path)

for file_name in file_list:
    # df = pd.read_csv(file_path+file_name)
        # 이렇게 하면 데이터가 계속 덮어씌워진다는 문제점이 있음

_IncompleteInputError: incomplete input (969689139.py, line 6)

In [10]:
# 위 코드 문제 해결
    # 1. 반복실행하면서 다른 전역 변수를 생성 → globals() 사용
    # 2. file_path에 마지막에 '/'가 들어가지 않으면 문제 발생
        # /가 2개 들어가도 정상적으로 작동함

file_path = '../csv/2017'
file_list = os.listdir(file_path)

for file_name in file_list:
    if not(file_path.endswith('/')):
        file_path += '/'
        # print(file_path + file_name)
    # else:
        # file_path += '/'
        # print(file_path + file_name)
        # 참인 경우는 아무 행동도 하지 않는다.
    
    # 반복마다 전역변수 생성
    # 전역변수의 이름은 df_201701, df_201702
    globals()[f'df_{file_name.split('_')[0]}'] = \
        pd.read_csv(file_path + file_name)

In [11]:
df_201701.info()

<class 'pandas.DataFrame'>
RangeIndex: 5517 entries, 0 to 5516
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                5517 non-null   int64
 1   title              5517 non-null   str
 2   url                5517 non-null   str
 3   dept_nm_lvl_1      5517 non-null   str
 4   dept_nm_lvl_2      5517 non-null   str
 5   dept_nm_lvl_3      4842 non-null   str
 6   dept_nm_lvl_4      1350 non-null   str
 7   dept_nm_lvl_5      252 non-null    str
 8   exec_yr            5517 non-null   int64
 9   exec_month         5517 non-null   int64
 10  expense_budget     274 non-null    float64
 11  expense_execution  202 non-null    float64
 12  category           115 non-null    str
 13  dept_nm_full       5517 non-null   str
 14  exec_dt            5517 non-null   str
 15  exec_loc           5467 non-null   str
 16  exec_purpose       5516 non-null   str
 17  target_nm          5486 non-null   str
 18  payment_method     5514 non-null   str
 19  exec_amount        5517 non-null   int64
dtypes: float64(2), int64(4), str(14)
memory usage: 862.2 KB

### 연습문제

같은 경로에서 12개의 데이터를 반복 실행하면서 하나의 df로 결합<br>
    - 전역변수는 2개 생성<br>
    - 반복 실행할 때마다 데이터들을 유니언 결합으로 행 결합<br>
    - hint: list에 반복 실행할 때마다 값을 추가하는 것과 같은 형식으로 구현

#### 내 풀이

In [12]:
list1 = []
df1 = pd.DataFrame(list1)

file_path = '../csv/2017'
file_list = os.listdir(file_path)

for file_name in file_list:
    if not(file_path.endswith('/')):
        file_path += '/'

    globals()['df2'] = pd.read_csv(file_path + file_name)
    df1 = pd.concat([df1, df2], axis=0, ignore_index=True)

In [13]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 70132 entries, 0 to 70131
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                70132 non-null  int64
 1   title              70132 non-null  str
 2   url                70132 non-null  str
 3   dept_nm_lvl_1      70132 non-null  str
 4   dept_nm_lvl_2      70074 non-null  str
 5   dept_nm_lvl_3      61262 non-null  str
 6   dept_nm_lvl_4      17939 non-null  str
 7   dept_nm_lvl_5      3474 non-null   str
 8   exec_yr            70132 non-null  int64
 9   exec_month         70132 non-null  int64
 10  expense_budget     3108 non-null   float64
 11  expense_execution  2805 non-null   float64
 12  category           1259 non-null   str
 13  dept_nm_full       70053 non-null  str
 14  exec_dt            70132 non-null  str
 15  exec_loc           69360 non-null  str
 16  exec_purpose       70110 non-null  str
 17  target_nm          69597 non-null  str
 18  payment_method     69929 non-null  str
 19  exec_amount        70132 non-null  int64
dtypes: float64(2), int64(4), str(14)
memory usage: 10.7 MB

In [14]:
df1.head(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,11430252,2017년 1월 장애인복지정책과 업무추진비 집행내역,http://opengov.seoul.go.kr/public/11430252,서울시본청,복지본부,장애인복지정책과,NaN,NaN,2017,1,NaN,NaN,NaN,복지본부 장애인복지정책과,2017-01-26 13:10,동해일식 (중구 무교동),기본소득과 장애인복지 논의간담회,장애인복지정책팀장 외 2명,카드,76000

In [15]:
df1.tail(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
70131,14292506,2017년 12월 사업소_은평병원_원무과 업무추진비 내역,http://opengov.seoul.go.kr/public/14292506,사업소,은평병원,원무과,NaN,NaN,2017,12,NaN,NaN,NaN,원무과,2017-12-06 18:00,스타벅스(응암동 96-1),전문의 및 전공의 격려 다과회,병원장 외 11명,카드,440000

#### 강사님 풀이

In [24]:
df = pd.DataFrame()

file_path = '../csv/2017'
file_list = os.listdir(file_path)

for file_name in file_list:
    file_path += '/'
    data = pd.read_csv(file_path + file_name)

    df = pd.concat([df, data], axis=0)

df.reset_index(drop=True, inplace=True)

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70132 entries, 0 to 70131
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                70132 non-null  int64
 1   title              70132 non-null  str
 2   url                70132 non-null  str
 3   dept_nm_lvl_1      70132 non-null  str
 4   dept_nm_lvl_2      70074 non-null  str
 5   dept_nm_lvl_3      61262 non-null  str
 6   dept_nm_lvl_4      17939 non-null  str
 7   dept_nm_lvl_5      3474 non-null   str
 8   exec_yr            70132 non-null  int64
 9   exec_month         70132 non-null  int64
 10  expense_budget     3108 non-null   float64
 11  expense_execution  2805 non-null   float64
 12  category           1259 non-null   str
 13  dept_nm_full       70053 non-null  str
 14  exec_dt            70132 non-null  str
 15  exec_loc           69360 non-null  str
 16  exec_purpose       70110 non-null  str
 17  target_nm          69597 non-null  str
 18  payment_method     69929 non-null  str
 19  exec_amount        70132 non-null  int64
dtypes: float64(2), int64(4), str(14)
memory usage: 10.7 MB

### 2019년 거 해보기: json

In [17]:
list1 = []
df2 = pd.DataFrame(list1)

file_path = '../csv/2019'
file_list = os.listdir(file_path)

for file_name in file_list:
    file_path += '/'
    data = pd.read_json(file_path + file_name)

    df2 = pd.concat([df2, data], axis=0)

df2.reset_index(drop=True, inplace=True)

In [19]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 74207 entries, 0 to 74206
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                74207 non-null  int64
 1   title              74207 non-null  str
 2   url                74207 non-null  str
 3   dept_nm_lvl_1      74207 non-null  str
 4   dept_nm_lvl_2      74207 non-null  str
 5   dept_nm_lvl_3      74207 non-null  str
 6   dept_nm_lvl_4      74207 non-null  str
 7   dept_nm_lvl_5      74207 non-null  str
 8   exec_yr            74207 non-null  int64
 9   exec_month         74207 non-null  int64
 10  expense_budget     2075 non-null   float64
 11  expense_execution  1598 non-null   float64
 12  category           74028 non-null  str
 13  dept_nm_full       74207 non-null  str
 14  exec_dt            74207 non-null  str
 15  exec_loc           74207 non-null  str
 16  exec_purpose       74207 non-null  str
 17  target_nm          74207 non-null  str
 18  payment_method     74207 non-null  str
 19  exec_amount        74207 non-null  int64
dtypes: float64(2), int64(4), str(14)
memory usage: 11.3 MB

### 파일 형식이 뒤죽박죽인 경우: glob()

In [ ]:
# os 말고 glob 라이브러리
# glob 라이브러리 안에 glob() 함수
# glob(경로 + 파일의 형식)

glob('../csv/2021/*.csv')

# os는 파일의 이름으로 리스트 생성
# glob() → 경로를 포함한 파일 리스트 생성

['../csv/2021\\202101_expense_list.csv',
 '../csv/2021\\202101_expense_list.json',
 '../csv/2021\\202101_expense_list.xlsx',
 '../csv/2021\\202101_expense_list.xml',
 '../csv/2021\\202102_expense_list.csv',
 '../csv/2021\\202102_expense_list.json',
 '../csv/2021\\202102_expense_list.xlsx',
 '../csv/2021\\202102_expense_list.xml',
 '../csv/2021\\202103_expense_list.csv',
 '../csv/2021\\202103_expense_list.json',
 '../csv/2021\\202103_expense_list.xlsx',
 '../csv/2021\\202103_expense_list.xml',
 '../csv/2021\\202104_expense_list.csv',
 '../csv/2021\\202104_expense_list.json',
 '../csv/2021\\202104_expense_list.xlsx',
 '../csv/2021\\202104_expense_list.xml',
 '../csv/2021\\202105_expense_list.csv',
 '../csv/2021\\202105_expense_list.json',
 '../csv/2021\\202105_expense_list.xlsx',
 '../csv/2021\\202105_expense_list.xml',
 '../csv/2021\\202106_expense_list.csv',
 '../csv/2021\\202106_expense_list.json',
 '../csv/2021\\202106_expense_list.xlsx',
 '../csv/2021\\202106_expense_list.xml',
 '../csv/2021\\202107_expense_list.csv',
 '../csv/2021\\202107_expense_list.json',
 '../csv/2021\\202107_expense_list.xlsx',
 '../csv/2021\\202107_expense_list.xml',
 '../csv/2021\\202108_expense_list.csv',
 '../csv/2021\\202108_expense_list.json',
 '../csv/2021\\202108_expense_list.xlsx',
 '../csv/2021\\202108_expense_list.xml',
 '../csv/2021\\202109_expense_list.csv',
 '../csv/2021\\202109_expense_list.json',
 '../csv/2021\\202109_expense_list.xlsx',
 '../csv/2021\\202109_expense_list.xml',
 '../csv/2021\\202110_expense_list.csv',
 '../csv/2021\\202110_expense_list.json',
 '../csv/2021\\202110_expense_list.xlsx',
 '../csv/2021\\202110_expense_list.xml',
 '../csv/2021\\202111_expense_list.csv',
 '../csv/2021\\202111_expense_list.json',
 '../csv/2021\\202111_expense_list.xlsx',
 '../csv/2021\\202111_expense_list.xml',
 '../csv/2021\\202112_expense_list.csv',
 '../csv/2021\\202112_expense_list.json',
 '../csv/2021\\202112_expense_list.xlsx',
 '../csv/2021\\202112_expense_list.xml']

### <font color=red>특정 경로의 파일들을 일괄적으로 로드하는 함수를 생성</font>

1. 매개변수 (함수를 호출할 때마다 변할 수 있는 데이터)
    - 경로 : file_path (필수 입력 항목)
    - 확장자 : file_ext (기본값 = csv)
    - 데이터 결합 여부 : output_type (데이터를 결합할 것인가)
        (기본값 = 'concat' || 'global')
    - 인코딩 엔진 (데이터가 한글이 들어간 경우 대비) : engine
        (기본값='utf-8' | 'cp949' | 'euc-kr')

2. 파일의 목록을 로드
3. 데이터 결합 여부에 따라 concat이라면 빈 df 생성
    - global이라면 파일의 전역변수에서 사용할 넘버의 초기값 설정
        (file_idx = 1)

4. 반복문을 설정하여 데이터를 로드
    - concat이면 데이터 결합
    - global이면 각각 데이터 변수에 대입

5. 결과를 되돌려준다.

----------------

- 함수를 만들었다면 모듈화
    - py 파일을 생성하여 함수를 넣고 저장

In [42]:
def data_load(file_path,
              file_ext = 'csv',
              output_type = 'concat',
              engine = 'utf-8'):
    # 파일 path에 '/' 추가
    file_path += '/'
    file_list = os.listdir(file_path)

    # 파일 목록이 file_ext와 다른 확장자가 포함되어있을 수 있다.
        # ext에 따라서 filter: 마지막이 file_ext와 같다면 리스트에 유지, 아니면 제거
    
    file_list = [x for x in file_list if x.endswith(file_ext)]
    # 다른 방법
    # file_list2 = []
    # for x in file_list:
        # if x.endswith(file_ext):
            # file_list2.append(x)

    # output_type이 concat이라면 빈 데이터 프레임을 생성
    if output_type == 'concat':
        result = pd.DataFrame()
    elif output_type == 'global':
        # 전역변수에서 사용할 넘버 생성
        vari_cnt = 1
    else:
        raise ValueError('output_type에는 concat, global만 선택이 가능합니다.')

    # 파일을 로드
    for file_name in file_list:
        if file_ext == 'csv':
            df = pd.read_csv(file_path + file_name, encoding=engine)
        elif file_ext == 'json':
            df = pd.read_json(file_path + file_name, encoding=engine)
        elif file_ext == 'xml':
            df = pd.read_xml(file_path + file_name, encoding=engine)
        elif file_ext in ['xlsx', 'xls']:
            df = pd.read_excel(file_path + file_name)
            # read_excel() 함수는 encoding 매개변수가 존재하지 않는다.
        else:
            raise ValueError('file_ext에는 csv, json, xml, excel 확장자만 선택이 가능합니다.')
    
        # output_type에 따라 결합, 전역변수 저장
        if output_type == 'concat':
            result = pd.concat([result, df])
        else:
            globals()[f'df_{vari_cnt}'] = df.copy()
            print(f'df_{vari_cnt} 전역 변수가 생성')
            vari_cnt += 1

    # 결과를 되돌려준다
    try:
        return result
    except:
        print('전역 변수 생성 완료')

In [45]:
# 함수 테스트

test_df = data_load(
    "../csv/2021",
    output_type= 'global'
)

df_1 전역 변수가 생성
df_2 전역 변수가 생성
df_3 전역 변수가 생성
df_4 전역 변수가 생성
df_5 전역 변수가 생성
df_6 전역 변수가 생성
df_7 전역 변수가 생성
df_8 전역 변수가 생성
df_9 전역 변수가 생성
df_10 전역 변수가 생성
df_11 전역 변수가 생성
df_12 전역 변수가 생성
전역 변수 생성 완료

In [47]:
# glob 라이브러리를 이용해서 파일 목록 받고 파일 이름에 접근하는 방법

file_path = '../csv/2021/'
file_ext = 'csv'

file_list = glob(f'{file_path}*.{file_ext}')
file_list

['../csv/2021\\202101_expense_list.csv',
 '../csv/2021\\202102_expense_list.csv',
 '../csv/2021\\202103_expense_list.csv',
 '../csv/2021\\202104_expense_list.csv',
 '../csv/2021\\202105_expense_list.csv',
 '../csv/2021\\202106_expense_list.csv',
 '../csv/2021\\202107_expense_list.csv',
 '../csv/2021\\202108_expense_list.csv',
 '../csv/2021\\202109_expense_list.csv',
 '../csv/2021\\202110_expense_list.csv',
 '../csv/2021\\202111_expense_list.csv',
 '../csv/2021\\202112_expense_list.csv']

In [55]:
for file_name in file_list:
    # os 라이브러리에 경로와 파일 이름을 나눠주는 함수
    print(file_name)
    f_path, f_name = os.path.split(file_name)
    print(f_path)
    print(f_name)
    # break

    name, ext = os.path.splitext(f_name)
    print(name)
    print(ext)
    break

../csv/2021\202101_expense_list.csv
../csv/2021
202101_expense_list.csv
202101_expense_list
.csv

### 모듈
1. py 파일로 구성
2. 폴더 안에 py 파일로도 구성

- import 모듈명
    - py 파일을 찾는다
    - 해당 이름의 폴더 안에 `__init__.py`를 찾는다

- import를 통해서 load가 된 모듈은 다시 import를 해도 수정된 내역은 load되지 않는다.
    - 구버전인 상태 그대로 유지
    - ipynb 파일의 경우 vscode에서 파일을 닫고 다시 import하는 방법 (kernal 재시작)
    - 모듈을 reload하는 라이브러리를 이용하여 다시 불러오기 (importlib 안에 reload() 함수가 존재)