In [1]:
import pandas as pd

In [2]:
sales = pd.read_csv('../csv/Sales Records.csv')

In [3]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          10000 non-null  str
 1   Country         10000 non-null  str
 2   Item Type       10000 non-null  str
 3   Sales Channel   10000 non-null  str
 4   Order Priority  10000 non-null  str
 5   Order Date      10000 non-null  str
 6   Order ID        10000 non-null  int64
 7   Ship Date       10000 non-null  str
 8   Units Sold      10000 non-null  int64
 9   Unit Price      10000 non-null  float64
 10  Unit Cost       10000 non-null  float64
 11  Total Revenue   10000 non-null  float64
 12  Total Cost      10000 non-null  float64
 13  Total Profit    10000 non-null  float64
dtypes: float64(5), int64(2), str(7)
memory usage: 1.1 MB

In [4]:
sales.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+04,10000.000000,10000.000000,10000.000000,1.000000e+04,1.000000e+04,1.000000e+04
mean,5.498719e+08,5002.855900,268.143139,188.806639,1.333355e+06,9.382658e+05,3.950893e+05
std,2.607835e+08,2873.246454,217.944092,176.445907,1.465026e+06,1.145914e+06,3.775550e+05
min,1.000892e+08,2.000000,9.330000,6.920000,1.679400e+02,1.245600e+02,4.338000e+01
25%,3.218067e+08,2530.750000,109.280000,56.670000,2.885511e+05,1.647855e+05,9.832914e+04
50%,5.485663e+08,4962.000000,205.700000,117.110000,8.000512e+05,4.816058e+05,2.890990e+05
75%,7.759981e+08,7472.000000,437.200000,364.690000,1.819143e+06,1.183822e+06,5.664227e+05
max,9.999342e+08,10000.000000,668.270000,524.960000,6.680027e+06,5.241726e+06,1.738178e+06

In [5]:
sales.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,1/27/2011,292494523,2/12/2011,4484,651.21,524.96,2920025.64,2353920.64,566105.00
1,Europe,Latvia,Beverages,Online,C,12/28/2015,361825549,1/23/2016,1075,47.45,31.79,51008.75,34174.25,16834.50
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,1/13/2011,141515767,2/1/2011,6515,154.06,90.93,1003700.90,592408.95,411291.95
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,9/11/2012,500364005,10/6/2012,7683,668.27,502.54,5134318.41,3861014.82,1273303.59
4,Europe,Czech Republic,Beverages,Online,C,10/27/2015,127481591,12/5/2015,3491,47.45,31.79,165647.95,110978.89,54669.06

#### 연습

1. 원본 데이터 복사본 생성 (복사본 이름 df)
2. 'Order ID', 'Total Revenue', 'Total Cost', 'Total Profit', 'Order Priority' column 제거
3. column의 이름을 변경: 대륙, 국가, 상품종류, 판매채널, 주문일자, 발송일자, 판매개수, 단가, 원가
4. 대륙, 국가를 기준으로 오름차순 정렬
5. 인덱스를 초기화하고 기존의 인덱스는 제거
6. 파생변수 생성
    - 총단가 = 단가 * 판매개수
    - 총원가 = 원가 * 판매개수
    - 총이윤 = 총단가 - 총원가

In [6]:
# 1

df = sales.copy()

In [9]:
# 2

df.drop(columns=['Order ID', 'Total Revenue', 'Total Cost', 'Total Profit', 'Order Priority'], inplace = True)

In [11]:
# 3

df.columns = ['대륙', '국가', '상품종류', '판매채널', '주문일자', '발송일자', '판매개수', '단가', '원가']
df.head()

,대륙,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가
0,Sub-Saharan Africa,Chad,Office Supplies,Online,1/27/2011,2/12/2011,4484,651.21,524.96
1,Europe,Latvia,Beverages,Online,12/28/2015,1/23/2016,1075,47.45,31.79
2,Middle East and North Africa,Pakistan,Vegetables,Offline,1/13/2011,2/1/2011,6515,154.06,90.93
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,9/11/2012,10/6/2012,7683,668.27,502.54
4,Europe,Czech Republic,Beverages,Online,10/27/2015,12/5/2015,3491,47.45,31.79

In [16]:
# 4

df.sort_values(['대륙', '국가'], ascending = True, inplace = True)

In [18]:
# 5

df.reset_index(drop=True, inplace=True)

In [ ]:
# 6

df['총단가'] = df['단가'] * df['판매개수']
df['총원가'] = df['원가'] * df['판매개수']
df['총이윤'] = df['총단가'] - df['총원가']

In [21]:
df.head()

,대륙,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가,총단가,총원가,총이윤
0,Asia,Bangladesh,Personal Care,Online,12/11/2016,1/13/2017,9420,81.73,56.67,769896.60,533831.40,236065.20
1,Asia,Bangladesh,Cosmetics,Offline,7/29/2010,9/11/2010,577,437.20,263.33,252264.40,151941.41,100322.99
2,Asia,Bangladesh,Vegetables,Offline,4/28/2014,5/5/2014,34,154.06,90.93,5238.04,3091.62,2146.42
3,Asia,Bangladesh,Cereal,Offline,6/22/2010,6/28/2010,9768,205.70,117.11,2009277.60,1143930.48,865347.12
4,Asia,Bangladesh,Office Supplies,Online,3/20/2013,4/11/2013,7731,651.21,524.96,5034504.51,4058465.76,976038.75

#### 추가

In [ ]:
# 어떤 대륙이 총이윤의 합계가 가장 클까?
# 대륙별 고유값 리스트를 생성 → unique() // value_counts()
# 대륙 column을 기준으로 비교연산자를 사용해서 filtering
    # → 총 이윤의 합산 (반복실행)

# groupby 안 쓰나요 강사님...?🥹 근데 나중에 쓰실 것 같긴 해요...

In [29]:
# 내가 생각나는대로 한 것

df['총이윤'].groupby(df['대륙']).sum()

대륙
Asia                                 5.874033e+08
Australia and Oceania                3.240712e+08
Central America and the Caribbean    4.033578e+08
Europe                               1.027000e+09
Middle East and North Africa         5.099239e+08
North America                        9.949552e+07
Sub-Saharan Africa                   9.996421e+08
Name: 총이윤, dtype: float64

In [50]:
# 그럼 평균에서 이건 어때요

df['총이윤'].groupby(df['대륙']).mean()

대륙
Asia                                 399866.097243
Australia and Oceania                406613.816073
Central America and the Caribbean    395836.947713
Europe                               390049.226282
Middle East and North Africa         403420.802634
North America                        462769.837767
Sub-Saharan Africa                   384034.610642
Name: 총이윤, dtype: float64

In [23]:
df['대륙'].unique()

<StringArray>
[                             'Asia',             'Australia and Oceania',
 'Central America and the Caribbean',                            'Europe',
      'Middle East and North Africa',                     'North America',
                'Sub-Saharan Africa']
Length: 7, dtype: str

In [32]:
df['대륙'].value_counts()
# 반환값 Series

대륙
Europe                               2633
Sub-Saharan Africa                   2603
Asia                                 1469
Middle East and North Africa         1264
Central America and the Caribbean    1019
Australia and Oceania                 797
North America                         215
Name: count, dtype: int64

In [34]:
list_1 = df['대륙'].unique()
# list_1 = df['대륙'].value_counts().index

In [38]:
data_list = []

for data in list_1:
    flag = df['대륙'] == data
    result = df.loc[flag, '총이윤'].sum()
    # print(result)
    dict_data = {'대륙': data, '합산': result}
    data_list.append(dict_data)

data_list

[{'대륙': 'Asia', '합산': np.float64(587403296.8499999)},
 {'대륙': 'Australia and Oceania', '합산': np.float64(324071211.41)},
 {'대륙': 'Central America and the Caribbean', '합산': np.float64(403357849.72)},
 {'대륙': 'Europe', '합산': np.float64(1026999612.8)},
 {'대륙': 'Middle East and North Africa', '합산': np.float64(509923894.53)},
 {'대륙': 'North America', '합산': np.float64(99495515.12)},
 {'대륙': 'Sub-Saharan Africa', '합산': np.float64(999642091.5)}]

In [39]:
pd.DataFrame(data_list)

                                  대륙            합산
0                               Asia  5.874033e+08
1              Australia and Oceania  3.240712e+08
2  Central America and the Caribbean  4.033578e+08
3                             Europe  1.027000e+09
4       Middle East and North Africa  5.099239e+08
5                      North America  9.949552e+07
6                 Sub-Saharan Africa  9.996421e+08

In [ ]:
# 데이터의 그룹화 → 같은 데이터들을 결합하여 연산한 뒤 새로운 데이터로 구성
# 그룹화 함수 → groupby(그룹화를 할 column의 이름(2개 이상이라면 []로 입력))

group_data = df.groupby('대륙')
group_data

# pandas.api.typing.DataFrameGroupBy object: 해당하는 data의 type
# 0x000001952F49BCB0: data의 주소

In [46]:
# 그룹화 데이터에서 특정 그룹만 추출 → 그룹을 가져오다

group_data.get_group('Asia')

,대륙,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가,총단가,총원가,총이윤
0,Asia,Bangladesh,Personal Care,Online,12/11/2016,1/13/2017,9420,81.73,56.67,769896.60,533831.40,236065.20
1,Asia,Bangladesh,Cosmetics,Offline,7/29/2010,9/11/2010,577,437.20,263.33,252264.40,151941.41,100322.99
2,Asia,Bangladesh,Vegetables,Offline,4/28/2014,5/5/2014,34,154.06,90.93,5238.04,3091.62,2146.42
3,Asia,Bangladesh,Cereal,Offline,6/22/2010,6/28/2010,9768,205.70,117.11,2009277.60,1143930.48,865347.12
4,Asia,Bangladesh,Office Supplies,Online,3/20/2013,4/11/2013,7731,651.21,524.96,5034504.51,4058465.76,976038.75
...,...,...,...,...,...,...,...,...,...,...,...,...
1464,Asia,Vietnam,Cosmetics,Offline,1/23/2016,2/11/2016,5639,437.20,263.33,2465370.80,1484917.87,980452.93
1465,Asia,Vietnam,Office Supplies,Online,11/19/2016,12/21/2016,3669,651.21,524.96,2389289.49,1926078.24,463211.25
1466,Asia,Vietnam,Meat,Online,9/5/2012,9/10/2012,5776,421.89,364.69,2436836.64,2106449.44,330387.20
1467,Asia,Vietnam,Personal Care,Online,2/6/2010,3/23/2010,1590,81.73,56.67,129950.70,90105.30,39845.40
1468,Asia,Vietnam,Baby Food,Online,2/25/2010,4/1/2010,9105,255.28,159.42,2324324.40,1451519.10,872805.30

In [47]:
group_data.sum()

,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가,총단가,총원가,총이윤
대륙,,,,,,,,,,,
Asia,BangladeshBangladeshBangladeshBangladeshBangla...,Personal CareCosmeticsVegetablesCerealOffice S...,OnlineOfflineOfflineOfflineOnlineOnlineOnlineO...,12/11/20167/29/20104/28/20146/22/20103/20/2013...,1/13/20179/11/20105/5/20146/28/20104/11/201311...,7367752,394260.70,277566.90,2.005306e+09,1.417902e+09,5.874033e+08
Australia and Oceania,AustraliaAustraliaAustraliaAustraliaAustraliaA...,Personal CareMeatFruitsFruitsBaby FoodCerealMe...,OnlineOnlineOnlineOfflineOnlineOnlineOnlineOnl...,3/16/20148/17/20134/13/20161/18/20164/22/20159...,4/27/20149/17/20135/5/20163/4/20165/30/201510/...,3974455,213124.94,148211.40,1.049802e+09,7.257310e+08,3.240712e+08
Central America and the Caribbean,Antigua and Barbuda Antigua and Barbuda Antigu...,Baby FoodVegetablesSnacksVegetablesSnacksCosme...,OnlineOfflineOnlineOfflineOfflineOnlineOnlineO...,11/13/201410/28/20129/5/20148/19/20163/14/2013...,12/20/201411/9/20129/19/20148/22/20164/22/2013...,5177603,279197.12,198051.67,1.395530e+09,9.921719e+08,4.033578e+08
Europe,AlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlbaniaAlba...,Baby FoodBaby FoodBeveragesVegetablesBeverages...,OfflineOnlineOnlineOnlineOfflineOnlineOfflineO...,5/20/201110/4/20121/13/20139/20/20107/31/20154...,6/19/201111/21/20122/4/201311/4/20108/5/20156/...,12955373,710315.09,500281.95,3.481372e+09,2.454372e+09,1.027000e+09
Middle East and North Africa,AfghanistanAfghanistanAfghanistanAfghanistanAf...,VegetablesCosmeticsVegetablesHouseholdFruitsCo...,OnlineOnlineOfflineOfflineOnlineOfflineOnlineO...,8/28/20154/7/201512/9/20133/25/20117/1/201110/...,8/29/20155/7/20151/27/20144/1/20118/20/201111/...,6466901,344338.90,243210.08,1.715633e+09,1.205710e+09,5.099239e+08
North America,CanadaCanadaCanadaCanadaCanadaCanadaCanadaCana...,Office SuppliesBaby FoodCerealHouseholdBeverag...,OfflineOnlineOnlineOnlineOfflineOnlineOfflineO...,10/24/201110/1/201411/27/20147/14/20151/31/201...,11/20/201110/20/20141/3/20157/29/20152/18/2011...,1155272,60021.05,42343.74,3.353524e+08,2.358569e+08,9.949552e+07
Sub-Saharan Africa,AngolaAngolaAngolaAngolaAngolaAngolaAngolaAngo...,FruitsClothesCosmeticsVegetablesVegetablesSnac...,OfflineOfflineOnlineOnlineOfflineOfflineOnline...,4/28/20147/15/201210/24/20101/23/20127/22/2016...,5/23/20148/15/201211/10/20103/9/20127/30/20165...,12931203,680173.59,478400.65,3.350556e+09,2.350914e+09,9.996421e+08

In [48]:
group_data.sum()['총이윤']

대륙
Asia                                 5.874033e+08
Australia and Oceania                3.240712e+08
Central America and the Caribbean    4.033578e+08
Europe                               1.027000e+09
Middle East and North Africa         5.099239e+08
North America                        9.949552e+07
Sub-Saharan Africa                   9.996421e+08
Name: 총이윤, dtype: float64

In [ ]:
group_data.mean()['총이윤']

# dtype이 숫자형이 아니라면 평균에서 에러 발생
# 그룹화를 할때 문자열 column은 제외하고 그룹화 → 그룹화 연산

In [58]:
# column을 filter → 그룹화 → 그룹화 연산
# 대륙별 총 이윤의 합계와 평균을 구해보자
# column의 filter

df[['총이윤', '대륙']].groupby('대륙').mean()

                                             총이윤
대륙
Asia                               399866.097243
Australia and Oceania              406613.816073
Central America and the Caribbean  395836.947713
Europe                             390049.226282
Middle East and North Africa       403420.802634
North America                      462769.837767
Sub-Saharan Africa                 384034.610642

In [55]:
df[['총이윤']]

            총이윤
0     236065.20
1     100322.99
2       2146.42
3     865347.12
4     976038.75
...         ...
9995  619172.64
9996  891881.44
9997  237578.40
9998   14228.64
9999  647504.31

[10000 rows x 1 columns]

In [ ]:
df[['총이윤']].groupby(df['대륙']).mean()

# groupby() 함수의 특징
# groupby(Series) → index를 기준으로 데이터를 그룹화
# 가독성이 떨어져서 일반적으로 사용하지는 않음
# DF를 결합하지 않고 그룹연산을 하는 특수한 경우에 사용

                                             총이윤
대륙
Asia                               399866.097243
Australia and Oceania              406613.816073
Central America and the Caribbean  395836.947713
Europe                             390049.226282
Middle East and North Africa       403420.802634
North America                      462769.837767
Sub-Saharan Africa                 384034.610642

In [ ]:
# df[['총이윤', '대륙']].groupby('대륙').sum().mean()은 총합의 평균이 도출

# 두 개의 연산을 동시에 보고 싶다면

df[['총이윤', '대륙']].groupby('대륙').agg(['mean', 'sum'])

                                             총이윤
                                            mean           sum
대륙
Asia                               399866.097243  5.874033e+08
Australia and Oceania              406613.816073  3.240712e+08
Central America and the Caribbean  395836.947713  4.033578e+08
Europe                             390049.226282  1.027000e+09
Middle East and North Africa       403420.802634  5.099239e+08
North America                      462769.837767  9.949552e+07
Sub-Saharan Africa                 384034.610642  9.996421e+08

In [62]:
group_data2 = df[['총이윤', '대륙']].groupby('대륙').agg(['mean', 'sum'])

group_data2['총이윤']

                                            mean           sum
대륙
Asia                               399866.097243  5.874033e+08
Australia and Oceania              406613.816073  3.240712e+08
Central America and the Caribbean  395836.947713  4.033578e+08
Europe                             390049.226282  1.027000e+09
Middle East and North Africa       403420.802634  5.099239e+08
North America                      462769.837767  9.949552e+07
Sub-Saharan Africa                 384034.610642  9.996421e+08

In [63]:
group_data2['총이윤']['mean']

대륙
Asia                                 399866.097243
Australia and Oceania                406613.816073
Central America and the Caribbean    395836.947713
Europe                               390049.226282
Middle East and North Africa         403420.802634
North America                        462769.837767
Sub-Saharan Africa                   384034.610642
Name: mean, dtype: float64

In [ ]:
group_data2['총이윤']['mean']['Asia']

# 3차원 데이터에서 단일 데이터까지 필터링하려면 괄호가 3번

np.float64(399866.09724302246)

In [66]:
test_data = {
    '총이윤' : {
        'mean' : {
            'Asia' : 100
        },
        'sum' : {
            'Asia' : 1000
        }
    }
}

print(f'test_data["총이윤"]:                {test_data['총이윤']}')
print(f'test_data["총이윤"]["mean"]:         {test_data['총이윤']['mean']}')
print(f'test_data["총이윤"]["mean"]["Asia"]: {test_data['총이윤']['mean']['Asia']}')

test_data["총이윤"]:                {'mean': {'Asia': 100}, 'sum': {'Asia': 1000}}
test_data["총이윤"]["mean"]:         {'Asia': 100}
test_data["총이윤"]["mean"]["Asia"]: 100

In [68]:
# group_data2의 인덱스와 column을 확인

print(group_data2.index)
print()
print(group_data2.columns)

Index(['Asia', 'Australia and Oceania', 'Central America and the Caribbean',
       'Europe', 'Middle East and North Africa', 'North America',
       'Sub-Saharan Africa'],
      dtype='str', name='대륙')

MultiIndex([('총이윤', 'mean'),
            ('총이윤',  'sum')],
           )

In [70]:
group_data2[ ('총이윤', 'mean') ]

대륙
Asia                                 399866.097243
Australia and Oceania                406613.816073
Central America and the Caribbean    395836.947713
Europe                               390049.226282
Middle East and North Africa         403420.802634
North America                        462769.837767
Sub-Saharan Africa                   384034.610642
Name: (총이윤, mean), dtype: float64

In [ ]:
# 멀티 인덱스를 생성
# 그룹의 (!!!!!!!!!!!!!!!!!!!!여기 깃헙보기!!!!!!!!!!!!!!!!!!!!)

group_data3 = df[ ['대륙', '판매채널', '총이윤'] ].groupby(
    ['대륙', '판매채널']).sum()

group_data3

                                                    총이윤
대륙                                판매채널
Asia                              Offline  2.734457e+08
                                  Online   3.139576e+08
Australia and Oceania             Offline  1.527809e+08
                                  Online   1.712903e+08
Central America and the Caribbean Offline  2.102715e+08
                                  Online   1.930864e+08
Europe                            Offline  5.337624e+08
                                  Online   4.932372e+08
Middle East and North Africa      Offline  2.549156e+08
                                  Online   2.550083e+08
North America                     Offline  5.338042e+07
                                  Online   4.611510e+07
Sub-Saharan Africa                Offline  5.023457e+08
                                  Online   4.972964e+08

In [83]:
group_data3['총이윤']['Europe']['Offline']

np.float64(533762385.78999996)

In [85]:
group_data3.loc[
    ('Europe', 'Offline'), '총이윤'
]

np.float64(533762385.78999996)

In [ ]:
# 판매채널 기준으로 index 수를 셈
    # 7번째였으므로 index에서는 6

group_data3.iloc[6, 0]

np.float64(533762385.78999996)

In [87]:
group_data3.reset_index()

                                   대륙     판매채널           총이윤
0                                Asia  Offline  2.734457e+08
1                                Asia   Online  3.139576e+08
2               Australia and Oceania  Offline  1.527809e+08
3               Australia and Oceania   Online  1.712903e+08
4   Central America and the Caribbean  Offline  2.102715e+08
5   Central America and the Caribbean   Online  1.930864e+08
6                              Europe  Offline  5.337624e+08
7                              Europe   Online  4.932372e+08
8        Middle East and North Africa  Offline  2.549156e+08
9        Middle East and North Africa   Online  2.550083e+08
10                      North America  Offline  5.338042e+07
11                      North America   Online  4.611510e+07
12                 Sub-Saharan Africa  Offline  5.023457e+08
13                 Sub-Saharan Africa   Online  4.972964e+08

In [ ]:
# 인덱스를 column으로 바꾸고 싶다

group_data3.unstack()   # default= -1 (마지막 인덱스를 column으로 올린다)

                                            총이윤
판매채널                                    Offline        Online
대륙
Asia                               2.734457e+08  3.139576e+08
Australia and Oceania              1.527809e+08  1.712903e+08
Central America and the Caribbean  2.102715e+08  1.930864e+08
Europe                             5.337624e+08  4.932372e+08
Middle East and North Africa       2.549156e+08  2.550083e+08
North America                      5.338042e+07  4.611510e+07
Sub-Saharan Africa                 5.023457e+08  4.972964e+08

In [91]:
group_data3.unstack(0)  # 첫번째 인덱스를 column으로 올린다

                  총이윤                                                          \
대륙               Asia Australia and Oceania Central America and the Caribbean
판매채널
Offline  2.734457e+08          1.527809e+08                      2.102715e+08
Online   3.139576e+08          1.712903e+08                      1.930864e+08

                                                                  \
대륙             Europe Middle East and North Africa North America
판매채널
Offline  5.337624e+08                 2.549156e+08   53380419.58
Online   4.932372e+08                 2.550083e+08   46115095.54


대륙      Sub-Saharan Africa
판매채널
Offline       5.023457e+08
Online        4.972964e+08

In [ ]:
# 그렇다면 초기화할 index를 선택할 수 있는가?

group_data3.reset_index(1)  # default는 모든 공간(기본값은... 아직 모름)

                                      판매채널           총이윤
대륙
Asia                               Offline  2.734457e+08
Asia                                Online  3.139576e+08
Australia and Oceania              Offline  1.527809e+08
Australia and Oceania               Online  1.712903e+08
Central America and the Caribbean  Offline  2.102715e+08
Central America and the Caribbean   Online  1.930864e+08
Europe                             Offline  5.337624e+08
Europe                              Online  4.932372e+08
Middle East and North Africa       Offline  2.549156e+08
Middle East and North Africa        Online  2.550083e+08
North America                      Offline  5.338042e+07
North America                       Online  4.611510e+07
Sub-Saharan Africa                 Offline  5.023457e+08
Sub-Saharan Africa                  Online  4.972964e+08

In [ ]:
# column의 기준을 index로 올림

group_data3.stack()

대륙                                 판매채널
Asia                               Offline  총이윤    2.734457e+08
                                   Online   총이윤    3.139576e+08
Australia and Oceania              Offline  총이윤    1.527809e+08
                                   Online   총이윤    1.712903e+08
Central America and the Caribbean  Offline  총이윤    2.102715e+08
                                   Online   총이윤    1.930864e+08
Europe                             Offline  총이윤    5.337624e+08
                                   Online   총이윤    4.932372e+08
Middle East and North Africa       Offline  총이윤    2.549156e+08
                                   Online   총이윤    2.550083e+08
North America                      Offline  총이윤    5.338042e+07
                                   Online   총이윤    4.611510e+07
Sub-Saharan Africa                 Offline  총이윤    5.023457e+08
                                   Online   총이윤    4.972964e+08
dtype: float64

In [ ]:
# stack(), unstack()
# stack(): column을 index로 이동
# unstack(): index를 column으로 이동
# 이동을 시키고 column이나 index가 존재하지 않는 경우
    # single column을 index로 이동
        # dtype이 Series로 변경

# multi index로 이루어진 Series에서 unstack()을 사용하면 dtype이 DF로 변경

group_data4 = df.groupby(['대륙', '판매채널'])['총이윤'].sum()

# df.groupby(['대륙', '판매채널']) : DataFrame Groupby
# ['총이윤'] : DF → Series
# df.groupby(['대륙', '판매채널'])['총이윤']: Series Groupby

In [103]:
group_data4

대륙                                 판매채널
Asia                               Offline    2.734457e+08
                                   Online     3.139576e+08
Australia and Oceania              Offline    1.527809e+08
                                   Online     1.712903e+08
Central America and the Caribbean  Offline    2.102715e+08
                                   Online     1.930864e+08
Europe                             Offline    5.337624e+08
                                   Online     4.932372e+08
Middle East and North Africa       Offline    2.549156e+08
                                   Online     2.550083e+08
North America                      Offline    5.338042e+07
                                   Online     4.611510e+07
Sub-Saharan Africa                 Offline    5.023457e+08
                                   Online     4.972964e+08
Name: 총이윤, dtype: float64

In [ ]:
print(type(group_data4))
group_data4.unstack()

# Series data에서 stack() 사용하면?
    # error: Series에서는 unstack()만 가지고 있음

<class 'pandas.Series'>

판매채널                                    Offline        Online
대륙
Asia                               2.734457e+08  3.139576e+08
Australia and Oceania              1.527809e+08  1.712903e+08
Central America and the Caribbean  2.102715e+08  1.930864e+08
Europe                             5.337624e+08  4.932372e+08
Middle East and North Africa       2.549156e+08  2.550083e+08
North America                      5.338042e+07  4.611510e+07
Sub-Saharan Africa                 5.023457e+08  4.972964e+08

In [107]:
# pivot → table의 data들을 재구조화 한다.
# pandas에서 pivot_table()
# pandas 안에 존재, DF 안에서도 존재
# 모듈 안에 있는 pivot_table()
# DataFrame class 안에 있는 pivot_table()
# 매개변수 index: 어떤 값을 기준으로 테이블 데이터를 배치할 것인가?
    # 인덱스로 사용할 !!!!!!!!!!!!!깃헙보기!!!!!!!!!!!!
# 매개변수 columns: 어떤 값을 기준으로 테이블 데이터를 배치할 것인가?
    # 컬럼으로 사용할
# 매개변수 values: index, columns를 기준으로 데이터를 결합하여 사용할 value는 무엇인가?
# 매개변수 aggfunc: values에 어떤 연산을 할 것인가?

In [108]:
# DF class 안에 존재하는 pivot_table() 함수를 사용

df.pivot_table(
    index = '대륙',        # 대륙을 기준으로 그룹화
    values = '총이윤',      # 값으로 쓰고 싶은 부분
    aggfunc = 'sum'
)

                                            총이윤
대륙
Asia                               5.874033e+08
Australia and Oceania              3.240712e+08
Central America and the Caribbean  4.033578e+08
Europe                             1.027000e+09
Middle East and North Africa       5.099239e+08
North America                      9.949552e+07
Sub-Saharan Africa                 9.996421e+08

In [111]:
df.pivot_table(
    index = '대륙',
    columns = '판매채널',
    values = '총이윤',
    aggfunc = ['sum', 'mean']       # 함수를 여러개 잡은 것처럼 i/c/v 모두 여러개 잡을 수 있음
)

                                            sum                         mean  \
판매채널                                    Offline        Online        Offline
대륙
Asia                               2.734457e+08  3.139576e+08  386222.681285
Australia and Oceania              1.527809e+08  1.712903e+08  409600.378954
Central America and the Caribbean  2.102715e+08  1.930864e+08  406714.673849
Europe                             5.337624e+08  4.932372e+08  404979.048399
Middle East and North Africa       2.549156e+08  2.550083e+08  407864.945456
North America                      5.338042e+07  4.611510e+07  489728.620000
Sub-Saharan Africa                 5.023457e+08  4.972964e+08  389717.367285


판매채널                                      Online
대륙
Asia                               412559.314717
Australia and Oceania              403986.485991
Central America and the Caribbean  384634.189920
Europe                             375085.343734
Middle East and North Africa       399074.027574
North America                      435048.071132
Sub-Saharan Africa                 378459.973417

In [112]:
# 라이브러리(pandas) 안에 pivot_table() 함수 호출
# 모듈 안에서 함수 호출 시 변경할 데이터를 인자로 입력

pd.pivot_table(
    df,
    index = '대륙',
    columns = '판매채널',
    values = '총이윤',
    aggfunc= 'sum'
)

판매채널                                    Offline        Online
대륙
Asia                               2.734457e+08  3.139576e+08
Australia and Oceania              1.527809e+08  1.712903e+08
Central America and the Caribbean  2.102715e+08  1.930864e+08
Europe                             5.337624e+08  4.932372e+08
Middle East and North Africa       2.549156e+08  2.550083e+08
North America                      5.338042e+07  4.611510e+07
Sub-Saharan Africa                 5.023457e+08  4.972964e+08

#### 연습
1. 각 대륙별 총이윤이 가장 많은 아이템은 무엇인가?
    - 대륙, 상품종류별 그룹화
    - 그룹화 연산으로는 총이윤의 합계
    - 각 대륙별로 총이윤이 가장 높은 상품종류를 출력하시오

In [144]:
# 1

df[['대륙', '상품종류', '총이윤']].groupby(['대륙', '상품종류']).sum().sort_values(['대륙', '총이윤'], ascending=False)

# 대륙별로 하나만 보고 싶은데 그게 안 된다...

                                             총이윤
대륙                 상품종류
Sub-Saharan Africa Cosmetics        1.766093e+08
                   Household        1.764783e+08
                   Office Supplies  1.269636e+08
                   Baby Food        1.129722e+08
                   Cereal           9.426100e+07
...                                          ...
Asia               Snacks           3.443074e+07
                   Meat             3.255046e+07
                   Personal Care    1.703025e+07
                   Beverages        8.647186e+06
                   Fruits           1.252062e+06

[84 rows x 1 columns]

In [145]:
# 강사님 풀이

# 그룹화 → 그룹화 연산 → 총이윤을 기준으로 내림차순
    # 나도 여기까지는 했다,,,
# 인덱스를 리셋 → 반복문을 이용해서 각 대륙 첫번째 인덱스를 추출 → DF에 필터

In [ ]:
# 힌트 받아서 다시
# 모르겠다... 난 바보야

df2 = df[['대륙', '상품종류', '총이윤']].groupby(['대륙', '상품종류']).sum().sort_values(['대륙', '총이윤'], ascending=False).reset_index()
df2

                    대륙             상품종류           총이윤
0   Sub-Saharan Africa        Cosmetics  1.766093e+08
1   Sub-Saharan Africa        Household  1.764783e+08
2   Sub-Saharan Africa  Office Supplies  1.269636e+08
3   Sub-Saharan Africa        Baby Food  1.129722e+08
4   Sub-Saharan Africa           Cereal  9.426100e+07
..                 ...              ...           ...
79                Asia           Snacks  3.443074e+07
80                Asia             Meat  3.255046e+07
81                Asia    Personal Care  1.703025e+07
82                Asia        Beverages  8.647186e+06
83                Asia           Fruits  1.252062e+06

[84 rows x 3 columns]

#### 강사님 풀이

In [224]:
group_data5 = df[['대륙', '상품종류', '총이윤']].groupby(['대륙', '상품종류']).sum()

In [225]:
group_data5

                                             총이윤
대륙                 상품종류
Asia               Baby Food        6.379205e+07
                   Beverages        8.647186e+06
                   Cereal           5.369351e+07
                   Clothes          3.886401e+07
                   Cosmetics        1.036069e+08
...                                          ...
Sub-Saharan Africa Meat             5.721001e+07
                   Office Supplies  1.269636e+08
                   Personal Care    2.666266e+07
                   Snacks           6.142855e+07
                   Vegetables       6.197819e+07

[84 rows x 1 columns]

In [226]:
group_df = group_data5.sort_values('총이윤', ascending=False)

In [238]:
group_df

                                   대륙             상품종류           총이윤
0                              Europe        Cosmetics  1.989963e+08
1                  Sub-Saharan Africa        Cosmetics  1.766093e+08
2                  Sub-Saharan Africa        Household  1.764783e+08
3                              Europe        Household  1.702985e+08
4                              Europe  Office Supplies  1.423337e+08
..                                ...              ...           ...
79       Middle East and North Africa           Fruits  1.265448e+06
80                               Asia           Fruits  1.252062e+06
81  Central America and the Caribbean           Fruits  9.974629e+05
82              Australia and Oceania           Fruits  7.464782e+05
83                      North America           Fruits  1.576935e+05

[84 rows x 3 columns]

In [227]:
# 멀티 인덱스에서 첫번째 인덱스만 만족하는 조건식?
group_df.loc[ ('Europe', 'Cosmetics'), ]

총이윤    1.989963e+08
Name: (Europe, Cosmetics), dtype: float64

In [228]:
group_df.reset_index(inplace=True)

In [229]:
group_df['대륙'].unique()

<StringArray>
[                           'Europe',                'Sub-Saharan Africa',
                              'Asia',      'Middle East and North Africa',
 'Central America and the Caribbean',             'Australia and Oceania',
                     'North America']
Length: 7, dtype: str

In [230]:
group_df.loc[group_df['대륙'] == 'Asia', ]

      대륙             상품종류           총이윤
7   Asia        Cosmetics  1.036069e+08
10  Asia        Household  9.787616e+07
13  Asia  Office Supplies  9.004857e+07
21  Asia        Baby Food  6.379205e+07
30  Asia           Cereal  5.369351e+07
32  Asia       Vegetables  4.561142e+07
35  Asia          Clothes  3.886401e+07
38  Asia           Snacks  3.443074e+07
41  Asia             Meat  3.255046e+07
59  Asia    Personal Care  1.703025e+07
65  Asia        Beverages  8.647186e+06
80  Asia           Fruits  1.252062e+06

In [231]:
# head(1) 진짜 개쇼킹이다 몰랐는데 와......

group_df.loc[group_df['대륙'] == 'Asia', ].head(1)

     대륙       상품종류           총이윤
7  Asia  Cosmetics  1.036069e+08

In [232]:
group_df.loc[group_df['대륙'] == 'Asia'].head(1).index

Index([7], dtype='int64')

In [233]:
group_df.loc[group_df['대륙'] == 'Asia'].head(1).index[0]

np.int64(7)

In [234]:
group_df.loc[group_df['대륙'] == 'Asia'].index[0]

np.int64(7)

In [235]:
group_df.loc[group_df['대륙'] == 'Asia', ].iloc[0,]

대륙              Asia
상품종류       Cosmetics
총이윤     103606872.69
Name: 7, dtype: object

In [236]:
index_list = []

for name in group_df['대륙'].unique():
    flag = group_df['대륙'] == name
    index_list.append(
        group_df.loc[flag, ].index[0]
        )
index_list

[np.int64(0),
 np.int64(1),
 np.int64(7),
 np.int64(8),
 np.int64(14),
 np.int64(18),
 np.int64(54)]

In [237]:
group_df.loc[index_list,]

                                   대륙       상품종류           총이윤
0                              Europe  Cosmetics  1.989963e+08
1                  Sub-Saharan Africa  Cosmetics  1.766093e+08
7                                Asia  Cosmetics  1.036069e+08
8        Middle East and North Africa  Household  1.025355e+08
14  Central America and the Caribbean  Household  8.873831e+07
18              Australia and Oceania  Cosmetics  6.760413e+07
54                      North America  Household  2.148805e+07

#### ~~이 거지같은~~ 억지스러운^^ 방법 말고 가장 쉬운 법

In [221]:
# 1. idxmax() 함수를 이용: value가 최대인 인덱스를 출력

group_data5.idxmax()

총이윤    (Europe, Cosmetics)
dtype: object

In [222]:
group_data5

                                             총이윤
대륙                 상품종류
Asia               Baby Food        6.379205e+07
                   Beverages        8.647186e+06
                   Cereal           5.369351e+07
                   Clothes          3.886401e+07
                   Cosmetics        1.036069e+08
...                                          ...
Sub-Saharan Africa Meat             5.721001e+07
                   Office Supplies  1.269636e+08
                   Personal Care    2.666266e+07
                   Snacks           6.142855e+07
                   Vegetables       6.197819e+07

[84 rows x 1 columns]

In [223]:
group_data5.groupby(level=0).idxmax()

                                                                              총이윤
대륙
Asia                                                            (Asia, Cosmetics)
Australia and Oceania                          (Australia and Oceania, Cosmetics)
Central America and the Caribbean  (Central America and the Caribbean, Household)
Europe                                                        (Europe, Cosmetics)
Middle East and North Africa            (Middle East and North Africa, Household)
North America                                          (North America, Household)
Sub-Saharan Africa                                (Sub-Saharan Africa, Cosmetics)

#### 수강생 분이 하신 방법

In [240]:
df2 = df[['대륙', '상품종류', '총이윤']].groupby(['대륙', '상품종류']).sum()

In [241]:
df2

                                             총이윤
대륙                 상품종류
Asia               Baby Food        6.379205e+07
                   Beverages        8.647186e+06
                   Cereal           5.369351e+07
                   Clothes          3.886401e+07
                   Cosmetics        1.036069e+08
...                                          ...
Sub-Saharan Africa Meat             5.721001e+07
                   Office Supplies  1.269636e+08
                   Personal Care    2.666266e+07
                   Snacks           6.142855e+07
                   Vegetables       6.197819e+07

[84 rows x 1 columns]

In [242]:
df['상품종류'].unique()

<StringArray>
[  'Personal Care',       'Cosmetics',      'Vegetables',          'Cereal',
 'Office Supplies',       'Household',       'Beverages',          'Fruits',
            'Meat',          'Snacks',         'Clothes',       'Baby Food']
Length: 12, dtype: str

In [246]:
# pandas에서 sort_values에 인덱스를 넣어도 실행이 될 수 있도록 업데이트
# 구버전에서는 해당 함수가 실행되지 않을 수 있다.

# df3 = df2.reset_index() 를 넣어주면 구버전에서도 실행됨

df3 = df2.sort_values(['대륙', '총이윤'], ascending=False)

In [245]:
for i in range(len(df3)):
    if i % 12 == 0:
        print(df3.iloc[[i],])

                                       총이윤
대륙                 상품종류
Sub-Saharan Africa Cosmetics  1.766093e+08
                                 총이윤
대륙            상품종류
North America Household  21488054.61
                                                총이윤
대륙                           상품종류
Middle East and North Africa Household  102535493.7
                           총이윤
대륙     상품종류
Europe Cosmetics  1.989963e+08
                                                     총이윤
대륙                                상품종류
Central America and the Caribbean Household  88738305.47
                                        총이윤
대륙                    상품종류
Australia and Oceania Cosmetics  67604133.4
                         총이윤
대륙   상품종류
Asia Cosmetics  1.036069e+08

#### 다음 내용

In [250]:
# 한 column은 오름차순, 한 column은 내림차순으로 하고 싶을 때
# 대륙으로는 오름차순, 총 이윤으로는 내림차순 정렬
# ascending에 리스트 형태

df_ex = df[['대륙', '상품종류', '총이윤']].groupby(['대륙', '상품종류']).sum()
df_ex = df_ex.reset_index()

In [252]:
df_ex.sort_values(['대륙', '총이윤'], ascending=[True, False], inplace=True)

In [254]:
df_ex.groupby('대륙').head(1)

                                   대륙       상품종류           총이윤
4                                Asia  Cosmetics  1.036069e+08
16              Australia and Oceania  Cosmetics  6.760413e+07
30  Central America and the Caribbean  Household  8.873831e+07
40                             Europe  Cosmetics  1.989963e+08
54       Middle East and North Africa  Household  1.025355e+08
66                      North America  Household  2.148805e+07
76                 Sub-Saharan Africa  Cosmetics  1.766093e+08

In [ ]:
# 대륙을 빼도 된다고?
# 깃헙봐라!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


df_ex = df[['대륙', '상품종류', '총이윤']].groupby('상품종류').sum()
df_ex = df_ex.reset_index()
df_ex.sort_values('총이윤', ascending=False, inplace=True)
df_ex.groupby('대륙').head(1)

,상품종류,대륙,총이윤
6,Household,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,7.187384e+08
4,Cosmetics,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,7.134390e+08
8,Office Supplies,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,5.201832e+08
0,Baby Food,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,4.023250e+08
2,Cereal,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,3.723787e+08
3,Clothes,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,3.196366e+08
11,Vegetables,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,2.675511e+08
7,Meat,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,2.279643e+08
10,Snacks,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,2.273301e+08
9,Personal Care,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,1.103348e+08
1,Beverages,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,6.123743e+07
5,Fruits,AsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAsiaAs...,9.774770e+06