### DF간의 결합


- 일반적으로 데이터는 하나의 table로 저장이 되지 않는다.
    - 데이터는 분할 관리하는 것이 일반적 (효율적)
    - column 개수를 줄이고 index를 늘리는 형태로 데이터 저장 관리
        - column이 많다: 다른 요소의 데이터가 많다
        - index가 많다: 정보가 많다
        - 데이터의 로드 속도가 올라간다.
- 대규모의 데이터를 받아오면 여러 개의 파일로 구성되어 있다.

1. 유니언 결합 (UNION)
    - 단순하게 행이나 열을 결합
    - pandas에서는 concat() 함수를 이용하여 유니언 결합
    - 단순한 결합 형태이기 때문에 DF 개수에 제한을 두지 않는다.
    - pd.concat( [DF1, DF2, ...] )
        - 매개변수
            - axis
                - default 0
                - 0(rows): 행결합
                - 1(cols): 열결합
            - ignore_index
                - default False
                - True로 변경하면 axis 매개변수의 값을 초기화
                    - axis = 0: index 초기화 (기존의 index 제거)
                    - axis = 1: column 초기화 (기존의 column명 제거)

2. 조인 결합 (JOIN)
    - 특정한 조건에 맞게 데이터 간의 열을 결합하는 방식
    - 데이터프레임과 데이터프레임간의 조인 결합 → 특정 컬럼의 데이터들이 같은 값들로 어우러져 있을 때만 열을 추가하는 결합
    - pandas, DataFrame에 merge() 함수를 사용
    - 특정 조건에 맞춰서 열을 결합하기 때문에 데이터프레임은 2개 사용
    - pd.merger(DF1, DF2)
        - 매개변수
            - on
                - 조건 (두 개의 데이터프레임이 공통적으로 가진 데이터 column의 이름)
                - column의 이름이 다른 경우
                    - 두 개의 데이터프레임을 로드하고 컬럼의 이름을 변경한 뒤 조인 결합
                    - left_on, right_on 매개변수를 이용해서 각각의 컬럼명을 입력
            - how
                - 어떻게 결합할 것인가?
                (A집합과 B집합이 있을 때, A∩B≠∮)
                    - inner (A∩B)
                    - left (A)
                    - right (B)
                    - outer (A∪B)
    - DataFrame.merge(오른쪽 데이터프레임명)

### 코드

In [2]:
import pandas as pd

In [4]:
_val = {
    'id': ['test', 'test2'],
    'password': ['1111', '2222']
}

df1 = pd.DataFrame(_val)

df1

      id password
0   test     1111
1  test2     2222

In [5]:
_val2 = {
    'id': ['test', 'test3', 'test4'],
    'name': ['kim', 'park', 'lee']
}

df2 = pd.DataFrame(_val2)
df2

      id  name
0   test   kim
1  test3  park
2  test4   lee

In [8]:
# 유니언 결합: concat() 함수를 이용(단순 행 결합/열 결합)

pd.concat(
    [df1, df2], axis=0
)

      id password  name
0   test     1111   NaN
1  test2     2222   NaN
0   test      NaN   kim
1  test3      NaN  park
2  test4      NaN   lee

In [11]:
pd.concat(
    [df1, df2], axis=0, ignore_index=True
)

      id password  name
0   test     1111   NaN
1  test2     2222   NaN
2   test      NaN   kim
3  test3      NaN  park
4  test4      NaN   lee

In [12]:
# 조인 결합

pd.merge(df1, df2, on='id', how='inner')

     id password name
0  test     1111  kim

In [13]:
pd.merge(df1, df2, on='id', how='left')

      id password name
0   test     1111  kim
1  test2     2222  NaN

In [14]:
pd.merge(df1, df2, on='id', how='right')

      id password  name
0   test     1111   kim
1  test3      NaN  park
2  test4      NaN   lee

In [15]:
pd.merge(df1, df2, on='id', how='outer')

      id password  name
0   test     1111   kim
1  test2     2222   NaN
2  test3      NaN  park
3  test4      NaN   lee