#### 연습 문제
- Doc2Vec을 이용하여 감성 분석
- ratings_train.txt 파일 로드
    - 특수 문자, 2칸 이상의 공백을 제거하는 정규화 함수 이용
    - document column의 중복 제거
    - 빈 텍스트가 존재한다면 제거
    - 상위 5000개 데이터를 학습 데이터로
- 토큰화 Komoran
    - 품사 필터: NNP, NNG, VV, VA, MAG, XR 사용
    - 불용어: 하다, 되다, 이다, 것, 수, 거
- 독립변수(document), 종속변수(label) 데이터를 나눠주고 train, text로 데이터 분할(8:2)
- Doc2Vec 객체 생성하여 벡터화
    - 매개변수
        - vector_size = 200
        - window = 5
        - min_count = 2
        - dm = 1
        - negative = 5
        - seed = 42
        - epochs = 50
    - train data 사용하여 학습
- Doc2Vec 객체에서 train, test 데이터를 infer_vector() 함수를 이용하여 벡터 데이터 생성
- ML 분류 모델을 이용하여 임베딩된 데이터를 독립 변수로 사용하여 학습
    - 정확도 확인
    - Logistic
        - max_iter = 2000
        - random_state = 42
    - LinearSVC
        - random_state = 42
- test 데이터를 이용하여 2개의 모델 중 정확도 높은 모델을 검색

In [1]:
from konlpy.tag import Komoran
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.metrics import classification_report

import numpy as np
import pandas as pd
import re

##### **<font color = red>우당탕탕 내 풀이ㅠ</font>**

In [2]:
df = pd.read_csv('../data/ratings_train.txt', sep = '\t')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  str
 2   label     150000 non-null  int64
dtypes: int64(2), str(1)
memory usage: 3.4 MB

In [4]:
df.drop('id', axis = 1, inplace = True)
df.dropna(inplace = True)
df.reset_index(drop = True, inplace = True)

In [5]:
for idx, data in enumerate(df['document']):
    df.loc[idx, 'document'] = data.strip()

In [6]:
df.drop_duplicates('document', inplace=True)
df.reset_index(drop = True, inplace = True)

In [7]:
df['document'].value_counts()

document
아 더빙.. 진짜 짜증나네요 목소리                                              1
흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나                                1
너무재밓었다그래서보는것을추천한다                                                1
교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정                                    1
사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다    1
                                                                ..
인간이 문제지.. 소는 뭔죄인가..                                              1
평점이 너무 낮아서...                                                    1
이게 뭐요? 한국인은 거들먹거리고 필리핀 혼혈은 착하다?                                  1
청춘 영화의 최고봉.방황과 우울했던 날들의 자화상                                      1
한국 영화 최초로 수간하는 내용이 담긴 영화                                         1
Name: count, Length: 146182, dtype: int64

In [ ]:
def normalize(text):
    # 특수 문자, 공백에 대한 처리
    text = re.sub(r'[^가-힣0-9a-zA-Z\s\.]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [ ]:
for idx, data in enumerate(df['document']):
    df.loc[idx, 'document'] = normalize(str(data))

In [10]:
flag = (df['document'] == '')
df.loc[flag, ]

       document  label
972                  0
1834                 1
2151                 1
2495                 0
2639                 1
...         ...    ...
142828               0
143383               0
145577               1
145610               0
145657               0

[181 rows x 2 columns]

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 146182 entries, 0 to 146181
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   document  146182 non-null  str
 1   label     146182 non-null  int64
dtypes: int64(1), str(1)
memory usage: 2.2 MB

In [12]:
komoran = Komoran()

In [13]:
allow_pos = ['NNP', 'NNG', 'VV', 'VA', 'MAG', 'XR']
stop_word = ['하다', '되다', '이다', '것', '수', '거']

In [14]:
def tokenize(text):

    tokens = []
    for word, pos in komoran.pos(text):
        if pos in allow_pos:
            if pos in ['VV', 'VA']:
                word += '다'
            if word not in stop_word and len(word) > 1:
                tokens.append(word)
    return tokens

In [15]:
X = df['document'][:5000].values
y = df['label'][:5000].values

In [16]:
X

<StringArray>
[                                                                   '아 더빙.. 진짜 짜증나네요 목소리',
                                                      '흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나',
                                                                      '너무재밓었다그래서보는것을추천한다',
                                                          '교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정',
                          '사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 던스트가 너무나도 이뻐보였다',
                                            '막 걸음마 뗀 3세부터 초등학교 1학년생인 8살용영화. ...별반개도 아까움.',
                                                                  '원작의 긴장감을 제대로 살려내지못했다.',
 '별 반개도 아깝다 욕나온다 이응경 길용우 연기생활이몇년인지..정말 발로해도 그것보단 낫겟다 납치.감금만반복반복..이드라마는 가족도없다 연기못하는사람만모엿네',
                                                                 '액션이 없는데도 재미 있는 몇안되는 영화',
                                            '왜케 평점이 낮은건데 꽤 볼만한데.. 헐리우드식 화려함에만 너무 길들여져 있나',
 ...
                                                                          '지저분하고 불쾌한 영화.',
                                                                                  '솔직합니다',
                                                           '제 생각엔 명작 중에 명작입니다. 강력 추천합니다.',
                                                                        '사랑스러운 영화 계속 보게됨',
                                                                      '감명깊게 봤음 열심히 살아야겠다',
                                       '별 1개도주기아깝다 여자애한명을 두고 남자둘의 싸움내용임 그냥 소설다운 내용이라고할까나',
                                                      '포스님의 귀여운 연기 잘봤어요. 사고때문에 중단되서 아쉽네요',
                                                                      '걍 영화인거같다 참고로 끝까지봄',
                                                                      '나중이라도 꼭 한번 보고싶습니다',
                                                              '뭐야 대중을 공감시켜야지 감독지혼자만 공감하냐']
Length: 5000, dtype: str

In [17]:
X = [tokenize(doc) for doc in X]

In [18]:
X

[['더빙', '진짜', '짜증', '나다', '목소리'],
 ['포스터', '초딩', '영화', '오버', '연기', '가볍다'],
 [],
 ['교도소', '이야기', '솔직히', '재미', '없다', '평점', '조정'],
 ['익살', '연기', '돋보이다', '영화', '스파이더맨', '늙다', '보이다', '커스틴 던스트', '너무나'],
 ['걸음마', '떼다', '초등학교', '학년', '영화', '반개', '아깝다'],
 ['원작', '긴장감', '제대로', '살리다'],
 ['반개',
  '아깝다',
  '나오다',
  '이응경',
  '길용우',
  '연기',
  '생활',
  '정말',
  '발로',
  '납치',
  '감금',
  '반복',
  '반복',
  '드라마',
  '가족',
  '없다',
  '연기',
  '못하다',
  '사람',
  '모이다'],
 ['액션', '없다', '재미', '있다', '영화'],
 ['평점', '낮다', '보다', '헐리우드', '화려', '너무', '길들이다', '있다'],
 [],
 ['눈물', '나서다', '죽다', '향수', '자극', '허진호', '감성', '절제', '멜로', '달인'],
 ['울다', '손들다', '횡단보도', '건너다', '뛰쳐나오다', '이범수', '연기', '드럽다'],
 ['담백', '깔끔', '좋다', '신문', '기사', '로만', '보다', '보다', '자꾸', '잊어버리다', '사람'],
 ['취향',
  '존중',
  '진짜',
  '극장',
  '보다',
  '영화',
  '가장',
  '재다',
  '감동',
  '스토리',
  '어거지',
  '감동',
  '어거지'],
 ['매번', '긴장'],
 ['사람',
  '웃기다',
  '바스코',
  '이기다',
  '락스',
  '바비',
  '이기다',
  '아이돌',
  '깔다',
  '그냥',
  '까다',
  '안달',
  '보이다'],
 ['굿바이 레닌', '표절', '이해', '갈수록', '재미없다'],
 ['이건', '정말', '깨알', '캐스팅', '질퍽', '산뜻', '내용', '구성', '깨알'],
 ['약탈', '위하다', '변명', '착하다', '절대'],
 ['심오', '있다', '그냥', '학생', '선생', '놀아나다', '영화', '절대'],
 ['보다', '웃다', '가능'],
 ['재미없다',
  '지루',
  '같다',
  '음식',
  '영화',
  '만찬',
  '만찬',
  '이야기',
  '있다',
  '음식',
  '보다',
  '재미',
  '있다',
  '이건',
  '보다',
  '없다',
  '음식',
  '별로',
  '나오다',
  '핀란드',
  '풍경',
  '별로',
  '나오다'],
 ['절대', '평범', '영화', '수작', '말씀', '드리다'],
 ['주제', '좋다', '중반', '지루'],
 ['짜르다', '납득', '없다', '그렇다', '그렇다', '끄다'],
 ['고추', '털다'],
 ['카밀라', '연기'],
 [],
 ['센스', '있다', '연출력', '탁월', '캐스팅', '90년대', '향수'],
 ['포스', '위력', '다시', '깨닫다', '검사', '연기', '정말', '좋다', '완전', '명품', '드라마'],
 ['쓰레기', '시간', '아깝다'],
 ['재밌다', '별점', '이리', '은고'],
 ['라도', '기대', '죄인', '죄인'],
 ['아직', '드라마', '인생', '최고'],
 ['패션', '대하다', '열정', '안나', '투어'],
 ['키이라 나이틀리', '연기', '대체', '정신', '장애', '장애'],
 ['작가', '정신', '나가다', '유령', '재미있다'],
 ['포스터', '있다', '보이다', '관객'],
 ['영화', '이렇다', '평가', '받다', '모르다'],
 ['단순', '은은', '매력', '영화'],
 ['알바',
  '내용',
  '없다',
  '무섭다',
  '거도',
  '없다',
  '웃기다',
  '거도',
  '없다',
  '완전',
  '싱겁다',
  '영화',
  '시간',
  '아깝다',
  '완전',
  '낚이다'],
 ['오다', '서리', '굶주리다'],
 ['정말', '들다', '보다', '보다', '방법', '없다'],
 ['윤제문',
  '멋지다',
  '배우',
  '발견',
  '소소',
  '일탈',
  '잔잔',
  '미소',
  '머금다',
  '음악',
  '조금',
  '아쉽다',
  '평점',
  '올리다'],
 ['평점', '속지', '마시', '시간', '낭비', '낭비'],
 ['리얼리티',
  '뛰어나다',
  '크다',
  '공감',
  '가다',
  '이민기',
  '캐릭터',
  '정신의학',
  '분노',
  '조절',
  '장애',
  '초기',
  '증상',
  '툭하면',
  '사람',
  '패다',
  '물건',
  '파손',
  '조금',
  '오바',
  '초반',
  '신선',
  '가다',
  '갈수록',
  '이민기',
  '정신',
  '상태',
  '공감',
  '불가'],
 ['마이너스', '없다', '보다', '영화', '수준', '북한', '만들다', '대다'],
 ['나다', '영화', '사랑합니다'],
 ['리스',
  '타르',
  '가르다',
  '용의',
  '주인',
  '이랑',
  '근친상간',
  '다니다',
  '소설',
  '제일',
  '멋지다',
  '자이',
  '니스',
  '드라마',
  '드래곤',
  '제일',
  '멋지다',
  '웃음',
  '감독',
  '토르',
  '다크 월드',
  '잡수다',
  '기본',
  '선방'],
 ['영화',
  '사람',
  '영혼',
  '어루만지다',
  '있다',
  '거치다',
  '세상사',
  '잠시',
  '잊다',
  '동화',
  '같다',
  '영화',
  '행복'],
 ['게이', '작다', '고추', '매운맛', '보이다', '진호', '간다'],
 ['이렇다', '가슴', '시리다', '보다', '드라마', '있다', '감동', '자체'],
 ['꼬마', '애가', '원한', '깊다', '그냥', '혼자', '나대다', '어쩌다'],
 ['재미있다'],
 ['좋다'],
 ['최고'],
 ['너무',
  '충격',
  '기분',
  '완전히',
  '꺼지다',
  '느낌',
  '활력',
  '없다',
  '너무나',
  '무겁다',
  '지독',
  '차갑다',
  '자비',
  '그저',
  '일본인',
  '상상력',
  '정말',
  '대단',
  '같다',
  '생각',
  '들다'],
 ['심심', '영화'],
 ['백봉기', '언제나', '오다'],
 ['보다', '그대로', '들어맞다', '예측', '카리스마', '없다', '악역'],
 ['불알', '나오다', '당황', '아무튼', '영화', '중간', '끝나다', '느낌'],
 ['평범', '함속', '아든', '평범', '일상', '조금', '밋밋'],
 ['보다',
  '계속',
  '보다',
  '전개도',
  '느리다',
  '주인공',
  '은희',
  '나오다',
  '소극',
  '모습',
  '짜증',
  '맨날',
  '언제',
  '끝나다',
  '기대',
  '전개',
  '빨리빨리'],
 ['사랑', '가슴속', '오다', '감정', '헤집다', '영화', '요정', '최고'],
 ['많다',
  '사람',
  '보다',
  '우리나라',
  '슬프다',
  '현대사',
  '단면',
  '대하다',
  '깊이',
  '생각',
  '사죄',
  '바로',
  '잡기',
  '위하다',
  '노력',
  '듣다',
  '보도',
  '연맹',
  '민간인',
  '학살',
  '이정',
  '이건',
  '명백',
  '살인',
  '살인자',
  '있다'],
 ['예전',
  '작품',
  '캐릭터',
  '에피소드',
  '재탕',
  '삼탕',
  '사골',
  '우려',
  '먹다',
  '내용',
  '가다',
  '시청률',
  '아예',
  '나오다',
  '이제',
  '중반'],
 ['김남길', '연기력', '초반', '몰입', '불구', '지루', '손예진'],
 ['재밌다', '비슷', '영화', '안보', '재미있다'],
 ['노래', '실력', '뽑다', '맞다', '박시환', '가면', '진짜', '망신'],
 ['일본', '영화', '유치'],
 ['이틀',
  '보다',
  '재밌다',
  '물건',
  '넣다',
  '조작',
  '열리다',
  '활짝',
  '열리다',
  '들어가다',
  '문자',
  '조작',
  '비번',
  '걸리다',
  '억지',
  '내용',
  '자체',
  '좋다'],
 [],
 ['달팽이', '빠르다', '재밌다'],
 ['어설프다', '전개', '어이없다', '결말'],
 ['부패', '로마노프 왕조', '기리다', '같다', '영화', '온몸', '항거', '러시아', '민중', '그저', '돌다'],
 ['내용', '전개', '무난', '편이', '보다'],
 ['매우', '실망'],
 ['한국',
  '영화',
  '흥행',
  '코드',
  '갈등',
  '갈등',
  '갈등',
  '화해',
  '감동',
  '평점',
  '남발',
  '흥행',
  '뻔하다'],
 ['아햏햏', '아햏햏', '아햏햏'],
 ['시작', '3분', '나오다', '리플릿', '사진', '보다', '불안'],
 ['단연', '최고'],
 ['감독', '영화', '만들다', '관객', '모르다', '엉망진창', '개진'],
 ['이건', '우뢰', '매다'],
 ['정말', '쓰레기', '영화'],
 ['진정', '위대', '영화', '최고'],
 ['별루'],
 ['내일', '기대'],
 ['조미', '좋아하다', '가요'],
 ['진짜', '까다', '부라리다', '쓰러지다'],
 ['성룡', '영화', '악인'],
 ['때리다', '걸스데이', '이혜리'],
 ['서기', '이쁘다'],
 ['완전', '재밌다', '백인', '공주', '귀여움'],
 ['인상', '영화'],
 ['세다', '스티', '완전', '추다', '정말', '재밌다'],
 ['재미있다', '영화'],
 ['클라라', '볼라', '화신'],
 ['진짜', '보다', '너무', '슬프다', '영화'],
 ['설정', '재밌다', '새롭다', '에피소드', '메인', '스토리', '차차', '나오다', '재밌다'],
 ['신카이 마코토', '작화', '카나', '연기', '대박'],
 ['재미없다', '진심', '캐스팅'],
 ['잔잔', '생각', '보다', '영화인', '같다'],
 ['감독', '고은님', '쓰다', '영화', '보다'],
 ['무섭다', '스토리'],
 ['영화', '억지', '노골적', '광고', '은은', '센스', '있다', '어떻다'],
 ['킬링타임'],
 ['크리스마스', '떠오르다', '영화'],
 ['재미있다', '보다', '매력', '행복'],
 ['음악', '완전히', '빠지다', '보다', '영화', '쪼다', '산만'],
 ['태어나다', '처음', '영화', '중간', '나오다', '불륜', '로맨스'],
 ['짜증', '아주', '전개', '짬뽕', '믹스', '음향', '무섭다'],
 ['솔직히', '나다', '별루', '덜다', '시간', '낭비', '느낌'],
 ['대박'],
 ['시청률', '기준', '패널', '가구', '거지', '명작', '드라마', '망치다', '서운'],
 ['내용', '이상해'],
 ['몬스터 주식회사', '3D', '재밌다', '보다'],
 ['내용', '전개', '너무나', '느리다'],
 ['소재', '흥미', '끌다', '이야기', '전개', '투박', '몰입'],
 ['절대', '보지', '마라', '쓰레기', '영화'],
 ['중국인',
  '특유',
  '과장',
  '허풍',
  '있다',
  '보이다',
  '안간힘',
  '쓰다',
  '노력',
  '가상',
  '고증',
  '현실감',
  '떨어지다',
  '설정',
  '거북',
  '도대체',
  '이렇다',
  '스스로',
  '대포',
  '장하'],
 ['그냥', '불법체류', '때려잡다', '영화', '좋다', '우상', '만들다', '미국', '따뜻', '설정', '이건'],
 ['2년', '주인공', '생애', '전부', '드러나다'],
 ['별점', '가자'],
 ['별로'],
 ['보다', '지나다', '남기다', '재미있다'],
 ['아니', '일다'],
 ['지나다', '다시', '보다', '영화', '다시', '보다', '순수', '사랑', '감동', '연기'],
 ['올레',
  '공짜',
  '있다',
  '보다',
  '허다',
  '스토리',
  '문제',
  '연기자',
  '전혀',
  '배역',
  '이랑',
  '어울리다',
  '상대',
  '배우',
  '따로',
  '같다',
  '이건',
  '연기자',
  '문제',
  '있다',
  '보다',
  '진심',
  '완전',
  '별로',
  '라미란',
  '아들'],
 ['너무', '욕심', '많다', '영화', '제대로', '보이다'],
 ['빵점'],
 ['아주', '쓰다'],
 ['아주', '모자', '라진'],
 ['영화', '도둑들', '뫼비우스', '같다', '나라', '만들다', '믿다'],
 ['온몸', '찌릿', '짜릿', '용기', '가지다'],
 ['정말', '재미있다', '교훈', '영화'],
 ['당시', '상황', '주제', '주입식', '긴장감', '있다', '재밌다', '전하다', '작품'],
 ['케이블', '그만', '나오다'],
 ['다르다', '차이밍량', '섞이다', '짬뽕', '그릇', '담기다'],
 ['여군', '재다', '없다', '건지', '재다', '없다', '재다', '없다', '질리다', '다이'],
 ['좋다'],
 ['한석규', '김혜수', '연기', '돋보이다', '영화', '모르다', '많이', '어설프다', '영화'],
 ['솔직히',
  '에볼라바이러스',
  '떠들석',
  '보다',
  '영화',
  '작품',
  '영화',
  '믿다',
  '힘들다',
  '정도',
  '정말',
  '만들다',
  '마지막',
  '후반부',
  '살짝',
  '아쉽다',
  '이정',
  '도면',
  '수작',
  '시간',
  '아깝다',
  '영화'],
 ['보다', '만해'],
 ['재미있다', '허풍', '떨다'],
 ['용가리', '진짜', '매다'],
 ['영화',
  '이제서야',
  '감히',
  '인생',
  '최고',
  '영화',
  '하나로',
  '꼽다',
  '있다',
  '작품',
  '어떻다',
  '살다',
  '위하다',
  '고민',
  '시간',
  '모건 프리먼',
  '나이',
  '들다',
  '여전히',
  '섹시'],
 ['작가', '별로', '내용', '진짜', '맨날', '그냥', '기대', '재방송', '혹시나', '없다', '진짜'],
 ['명작', '명작', '있다', '보다', '보다', '여운', '남다', '영화'],
 ['진짜',
  '조금',
  '보다',
  '상업',
  '영화',
  '못하다',
  '만들다',
  '아쉽다',
  '충분히',
  '재미있다',
  '개인',
  '조금',
  '잔인',
  '자극',
  '노출',
  '화끈',
  '어떻다',
  '국산',
  '영화',
  '많이',
  '아끼다',
  '보이다'],
 ['그만', '끌다', '이제', '끝내다', '지겹다', '지겹다'],
 [],
 ['드니', '연기', '일품', '맥스', '죽이다'],
 ['괜찮다', '작품'],
 ['너무', '좋다', '영화'],
 ['정말', '실망'],
 ['배우', '뜨다', '영화', '찍다', '뜨다', '진짜', '모르다', '면상', '보다', '알다', '자신', '모르다'],
 ['어린이', '좋아하다', '어리다', '동심', '멀리', '뜨다', '낫다'],
 ['무술', '들다'],
 [],
 ['크리스토퍼', '왈츠', '타란티노', '조합'],
 ['한국', '에선', '유명한', '외국', '상상', '초월', '유명', '영화'],
 ['오랜만'],
 ['아쉽다',
  '오늘',
  '방도',
  '보다',
  '방송',
  '대본',
  '완성도',
  '있다',
  '느낌',
  '받다',
  '요즘',
  '드라마',
  '막장',
  '지치다',
  '정말',
  '바른',
  '드라마',
  '악역',
  '그리',
  '심하다',
  '어이없다',
  '화이팅'],
 ['평점',
  '조절',
  '위원회',
  '나오다',
  '웃음',
  '김혜선',
  '내일이 오면',
  '순정',
  '순정',
  '역할',
  '정도',
  '해내다',
  '정말',
  '의외',
  '연기',
  '20년',
  '사람',
  '요즘',
  '사극',
  '벌어지다',
  '있다',
  '대하다',
  '연기',
  '논란',
  '왠지',
  '코미디',
  '의하다',
  '장면',
  '같다',
  '웃음'],
 ['영화', '끝나다', '멍하다', '보다', '한마디', '나오다', '같다'],
 ['공유'],
 ['상쾌', '발랄', '영화', '끌다', '소재', '유쾌', '해설'],
 ['소파', '치다', '앉다', '지키다', '보다', '이유', '없다', '작품'],
 ['로큰롤'],
 ['주되다',
  '타겟',
  '어린이',
  '일반',
  '논리',
  '통하다',
  '알다',
  '게임',
  '흥미',
  '요원',
  '주인공',
  '너무',
  '능력',
  '별로',
  '재미없다',
  '배경',
  '거슬리다'],
 ['뮤지컬 영화',
  '사운드',
  '녹음',
  '엉망',
  '추다',
  '내용',
  '뻔하다',
  '주인공',
  '목소리',
  '너무',
  '어울리다',
  '어제',
  '뛰다',
  '나가다',
  '참다',
  '진심',
  '말리다',
  '영국',
  '예산',
  '영화',
  '뮤지컬',
  '영화',
  '맘마미아',
  '10'],
 ['어리다', '나이', '보다', '좋아하다', '로맨틱', '코미디'],
 ['게이', '인줄', '모르다', '보다'],
 ['알바', '끄다', '절다'],
 ['영화', '받다', '보다', '알다', '영화', '배우', '스텝', '감독', '꼭두각시'],
 ['최악'],
 ['정말', '아름답다', '영화'],
 ['자극', '익숙', '현대인', '보다', '떼다', '힘들다', '연출력'],
 ['읽다', '당하다'],
 ['정말',
  '짜증',
  '극치',
  '보이다',
  '영화',
  '굉장히',
  '느낌',
  '뚱뚱',
  '못생기다',
  '남자',
  '연기',
  '시종일관',
  '보다',
  '고역',
  '흘러나오다',
  '잔잔',
  '클래식',
  '음악',
  '조차',
  '듣다',
  '싫다',
  '짜증',
  '정도',
  '상당히',
  '싫다',
  '영화'],
 ['감동', '감동', '정말', '최고'],
 ['별점',
  '아깝다',
  '얼마나',
  '내용',
  '진부',
  '나오다',
  '재밌다',
  '사람',
  '초딩',
  '죄송',
  '너무',
  '화가',
  '나서다',
  '보다',
  '없다',
  '보다',
  '그냥',
  '비판',
  '집기',
  '같다'],
 ['짜증', '내다'],
 ['돼지', '먹다', '닭목', '따다', '장면', '에선', '무당'],
 [],
 ['유치', '지루'],
 ['판타지', '가져가다'],
 ['윤종신',
  '복귀',
  '좋다',
  '이하늘',
  '도대체',
  '뽑히다',
  '없다',
  '참가자',
  '실력',
  '따지다',
  '심사',
  '위원',
  '인격',
  '실력',
  '쌓다',
  '오시',
  '그만'],
 ['광장', '작품', '옛날', '보고 싶다'],
 ['최고', '영화'],
 ['어리다',
  '시절',
  '너무',
  '무섭다',
  '재미있다',
  '보다',
  '추억',
  '판타지',
  '영화',
  '절대',
  '나쁘다',
  '금물',
  '지옥',
  '가요'],
 ['기존', '멜로', '영화', '형식', '탈피', '감정', '절제', '지나치다', '너무', '담백', '영화'],
 ['나다', '사랑비', '서주', '빠지다', '나다', '절대', '잊다', '후회', '도안', '할거'],
 ['이영화', '보다', '교훈', '남은', '인생', '화려', '나오다'],
 ['추억', '젖다', '좋다', '생각', '없이', '가볍다', '보다', '추천'],
 ['단순', '싸이코', '벗어나다'],
 ['만들다', '가요', '예전', '만들다', '다시', '개봉', '가요', '너무', '접하다'],
 ['사랑', '영화', '보고', '연잇다', '보다', '귀여워'],
 ['청춘 영화',
  '있다',
  '감성',
  '넘치다',
  '순간',
  '지나가다',
  '다시',
  '돌아오다',
  '순간',
  '무한',
  '젊음',
  '있다',
  '감성'],
 ['건담', '시리즈', '아직', '최고봉'],
 ['개코', '요즘', '갈수록', '코너', '달다', '재다', '웃음', '이안', '나다'],
 ['사다코', '서리다', '우물', '펀치', '감동'],
 ['후세',
  '사랑',
  '결정',
  '계기',
  '시간',
  '표현',
  '생명',
  '빼앗다',
  '이유',
  '시노',
  '출현',
  '연극',
  '알리다',
  '생각',
  '시노',
  '얼마나',
  '시랑',
  '노력',
  '보이다',
  '좋다'],
 ['새벽', '시간', '일본', '영화', '전부', '일본', '영화', '원래', '이러다'],
 ['강수연', '나가다', '최정원', '신음'],
 ['정말', '김혜성', '너무', '예쁘다', '이현진', '웃다', '정말'],
 ['가발', '쓰다'],
 ['화려', '이인상', '깊다', '배두나', '연기', '정말'],
 ['10대', '위하다', '성적', '호기심', '영화'],
 ['감동', '영화'],
 ['이건', '필요', '없다', '그냥', '닥치다', '보다'],
 ['각기', '사람', '재밌다', '멋지다', '사랑', '영화'],
 ['미국', '드라마', '파워', '정말', '수없다', '미묘', '사로잡다', '최고'],
 ['너무너무', '훈훈'],
 ['응답하라', '은지원', '원도', '스스로'],
 ['너무', '웃기다', '배꼽', '빠지다', '영화', '있다'],
 ['구성', '상당히', '부실', '영화', '네이버', '평점', '믿다', '없다'],
 ['끌다', '로드', '몰락', '가져오다', '오우삼', '헐리우드', '작품', '가장', '재미없다'],
 ['영웅본색', '연출', '인지', '현실', '제로', '영화'],
 ['작다',
  '하나에',
  '설레다',
  '학창',
  '시절',
  '그때',
  '느낌',
  '다시',
  '느끼다',
  '시간',
  '장면',
  '대사',
  '배경',
  '음악',
  '없다',
  '드라마'],
 ['진심', '재미', '없다', '너무', '평점', '높다', '화나다'],
 ['더럽다', '재미없다', '형태', '오다', '닿다', '허무', '완벽히', '지루', '영화', '영양가', '없다', '영화'],
 ['이승기', '정말', '연기', '조연', '연기', '정말'],
 ['현실', '현실'],
 ['오늘', '현충일', '특집', '프로', '보다', '매우', '훌륭', '작품'],
 ['의미', '동급'],
 ['제대', '보다', '재밌다'],
 ['영화',
  '보다',
  '마음',
  '휴가',
  '다녀오다',
  '느낌',
  '하지',
  '잔잔',
  '지루',
  '다시',
  '보다',
  '영화',
  '햇살',
  '가득',
  '부엌',
  '요리',
  '인상'],
 ['코믹', '좋다', '짜임새', '너무', '허술'],
 ['그때',
  '당시',
  '나라',
  '판타지',
  '로맨스',
  '없다',
  '아직',
  '신현준',
  '장군',
  '연기',
  '괜찮다',
  '한석규',
  '전성시대',
  '열리다',
  '영화',
  '이때',
  '한석규',
  '가다'],
 ['일단', '재생', '괴물', '같다', '서스펜스', '귀신', '같다', '흡입'],
 ['진짜',
  '댓글',
  '한번쯤',
  '영화인',
  '같다',
  '죽기',
  '직전',
  '소원',
  '들어주다',
  '보다',
  '죽기',
  '직전',
  '살다',
  '같다',
  '감동',
  '없다',
  '진짜',
  '영화',
  '발톱',
  '따라가다',
  '쓰레기',
  '영화',
  '와다',
  '실망'],
 ['시간',
  '밝다',
  '긍정',
  '드라마',
  '보다',
  '보기',
  '보다',
  '오버',
  '연기',
  '거슬리다',
  '연기',
  '너무',
  '홍혜정',
  '이그',
  '마도',
  '후련',
  '기도',
  '고시원',
  '나머지',
  '답답',
  '내다',
  '월요일',
  '해피',
  '보다'],
 ['정치인', '모순', '인가', '정치범', '모순'],
 ['어떻다', '상상', '대단'],
 ['어렵다', '전쟁', '대하다', '묘사', '모르다'],
 ['일본', '극장판', '만들다', '우리나라', '에선', '개봉', '하니', '이건'],
 ['개그콘서트', '보다', '전화', '끊다', '개그', '콘서트', '없애다'],
 ['한물', '동서양', '배우', '싸움판'],
 ['푸다', '기대'],
 ['세계', '최초', '반공', '애니매이션', '역사', '가치'],
 ['감각', '시각', '바라보다', '색다르다', '느낌', '사랑', '문학'],
 ['엄마', '무고', '감옥살이', '시키다', '시키다', '이해'],
 ['이영화', '제발', '보세', '감독', '미치다', '만들다', '정도'],
 ['신나다', '흑인', '음악', '아이스 큐브', '남다', '없다'],
 ['드럽다', '재미없다', '시간', '시간', '어쩌다'],
 ['그저', '한마디', '알리다'],
 ['진짜', '생생', '느끼다'],
 ['재밌다', '평점', '이상', '정도', '낮다'],
 ['옥소리', '프로필', '사진', '남기다', '가다', '완전', '대박', '진짜', '아우', '짜증'],
 ['드라마', '너무'],
 ['진짜', '너무', '좋다'],
 ['연기'],
 ['영화', '다시', '나오다', '그때', '시절', '나타내다', '같다'],
 ['중간', '정도', '보다', '대단'],
 ['까다', '제맛', '까다', '제맛'],
 ['소설', '재미없다'],
 ['액션', '영화', '범죄', '느와르', '영화', '범죄', '느와르', '영화', '실패작'],
 ['없다', '매력', '빠지다', '영화'],
 ['모녀',
  '토막',
  '살해',
  '살인자',
  '성애',
  '말이',
  '감동',
  '받다',
  '사람',
  '본인',
  '피해자',
  '감동',
  '받다',
  '진심',
  '묻다'],
 ['재밌다', '평점', '이렇다', '구리지'],
 ['보다', '아깝다', '진짜', '놓다', '진짜', '명작'],
 ['필름', '아깝다', '재미', '더럽다', '없다', '수준', '매미'],
 ['보다'],
 ['영화', '재미있다'],
 ['남주인공',
  '연기력',
  '짧다',
  '소리',
  '듣다',
  '너무',
  '힘들다',
  '매니저',
  '역활',
  '분이',
  '남주인공',
  '좋다',
  '생각',
  '들다',
  '정도',
  '영화',
  '자체',
  '적당히',
  '보다'],
 ['액션', '스릴러', '액션', '스릴', '없다'],
 ['완전', '스토리', '엉망', '완전'],
 ['영화', '전달', '모르다', '거리'],
 ['좋다', '영화'],
 ['더빙', '이상', '할머니', '월래', '익숙'],
 ['나오다'],
 ['부족'],
 ['정말', '그대로', '영화'],
 ['보다', '기억', '진개', '천카이거', '감독', '이름', '기억', '두다'],
 ['정은지', '언니', '연기', '노래', '부르다', '마지막', '웃다', '즐겁다', '보다', '트로트의 연인'],
 [],
 ['망하다'],
 ['아이', '시선', '보다', '전쟁', '보다', '내내', '가슴', '먹먹'],
 ['사람',
  '재미없다',
  '레알',
  '기대',
  '생각',
  '보다',
  '여자',
  '복순이',
  '다투다',
  '장면',
  '굳이',
  '없다',
  '생각',
  '몰입',
  '겁나다',
  '없애다',
  '어색',
  '보이다'],
 ['설정', '연속극', '같다', '느낌', '들다', '배우', '연기', '뛰어나다'],
 ['여주인공', '인터뷰', '지루', '죽다', '알다', '그냥저냥', '킬링타임', '스릴러'],
 ['박스',
  '오피스',
  '그냥',
  '몰아주다',
  '어떻다',
  '영화',
  '옛날',
  '90년대',
  '우뢰',
  '수준',
  '폭탄',
  '싸움',
  '가나',
  '폭탄',
  '나가다',
  '다르다'],
 ['감독', '여자', '보니', '기량', '많이', '딸리다'],
 ['보다'],
 ['영화', '개연', '없다', '허무', '만들다', '조디', '포스터', '이쁘다', '모습', '영화'],
 ['굳다', '굳다'],
 ['스토리', '개막', '사랑이야', '기도', '아니', '보다', '시간', '아끼다', '보다', '호구'],
 ['살리다', '아깝다', '세기', '대사'],
 ['평점',
  '너무',
  '높다',
  '전혀',
  '재미있다',
  '쓸데없이',
  '많다',
  '영화',
  '조연',
  '뒷받침',
  '중요',
  '조연',
  '내용',
  '자체',
  '전혀',
  '없다',
  '여배우',
  '별로',
  '매력',
  '없다',
  '이틀',
  '저스트',
  '고위',
  '애니',
  '스톤',
  '보다',
  '영화',
  '보다',
  '그렇다',
  '실망'],
 ['맛깔', '드라마'],
 ['시베리아', '인가', '가다', '훈련', '나오다', '작살'],
 ['이건',
  '시종일관',
  '제목',
  '야경꾼 일지',
  '지금',
  '넘어가다',
  '넘어가다',
  '군가',
  '얘기',
  '그렇다',
  '순간',
  '진짜',
  '지루함',
  '지존'],
 ['나이', '들다', '이해', '가다', '영화'],
 ['슬픔'],
 ['장면',
  '개연',
  '없다',
  '아역',
  '연기',
  '추노',
  '나오다',
  '민폐',
  '외국',
  '인줄',
  '초반',
  '그럴싸',
  '저급',
  '영화'],
 ['영화', '정말', '별루', '결말', '이상'],
 ['딱히', '재미', '없다'],
 ['송강호', '정말', '연기', '위하다', '태어나다', '인하다', '즐거움', '느끼다', '송강호', '연기', '파다'],
 ['일본', '영화', '수입', '금지', '시절', '비디오', '테이프', '돌리다', '불후의 명작', '그립다'],
 ['살인',
  '소재',
  '영화',
  '이토록',
  '재밌다',
  '살인',
  '대하다',
  '감독',
  '해석',
  '정말',
  '재치',
  '있다',
  '배우',
  '모습',
  '정말',
  '유쾌',
  '재밌다'],
 ['라파스', '신봉선', '닮다', '보다'],
 ['케이블', '그만', '재탕'],
 ['멋지다', '정말', '멋지다', '이외', '없다'],
 ['어떻다', '영화', '만들다', '의문', '당대', '최고', '영화', '지금', '보다', '결코', '떨어지다'],
 ['지금', '내다', '보다', '한심'],
 ['쓰레기', '연예인', '재기'],
 ['좋다'],
 ['많다', '감동', '드라마'],
 ['발로',
  '만들다',
  '영화',
  '지진',
  '나서다',
  '주인공',
  '넘어지다',
  '사람',
  '유유히',
  '걷다',
  '다니다',
  '있다',
  'CG',
  '연기',
  '시나리오',
  '내용',
  '정말',
  '같다'],
 ['적당히', '언제', '끝나다'],
 ['잊다', '없다', '안개', '끼다', '워터', '다리', '마스코트'],
 ['사토시',
  '감독',
  '안타깝다',
  '돌아가다',
  '가슴',
  '먹먹',
  '정말',
  '천재',
  '감독',
  '가다',
  '이제',
  '와서',
  '다시',
  '보다',
  '작품',
  '대작'],
 ['많다', '생각', '지다'],
 ['없다', '줄다'],
 ['어리다',
  '영화로',
  '알다',
  '나이',
  '들다',
  '인생',
  '뭉클',
  '영화',
  '세상',
  '살아가다',
  '갈수록',
  '오다',
  '닿다',
  '많다',
  '세상',
  '비정',
  '비정',
  '함마',
  '지다',
  '따뜻',
  '친구'],
 ['영상', '너무나', '멋지다'],
 ['비디오', '있다', '보다', '1997년', '도인', '모르다', '정도', '만들다', '긴장감', '있다'],
 [],
 ['만들다',
  '재밌다',
  '영화',
  '길다',
  '다듬다',
  '소재',
  '좋다',
  '몰입',
  '기대',
  '이상',
  '매끄럽다',
  '부분',
  '있다',
  '연기'],
 ['지나다',
  '코미디',
  '뼈대',
  '있다',
  '가문',
  '이야기',
  '섞다',
  '지루',
  '박정아',
  '비롯',
  '배우',
  '보다',
  '민망',
  '연기',
  '펼치다',
  '기억',
  '남다',
  '없다'],
 ['군더더기', '없이', '진행', '재미', '없다', '문제'],
 ['심심', '재밌다', '연기', '알다', '배우', '포스'],
 ['괜찮다'],
 ['지대', '짜증', '아빠', '보다', '앗다', '민망', '죽다'],
 ['주다'],
 ['순이', '영화'],
 ['최악', '애니메이션', '지루', '재미없다', '스토리', '진부'],
 ['좋다', '의도', '다르다', '불쾌', '표현법'],
 ['줄리아', '로버츠', '귀엽다', '연인', '5년'],
 ['신선'],
 ['예술가', '사람', '인생', '당시', '시대', '상황', '느끼다', '명작'],
 ['관객', '너무', '아쉽다', '영화', '베테랑', '류승완', '감독', '역작', '강하다', '악역'],
 ['한창', '펭귄', '남북', '거짓', '평화로', '국민', '만들다', '영화'],
 ['지금', '보다'],
 ['여자', '해서', '죽다', '없다'],
 ['성룡', '단연', '고지'],
 [],
 ['감독', '의도', '전혀', '알아차리다'],
 ['하나님', '가정', '온전히', '만들다', '진리', '이신', '분이', '만들다', '영화', '보다', '마음', '보다'],
 ['흥미진진', '피다', '헤드', '죽다', '아쉽다'],
 ['국산', '코미디', '영화', '나다', '신라', '달밤', '제일', '좋다', '푸근', '따뜻'],
 ['최악', '영화', '오기', '지루'],
 ['탄탄', '배우', '걸다'],
 ['영화', '점점', '달려가다', '몰입', '도가', '높다', '영화', '이번', '처음'],
 ['결국', '감독', '자신', '의견', '지존파', '핑계', '삼다', '지존파', '살인', '정당화', '정부', '사회'],
 ['사실',
  '여부',
  '떠나다',
  '알다',
  '아더',
  '너무',
  '덜다',
  '원탁',
  '기사',
  '실제',
  '검술',
  '최고',
  '랜스',
  '알다',
  '있다',
  '트리스탄',
  '싸우다',
  '검술',
  '마치',
  '중국',
  '검술',
  '흉내',
  '내다',
  '같다',
  '란슬롯',
  '실제',
  '너무',
  '안대',
  '하트',
  '어역',
  '미스'],
 ['대한민국', '영화', '수준', '평균', '하락', '충분', '영상물'],
 ['없다'],
 ['재밌다'],
 ['재미없다', '기대', '완전', '완전', '실망'],
 ['종착역', '없다', '인생', '대유', '트레비', '슬다', '단지', '흘러가다'],
 ['시간', '아깝다', '영화'],
 ['없다', '예쁘다', '음악', '동영상', '취미', '영화', '만들다', '끝나다', '음악', '올인', '하기'],
 ['배우', '연기', '좋다', '걸다'],
 ['학위', '위조', '성범죄', '문제', '모으다', '영화', '찍다', '그러다', '제작비', '아끼다', '패자부활전'],
 ['솔직히'],
 ['완전', '재미있다', '보다', '알맞다'],
 ['잔인', '무섭다', '멋있다'],
 ['무섭다', '기분', '나쁘다'],
 ['군더더기', '없다', '깔끔', '강하다', '메세지', '전달', '뜻밖', '좋다', '영화'],
 ['영화', '최고', '그냥', '최고', '알다'],
 ['그랜드 부다페스트 호텔', '시리즈', '같다', '캐스팅', '아깝다'],
 ['빨리', '감기', '보다', '투자비', '많이', '들다', '같다', '영화사', '망하다'],
 ['도대체',
  '재밌다',
  '건지',
  '모르다',
  '아이언맨',
  '시리즈',
  '개그',
  '뛰어넘다',
  '웃다',
  '모르다',
  '내용',
  '뜨다',
  '없다',
  '히어로',
  '놀이',
  '이렇다',
  '평점',
  '높다',
  '모르다'],
 ['끌어가다',
  '중심',
  '있다',
  '캐릭터',
  '있다',
  '알다',
  '영화',
  '살인마',
  '대적',
  '사건',
  '해결',
  '인물',
  '없다',
  '마지막',
  '탈출',
  '나서다',
  '잡히다',
  '죽이다',
  '당하다',
  '이해',
  '없다',
  '대체',
  '조달환',
  '정유미',
  '나오다'],
 ['짜다', '리얼', '쓰레기', '영화', '보다', '나다', '정말', '영화', '절대', '보다'],
 ['비록',
  '로봇',
  '점차',
  '인간',
  '감정',
  '가지다',
  '자신',
  '대하다',
  '고민',
  '결국',
  '인간',
  '죽다',
  '앤드',
  '모습',
  '보다',
  '영화',
  '최고',
  '감동',
  '선사',
  '영화'],
 ['영구', '땡칠이', '시리즈', '레전드', '영화'],
 ['초딩',
  '친척',
  '비디오',
  '빌리다',
  '보다',
  '기억',
  '나다',
  '너무',
  '재미',
  '없다',
  '나중',
  '우연히',
  '다시',
  '보니',
  '재밌다',
  '그렇다',
  '재미',
  '없다',
  '초등학교',
  '학년',
  '사촌',
  '당시',
  '최신',
  '비디오',
  '빌리다',
  '같다'],
 ['지루', '고요', '서글프다', '선속', '머물다', '깊다', '성찰', '사색'],
 ['영화', '진짜', '보다', '펑펑', '울다', '너무', '슬프다', '같다'],
 ['짧다', '내기', '박빙', '같다'],
 ['딸리다', '심은하', '눈부시다', '미모', '아름답다', '영상', '메인 주', '제가'],
 ['나오다',
  '아직',
  '풀리다',

In [19]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, stratify = y, random_state = 42
)

In [20]:
# doc2vec은 문장 하나씩 ID를 붙여준다.
tagged = []
for idx, token in enumerate(X_train):
    # idx: 위치
    # token: 리스트의 원소
    tagged.append(
        TaggedDocument(words = token, tags = [f'DOC_{idx}'])
    )

tagged

[TaggedDocument(words=['아하'], tags=['DOC_0']),
 TaggedDocument(words=['개도', '아깝다'], tags=['DOC_1']),
 TaggedDocument(words=['어떻다', '평점', '낮다', '있다'], tags=['DOC_2']),
 TaggedDocument(words=['이영화', '논하다'], tags=['DOC_3']),
 TaggedDocument(words=['죄다', '없다'], tags=['DOC_4']),
 TaggedDocument(words=['가장', '어깨', '짊어지다', '책임감', '가장', '리얼', '표현', '영화', '여담', '이후', '조 루이스', '이전', '복싱', '황금기', '너무나', '표현', '진짜', '복싱', '춘추', '전국 시대'], tags=['DOC_5']),
 TaggedDocument(words=['린즈링', '너무', '이상', '영화', '쓰레기'], tags=['DOC_6']),
 TaggedDocument(words=['여자친구', '전쟁', '치루다'], tags=['DOC_7']),
 TaggedDocument(words=['솔직히', '이영화', '재미없다', '평점', '세상', '재미있다', '영화', '하나', '없다', '참고', '기똥차다', '즐겁다', '보다', '다음', '시리즈'], tags=['DOC_8']),
 TaggedDocument(words=['각본', '캐스팅', '전부', '완벽', '99년', '허준', '김재철', '전사', '장이', '발치', '리메이크', '해서', '망하다', '이제', '아무도', '기억', '드라마'], tags=['DOC_9']),
 TaggedDocument(words=['전쟁', '이후', '아픔', '그린', '영화', '마지막', '장면', '압권', '유대인', '알다', '더럽다', '도움', '필요', '하니', '동행', '토마스', '더럽다', '유태인', '장면', '유대인', '인척', '사실', '유대인', '가족사진', '보다', '미묘', '감정', '사슴', '인형', '밟다', '까다', '변한', '찌다', '영화'], tags=['DOC_10']),
 TaggedDocument(words=['특수', '효과', '없이', '관객', '납득', '능력'], tags=['DOC_11']),
 TaggedDocument(words=['게이', '인줄', '모르다', '보다'], tags=['DOC_12']),
 TaggedDocument(words=['과연'], tags=['DOC_13']),
 TaggedDocument(words=['조건', '편리', '따지다', '요즘', '세대', '진정', '사랑', '보다', '배우다', '영화'], tags=['DOC_14']),
 TaggedDocument(words=['너무너무', '귀엽다', '영화'], tags=['DOC_15']),
 TaggedDocument(words=['보다', '보다', '빠지다', '제니퍼 가너', '매력'], tags=['DOC_16']),
 TaggedDocument(words=['보다', '후회'], tags=['DOC_17']),
 TaggedDocument(words=['바다', '시원', '상쾌', '라이드', '기분'], tags=['DOC_18']),
 TaggedDocument(words=['향연'], tags=['DOC_19']),
 TaggedDocument(words=['진보', '외치', '보다', '영화'], tags=['DOC_20']),
 TaggedDocument(words=['인간', '너무', '재미없다'], tags=['DOC_21']),
 TaggedDocument(words=['임권택', '작품'], tags=['DOC_22']),
 TaggedDocument(words=['빅뱅', '사랑'], tags=['DOC_23']),
 TaggedDocument(words=['영화', '안보', '포스터', '보다', '주기', '아깝다'], tags=['DOC_24']),
 TaggedDocument(words=['보다', '시간', '무한도전', '보다'], tags=['DOC_25']),
 TaggedDocument(words=['영상미', '최고'], tags=['DOC_26']),
 TaggedDocument(words=['전편', '스토리', '여주', '연감'], tags=['DOC_27']),
 TaggedDocument(words=['좋다', '상술', '최고', '아니', '선거', '최고'], tags=['DOC_28']),
 TaggedDocument(words=['단체', '올누드', '마케팅', '요란', '기억'], tags=['DOC_29']),
 TaggedDocument(words=['차라리', '미니시리즈', '드라마', '만들다', '타임', '어쩌다', '없다', '알다'], tags=['DOC_30']),
 TaggedDocument(words=['시대', '맞다', '쓰다', '이러다', '받다', '쓰다', '황금', '시간대', '이렇다', '수신료', '공짜', '드라마', '접다', '가야', '놓다'], tags=['DOC_31']),
 TaggedDocument(words=['있다', '점수', '없다'], tags=['DOC_32']),
 TaggedDocument(words=['지나다', '다시', '보다', '영화', '다시', '보다', '순수', '사랑', '감동', '연기'], tags=['DOC_33']),
 TaggedDocument(words=['보다', '웃다', '가능'], tags=['DOC_34']),
 TaggedDocument(words=['보다', '많다', '따르다', '많다', '영화', '발전', '없다'], tags=['DOC_35']),
 TaggedDocument(words=['같이', '울다'], tags=['DOC_36']),
 TaggedDocument(words=['개봉', '보다', '오늘', '다시', '보다', '영화', '박쥐', '지금', '보다', '여전히', '세련', '기이', '특히', '배우', '연기력', '평점'], tags=['DOC_37']),
 TaggedDocument(words=['당시', '명필름', '부도', '직전', '몰다', '문제', '한동', '안이'], tags=['DOC_38']),
 TaggedDocument(words=['라이', '미치다', '사이코', '드라마'], tags=['DOC_39']),
 TaggedDocument(words=['아니', '일다'], tags=['DOC_40']),
 TaggedDocument(words=['이건', '모니', '제목', '보다', '뿜다'], tags=['DOC_41']),
 TaggedDocument(words=['일제', '사격', '대체', '나오다', '대본', '유명', '달리', '경찰', '명복', '바래다', '보다'], tags=['DOC_42']),
 TaggedDocument(words=['정말', '좋다', '영화', '항상', '보다'], tags=['DOC_43']),
 TaggedDocument(words=['정체성', '사치'], tags=['DOC_44']),
 TaggedDocument(words=['소재', '좋아서', '제작', '영화', '공포', '스릴러', '본분', '잊다', '드라마', '드라마', '같다', '느낌', '연기', '연출', '괜찮다', '시작', '지루', '장면', '살짝', '유치'], tags=['DOC_45']),
 TaggedDocument(words=['감독', '죽다', '진짜'], tags=['DOC_46']),
 TaggedDocument(words=['그냥', '별루', '극장', '안보', '다행'], tags=['DOC_47']),
 TaggedDocument(words=['엉망진창', '영화', '캐스팅', '아깝다'], tags=['DOC_48']),
 TaggedDocument(words=['너무', '재밌다'], tags=['DOC_49']),
 TaggedDocument(words=['재미없다', '여치', '짜증', '싸우다'], tags=['DOC_50']),
 TaggedDocument(words=['예원', '그만', '울다'], tags=['DOC_51']),
 TaggedDocument(words=['더빙', '장난', '화나'], tags=['DOC_52']),
 TaggedDocument(words=['괜찮다', '스릴러'], tags=['DOC_53']),
 TaggedDocument(words=['괜찮다', '영화', '평점', '너무', '낮다'], tags=['DOC_54']),
 TaggedDocument(words=['천국', '아름답다', '사랑'], tags=['DOC_55']),
 TaggedDocument(words=['비디오', '테잎', '감다', '보다', '영화', '가장', '슬프다', '영화'], tags=['DOC_56']),
 TaggedDocument(words=['엄청나다', '소름', '히치콕', '영화'], tags=['DOC_57']),
 TaggedDocument(words=['영웅', '사람', '원하다', '만들다', '희생', '자다'], tags=['DOC_58']),
 TaggedDocument(words=['재다', '있다', '사람', '낚이다', '낚이다'], tags=['DOC_59']),
 TaggedDocument(words=['양조위', '상관', '걸다'], tags=['DOC_60']),
 TaggedDocument(words=['푸다', '패다', '심지어', '보다', '만들다', '만들다'], tags=['DOC_61']),
 TaggedDocument(words=['윤소이', '얼굴', '짜증', '얼굴', '울상', '연기', '실력', '시다'], tags=['DOC_62']),
 TaggedDocument(words=['많다', '감동', '드라마'], tags=['DOC_63']),
 TaggedDocument(words=['요즘', '시험', '때려치다', '보다', '잇다', '어쩌다'], tags=['DOC_64']),
 TaggedDocument(words=['오늘', '보다', '진짜', '재미있다', '끝나다'], tags=['DOC_65']),
 TaggedDocument(words=['작가', '진짜', '주관', '없다', '같다', '생각', '없이', '막장', '만들다', '다시다', '보다'], tags=['DOC_66']),
 TaggedDocument(words=['따다', '영화', '찍다', '보다', '시간', '낭비', '인생', '접다', '따다', '틀다', '사람', '있다', '이유', '있다', '국어', '수업', '재미없다'], tags=['DOC_67']),
 TaggedDocument(words=['이건', '내용', '결말', '살다', '살다'], tags=['DOC_68']),
 TaggedDocument(words=['케빈 코스트너', '삽질', '작품'], tags=['DOC_69']),
 TaggedDocument(words=['시즌', '가다'], tags=['DOC_70']),
 TaggedDocument(words=['계몽영화', '한계', '고스', '답습'], tags=['DOC_71']),
 TaggedDocument(words=['실화', '너무', '가슴', '아프다'], tags=['DOC_72']),
 TaggedDocument(words=['별루'], tags=['DOC_73']),
 TaggedDocument(words=['진짜', '웃기다', '롭 슈나이더', '동물', '흉내', '너무', '웃기다'], tags=['DOC_74']),
 TaggedDocument(words=['전혀', '옛날', '영화', '같다', '행복', '좋다', '영화', '만들다'], tags=['DOC_75']),
 TaggedDocument(words=['강력', '추천'], tags=['DOC_76']),
 TaggedDocument(words=['나이', '먹다', '아저씨', '찌다', '놀이', '영화', '역겹다', '알바', '풀다', '현실감', '진짜', '제로'], tags=['DOC_77']),
 TaggedDocument(words=['이건', '한국', '영화', '미래', '설국열차', '웃기다', '감독', '다음', '작품', '가루지기', '최고', '명작', '정말', '아쉽다'], tags=['DOC_78']),
 TaggedDocument(words=['평점'], tags=['DOC_79']),
 TaggedDocument(words=['전형', '일본', '학원', '오바', '액션', '주연', '배우', '연기', '살리다', '정상', '향하다', '순수', '열정', '표현', '수작'], tags=['DOC_80']),
 TaggedDocument(words=['운지', '운지', '홍어', '홍어', '부릉부릉', '땅크', '나가다'], tags=['DOC_81']),
 TaggedDocument(words=['쓰다'], tags=['DOC_82']),
 TaggedDocument(words=['장르', '노도'], tags=['DOC_83']),
 TaggedDocument(words=['시시', '시간', '아깝다'], tags=['DOC_84']),
 TaggedDocument(words=['토마스', '하디', '시대', '서간', '작가', '잔인'], tags=['DOC_85']),
 TaggedDocument(words=['마술', '기전', '외계인', '만나', '있다'], tags=['DOC_86']),
 TaggedDocument(words=['삼가', '고인', '명복', '비다', '하늘', '가다', '편하다', '쉬다'], tags=['DOC_87']),
 TaggedDocument(words=['쓰레기', '채우다'], tags=['DOC_88']),
 TaggedDocument(words=['게이', '영화', '라고', '달다', '새롭다', '찾다', '다와', '유작', '내역', '보다', '반도', '보다', '나오다'], tags=['DOC_89']),
 TaggedDocument(words=['지금', '보다'], tags=['DOC_90']),
 TaggedDocument(words=['크리스 터커'], tags=['DOC_91']),
 TaggedDocument(words=['세상', '보이다', '보이다', '많다'], tags=['DOC_92']),
 TaggedDocument(words=['테이크', '환장', '지루', '영화'], tags=['DOC_93']),
 TaggedDocument(words=['사랑은 너무 복잡해', '다시', '시작', '보다', '새로', '시작', '단순'], tags=['DOC_94']),
 TaggedDocument(words=[], tags=['DOC_95']),
 TaggedDocument(words=['똑같다', '스토리', '혹시나', '역시', '나라', '남은', '스토리', '뻔하다', '보다', '고맙다', '작가', '글쓰기', '힘들다', '기왕', '힘들다', '쓰다', '참신', '쓰다', '지나다', '얘기', '습작', '지원', '오늘'], tags=['DOC_96']),
 TaggedDocument(words=['가슴', '먹먹', '반전', '약간', '혼란', '인간', '마무리', '특히', '영화', '장면', '연관', '의미', '가득', '끝나다', '생각', '들다', '영화', '막판', '아스카', '마음', '그대로', '읽히다', '가슴', '저리다', '영화'], tags=['DOC_97']),
 TaggedDocument(words=['컨저링', '다소', '미치다', '긴장감', '있다', '재밌다', '제임스', '감독', '확실히', '공포', '영화', '명장', '이자', '심리', '공포', '제작', '대가'], tags=['DOC_98']),
 TaggedDocument(words=['솔직히', '영화', '기대', '진짜', '인생', '영화', '늘다', '얼간이', '트루먼'], tags=['DOC_99']),
 TaggedDocument(words=['유럽', '영화', '이번', '정부', '많이', '들어오다', '즐겁다', '내용', '이리', '진부', '유럽', '영화', '소리'], tags=['DOC_100']),
 TaggedDocument(words=['가슴', '따뜻', '영화'], tags=['DOC_101']),
 TaggedDocument(words=['개인', '평점', '좋다', '원작', '배우', '영화', '만들다', '크다', '결정', '벨아미', '제목', '로버트', '패티', '슬다', '아름답다', '남자', '보이다'], tags=['DOC_102']),
 TaggedDocument(words=['상쾌', '발랄', '영화', '끌다', '소재', '유쾌', '해설'], tags=['DOC_103']),
 TaggedDocument(words=['슬프다', '가슴', '따뜻', '영화', '어둡다', '현실', '밝다', '풍경', '예쁘다', '마음', '가지다', '사람', '보다', '있다', '좋다', '이어지다', '훈훈', '소박', '일상', '아름답다', '느끼다'], tags=['DOC_104']),
 TaggedDocument(words=['학생', '선생님', '많이', '잇다', '보다', '앗다'], tags=['DOC_105']),
 TaggedDocument(words=['죽다', '재미없다'], tags=['DOC_106']),
 TaggedDocument(words=['어쩌다'], tags=['DOC_107']),
 TaggedDocument(words=['삼류', '포장', '일류', '최고'], tags=['DOC_108']),
 TaggedDocument(words=['정말', '아름답다', '영화'], tags=['DOC_109']),
 TaggedDocument(words=['꼬마', '안성기'], tags=['DOC_110']),
 TaggedDocument(words=['반도', '영화'], tags=['DOC_111']),
 TaggedDocument(words=['하숙집', '아줌마', '아줌마', '연인', '하숙', '아기', '갖다', '불쾌', '영화'], tags=['DOC_112']),
 TaggedDocument(words=['무조건', '보다'], tags=['DOC_113']),
 TaggedDocument(words=['이영화', '진짜', '제이슨', '영화'], tags=['DOC_114']),
 TaggedDocument(words=['영웅', '소재', '영화', '영웅', '색다르다', '그린', '코미디'], tags=['DOC_115']),
 TaggedDocument(words=['감동', '좋아하다', '보다', '영화', '좋다', '상영', '관이', '없다', '일주일', '내리다', '신분', '보시'], tags=['DOC_116']),
 TaggedDocument(words=['근무', '정도', '결말'], tags=['DOC_117']),
 TaggedDocument(words=['미국', '진짜', '선진국', '이유', '있다', '진짜', '멋지다', '최고'], tags=['DOC_118']),
 TaggedDocument(words=['이전', '이미', '보다', '신데렐라', '러브 스토리'], tags=['DOC_119']),
 TaggedDocument(words=['메시지', '정말', '특별', '영화'], tags=['DOC_120']),
 TaggedDocument(words=['독특', '한화', '면구', '성에', '만주', '스토리', '최악'], tags=['DOC_121']),
 TaggedDocument(words=['내다', '다운', '받다', '보다', '재다', '나다', '보다'], tags=['DOC_122']),
 TaggedDocument(words=['새벽', '보다', '재미없다', '이두용', '감독'], tags=['DOC_123']),
 TaggedDocument(words=['영화', '보다', '나다', '거울', '보다', '마지막', '장면', '리차드', '기어', '표정', '같다'], tags=['DOC_124']),
 TaggedDocument(words=['동민', '기대', '저버리다'], tags=['DOC_125']),
 TaggedDocument(words=['영화', '전용', '배우', '끌다', '로드', '킬링타임', '영화'], tags=['DOC_126']),
 TaggedDocument(words=['재미있다', '감동', '어른', '알다'], tags=['DOC_127']),
 TaggedDocument(words=['좋다', '인상', '깊다', '내용'], tags=['DOC_128']),
 TaggedDocument(words=['줄리', '델피', '나이', '들다', '멋지다'], tags=['DOC_129']),
 TaggedDocument(words=['스마트', '세번', '보다', '목도', '마음', '들다', '현실', '내용', '오다', '닿다', '좋다', '한편', '영화', '보다', '같다', '김지석', '연기'], tags=['DOC_130']),
 TaggedDocument(words=['오늘', '출연자', '스크린', '배경', '승천', '연상', '배경', '상당히', '기분', '좋다', '마지막', '출연자', '배경', '일장기', '연상', '배경', '일맥상통', '의도', '있다', '가요', '해명', '필요'], tags=['DOC_131']),
 TaggedDocument(words=['조르다', '허무', '딱지', '건지', '아깝다'], tags=['DOC_132']),
 TaggedDocument(words=['정말', '그대로', '영화'], tags=['DOC_133']),
 TaggedDocument(words=['어이없다'], tags=['DOC_134']),
 TaggedDocument(words=['헐리우드', '만들다', '정말', '멋지다', '영화', '모르다', '견자단', '표정', '연기', '행동', '연기', '기가', '막히다', '주윤발', '표정', '연기', '너무', '멋지다', '그놈', '3D', '망치다'], tags=['DOC_135']),
 TaggedDocument(words=['최고', '위트', '있다', '대사', '깔끔', '마무리', '신분', '보다'], tags=['DOC_136']),
 TaggedDocument(words=['영화', '필수', '요소', '재미'], tags=['DOC_137']),
 TaggedDocument(words=['주성치', '영화', '최고'], tags=['DOC_138']),
 TaggedDocument(words=['표현', '주제', '좋다', '영화', '이상', '영화'], tags=['DOC_139']),
 TaggedDocument(words=['세상', '살다', '시련'], tags=['DOC_140']),
 TaggedDocument(words=['평화', '도구', '쓰다'], tags=['DOC_141']),
 TaggedDocument(words=['소재', '낚이다'], tags=['DOC_142']),
 TaggedDocument(words=['공감', '없다', '영화', '과연', '전달', '이야기'], tags=['DOC_143']),
 TaggedDocument(words=['남자', '주연', '헤어', '스타일', '들다'], tags=['DOC_144']),
 TaggedDocument(words=['킹콩', '다음', '영화', '졸다', '경험', '안기다', '영화인'], tags=['DOC_145']),
 TaggedDocument(words=['작가', '정신', '나가다', '유령', '재미있다'], tags=['DOC_146']),
 TaggedDocument(words=['내용', '이상해'], tags=['DOC_147']),
 TaggedDocument(words=['지구', '멸망', '사수'], tags=['DOC_148']),
 TaggedDocument(words=['기대', '재다', '있다', '보다', '영화', '와이프', '용서'], tags=['DOC_149']),
 TaggedDocument(words=['용감', '순수', '성장', '다루다', '일본', '애니', '무디다', '마음', '꾸다', '만들다', '동화', '모험', '가슴', '뛰다', '살다', '만들다', '미미', '만남', '이별', '공존', '슬프다', '함께', '지금', '아름답다', '소중'], tags=['DOC_150']),
 TaggedDocument(words=['납치', '영화', '긴박', '없다', '싱겁다'], tags=['DOC_151']),
 TaggedDocument(words=['덕분', '빅뱅', '좋다', '재밌다'], tags=['DOC_152']),
 TaggedDocument(words=['교훈', '느끼다', '이영화', '보다', '원작', '너무', '좋다', '보다', '영화', '모자라다', '아버지', '어머니', '사이에서', '완득이', '대단'], tags=['DOC_153']),
 TaggedDocument(words=['헤어', '스타일', '저러다'], tags=['DOC_154']),
 TaggedDocument(words=['드라마', '잇다', '일요일', '아침', '빠지다'], tags=['DOC_155']),
 TaggedDocument(words=['재미', '잇다', '매우'], tags=['DOC_156']),
 TaggedDocument(words=['별로'], tags=['DOC_157']),
 TaggedDocument(words=['최수종', '유동근', '의형제', '너무', '감동', '받다', '드라마'], tags=['DOC_158']),
 TaggedDocument(words=['백성현', '최불암', '차인표', '전광렬', '그러다'], tags=['DOC_159']),
 TaggedDocument(words=['초고', '떠나다', '지겹다'], tags=['DOC_160']),
 TaggedDocument(words=['중학교', '시절', '요새', '다시', '생각', '찾아보다', '감회', '새롭다', '재밌다', '조금', '있다', '영화', '느낌', '이적', '갑자기', '아쉽다', '생각', '이드'], tags=['DOC_161']),
 TaggedDocument(words=['클라라', '볼라', '화신'], tags=['DOC_162']),
 TaggedDocument(words=['형용', '힘들다', '엉성', '황당'], tags=['DOC_163']),
 TaggedDocument(words=['마이너스', '없다', '보다', '영화', '수준', '북한', '만들다', '대다'], tags=['DOC_164']),
 TaggedDocument(words=['아주', '재미있다', '보다', '정말', '재미', '있다'], tags=['DOC_165']),
 TaggedDocument(words=['넌센스'], tags=['DOC_166']),
 TaggedDocument(words=['옛날', '워낭소리', '보다', '진짜', '많이', '울다'], tags=['DOC_167']),
 TaggedDocument(words=['재밌다', '평점', '낮다', '거지'], tags=['DOC_168']),
 TaggedDocument(words=['괜찮다', '작품'], tags=['DOC_169']),
 TaggedDocument(words=['남자', '인생', '대하다', '최고', '영화'], tags=['DOC_170']),
 TaggedDocument(words=['상당히', '재밌다', '보다'], tags=['DOC_171']),
 TaggedDocument(words=['저렇다', '만나다', '진짜', '사랑', '빠지다', '수도', '있다'], tags=['DOC_172']),
 TaggedDocument(words=['재밌다'], tags=['DOC_173']),
 TaggedDocument(words=['재치', '있다', '영화', '여주인공', '자연', '패션', '연기', '인상', '배우', '영화', '대한', '궁금증', '증폭'], tags=['DOC_174']),
 TaggedDocument(words=['영화', '이영화', '나쁘다'], tags=['DOC_175']),
 TaggedDocument(words=['대비'], tags=['DOC_176']),
 TaggedDocument(words=['쉽다', '사이', '잔잔', '감동', '있다', '영화', '마음', '여유', '생기다', '가을'], tags=['DOC_177']),
 TaggedDocument(words=['정말', '재미없다', '드라마'], tags=['DOC_178']),
 TaggedDocument(words=['영화', '홍상수', '찍다', '있다', '홍상수', '영화', '같다', '매력', '영화', '찾다', '없다'], tags=['DOC_179']),
 TaggedDocument(words=['미유키', '여배우', '빼다', '전부', '진부', '남자', '주인공', '보다', '그냥', '짜증', '나다', '결국', '영화', '더욱', '싫다'], tags=['DOC_180']),
 TaggedDocument(words=['일부', '괜찮다', '한국', '영화', '빼다', '해대', '한국', '영화', '만들다', '보다'], tags=['DOC_181']),
 TaggedDocument(words=['찍다'], tags=['DOC_182']),
 TaggedDocument(words=['하하하', '전무송', '괴다', '보다', '영화'], tags=['DOC_183']),
 TaggedDocument(words=['그냥', '저녁', '시정', '티브이', '정도', '보다', '끝내', '좋다', '영화', '티켓', '보다'], tags=['DOC_184']),
 TaggedDocument(words=['나오다', '보다'], tags=['DOC_185']),
 TaggedDocument(words=['이리', '쓰잘데', '없다', '장면', '많다', '편집', '너무', '그지', '같이', '지루'], tags=['DOC_186']),
 TaggedDocument(words=['몬스터 주식회사', '3D', '재밌다', '보다'], tags=['DOC_187']),
 TaggedDocument(words=['영화', '만들다'], tags=['DOC_188']),
 TaggedDocument(words=['플라이', '주인공'], tags=['DOC_189']),
 TaggedDocument(words=['인생', '최악', '한국', '영화', '괜히', '날리다', '생각'], tags=['DOC_190']),
 TaggedDocument(words=['뿜다', '깎다', '운동'], tags=['DOC_191']),
 TaggedDocument(words=['좋아하다', '자신', '좋아하다', '성취', '자체', '너무', '멋지다', '기회', '해보다'], tags=['DOC_192']),
 TaggedDocument(words=['평점', '가다', '울다', '재미없다'], tags=['DOC_193']),
 TaggedDocument(words=['찍다', '영화', '제작비'], tags=['DOC_194']),
 TaggedDocument(words=['러시아', '영화', '재미없다'], tags=['DOC_195']),
 TaggedDocument(words=['차승원', '열연', '돋보이다', '진부', '유치'], tags=['DOC_196']),
 TaggedDocument(words=['진짜', '시기', '영화', '그리움', '복잡', '특수', '효과', '없이', '스펙', '크다', '촬영'], tags=['DOC_197']),
 TaggedDocument(words=['이영화', '중학교', '보다', '학년', '보다', '진짜', '너무', '용암', '신기', '용암', '보다', '마지막', '남자', '주인공', '아저씨', '용암', '빠지다', '죽다'], tags=['DOC_198']),
 TaggedDocument(words=['계속', '울다'], tags=['DOC_199']),
 TaggedDocument(words=['이틀', '보다', '재밌다', '물건', '넣다', '조작', '열리다', '활짝', '열리다', '들어가다', '문자', '조작', '비번', '걸리다', '억지', '내용', '자체', '좋다'], tags=['DOC_200']),
 TaggedDocument(words=['막장', '들다'], tags=['DOC_201']),
 TaggedDocument(words=['시간', '아깝다', '영화'], tags=['DOC_202']),
 TaggedDocument(words=['미흡', '프랑스', '영화', '다운', '은은', '감동', '묻다', '나오다'], tags=['DOC_203']),
 TaggedDocument(words=['잔잔', '막히다', '영화', '연출', '대단', '곳곳', '숨다', '복선', '치밀', '정도', '섬세', '감정', '표현', '김영애', '연기'], tags=['DOC_204']),
 TaggedDocument(words=['쓰레기', '영화', '앞으로', '만들다'], tags=['DOC_205']),
 TaggedDocument(words=[], tags=['DOC_206']),
 TaggedDocument(words=['재다'], tags=['DOC_207']),
 TaggedDocument(words=['너무나', '따뜻', '감동', '영화'], tags=['DOC_208']),
 TaggedDocument(words=['속편', '안보', '재밌다', '보다', '잔인', '모르다', '당황', '특수', '카리스마', '개성', '없다', '속수무책', '당하다', '재밌다', '도저히', '납득', '안갑', '니다', '지루', '돌리다', '평점', '너무', '높다', '같다', '깎다', '개다', '시간', '아깝다'], tags=['DOC_209']),
 TaggedDocument(words=['주인공', '너무', '웃기다', '주인공', '맞다', '죽다', '긴장'], tags=['DOC_210']),
 TaggedDocument(words=['공포', '액션', '미스터리', '스릴러'], tags=['DOC_211']),
 TaggedDocument(words=['무섭다', '귀신', '애기', '건지', '그냥', '까다', '놀다', '하기'], tags=['DOC_212']),
 TaggedDocument(words=['카이', '시네마', '최고', '영화', '선정', '그만큼', '깊이', '있다', '영화'], tags=['DOC_213']),
 TaggedDocument(words=['자신', '대하다', '다시', '생각', '영화'], tags=['DOC_214']),
 TaggedDocument(words=['탄탄', '스토리', '훌륭', '배우', '연기', '호강', '액션', '놀라다', '반전', '있다', '장점', '모으다', '같다', '영화'], tags=['DOC_215']),
 TaggedDocument(words=['어줍잖다'], tags=['DOC_216']),
 TaggedDocument(words=['크다', '카다', '스토리', '매우', '뛰어나다'], tags=['DOC_217']),
 TaggedDocument(words=['작다', '하나에', '설레다', '학창', '시절', '그때', '느낌', '다시', '느끼다', '시간', '장면', '대사', '배경', '음악', '없다', '드라마'], tags=['DOC_218']),
 TaggedDocument(words=['아일랜드', '멋지다', '광경', '예쁘다', '멋지다', '주인공', '빼다', '보다', '없다', '영화', '아무리', '로맨틱', '코미디', '개연', '말다', '사람', '어떻다', '사랑', '빠지다', '전혀', '납득', '가다', '그놈', '더블린', '가다', '한국', '남극', '시간', '걸리다'], tags=['DOC_219']),
 TaggedDocument(words=['펼쳐지다', '세상'], tags=['DOC_220']),
 TaggedDocument(words=['재밌다', '별점', '이리', '은고'], tags=['DOC_221']),
 TaggedDocument(words=['기대', '재미있다', '검열', '흔적', '보이다', '아쉬움'], tags=['DOC_222']),
 TaggedDocument(words=['다시', '보다', '보다', '스릴', '넘치다', '감탄', '나오다', '영화'], tags=['DOC_223']),
 TaggedDocument(words=['이렇다', '평점', '높다'], tags=['DOC_224']),
 TaggedDocument(words=['겁나다', '재미', '지다', '보다'], tags=['DOC_225']),
 TaggedDocument(words=['사람', '명작', '칭송', '보다', '웃음', '나오다', '이렇다', '영화', '망하다', '관객', '정확', '포스터', '망하다', '참다', '영화', '나오다'], tags=['DOC_226']),
 TaggedDocument(words=['시간', '보다', '지우다', '평생'], tags=['DOC_227']),
 TaggedDocument(words=['나다', '정이안', '가다', '지루'], tags=['DOC_228']),
 TaggedDocument(words=['멋지다', '영화'], tags=['DOC_229']),
 TaggedDocument(words=['난리', '나다', '난리', '패션쇼', '장이', '영화'], tags=['DOC_230']),
 TaggedDocument(words=['영화', '사랑한다면', '처절', '열정', '불태우다', '사람', '만나', '보고 싶다', '맞다', '장면', '극복', '가능'], tags=['DOC_231']),
 TaggedDocument(words=['세다', '스티', '완전', '추다', '정말', '재밌다'], tags=['DOC_232']),
 TaggedDocument(words=['재밌다'], tags=['DOC_233']),
 TaggedDocument(words=['과거', '현재', '적절', '어우러지다', '역사', '흐름', '개인', '우정', '사랑', '현재', '이어지다', '보이다', '영화'], tags=['DOC_234']),
 TaggedDocument(words=['일단', '장르', '코미디', '없애다', '관리자'], tags=['DOC_235']),
 TaggedDocument(words=['추억', '돋다'], tags=['DOC_236']),
 TaggedDocument(words=['진짜', '까다', '부라리다', '쓰러지다'], tags=['DOC_237']),

In [21]:
len(tagged)

4000

In [22]:
model = Doc2Vec(
    documents = tagged,
    vector_size = 200,
    window = 5,
    min_count = 2,
    dm = 1,
    epochs = 50,
    seed = 42,
    negative = 5
)

In [23]:
X_train_vec = [model.infer_vector(data) for data in X_train]

In [24]:
X_test_vec = [model.infer_vector(data) for data in X_test]

In [25]:
logi = LogisticRegression(random_state = 42, max_iter = 2000)
svc = LinearSVC(random_state = 42)

In [26]:
logi.fit(X_train_vec, y_train)

LogisticRegression(max_iter=2000, random_state=42)

In [27]:
pred_logi = logi.predict(X_test_vec)

In [28]:
svc.fit(X_train_vec, y_train)

LinearSVC(random_state=42)

In [29]:
pred_svc = svc.predict(X_test_vec)

In [30]:
print('LogisticRegression')
print(classification_report(y_test, pred_logi))
print()
print('LinearSVC')
print(classification_report(y_test, pred_svc))

LogisticRegression
              precision    recall  f1-score   support

           0       0.74      0.72      0.73       500
           1       0.73      0.75      0.74       500

    accuracy                           0.74      1000
   macro avg       0.74      0.74      0.74      1000
weighted avg       0.74      0.74      0.74      1000


LinearSVC
              precision    recall  f1-score   support

           0       0.74      0.74      0.74       500
           1       0.74      0.74      0.74       500

    accuracy                           0.74      1000
   macro avg       0.74      0.74      0.74      1000
weighted avg       0.74      0.74      0.74      1000

##### **강사님 풀이**

In [31]:
df = pd.read_csv('../data/ratings_train.txt', sep = '\t')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        150000 non-null  int64
 1   document  149995 non-null  str
 2   label     150000 non-null  int64
dtypes: int64(2), str(1)
memory usage: 3.4 MB

In [32]:
df.dropna(inplace = True)

In [ ]:
# 텍스트 정규화 함수
# 나는 중복제거한 이후에 nomalize를 했고,
# 강사님은 nomalize를 하고 중복 제거를 하셨다.
    # 이랬더니 개수 차이가 400개? 가까이 났음... 성능은 1% 정도 차이... 오히려 내려감

def normalize(text):
    text = re.sub(r'[^가-힣0-9a-zA-Z\s\.]', ' ', str(text))     # 달라진 부분
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [ ]:
df['document'] = df['document'].map(normalize)

In [35]:
df = df.loc[
    ~(df['document'] == ''),
]

In [36]:
df.info()

<class 'pandas.DataFrame'>
Index: 149559 entries, 0 to 149999
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   id        149559 non-null  int64
 1   document  149559 non-null  str
 2   label     149559 non-null  int64
dtypes: int64(2), str(1)
memory usage: 4.6 MB

In [37]:
df.drop_duplicates('document', inplace = True)

In [38]:
allow_pos = ['NNP', 'NNG', 'VV', 'VA', 'MAG', 'XG']
stop_word = ['하다', '되다', '이다', '것', '수', '거']

In [39]:
komoran = Komoran()

In [40]:
def tokenize(text):
    tokens = []
    for word, pos in komoran.pos(text):
        if pos in allow_pos and word not in stop_word:
            tokens.append(word)
    return tokens

In [41]:
df3 = df.head(5000)

In [43]:
tokenize_sentence = [
    tokenize(text) for text in df3['document'].values
]

In [44]:
X = tokenize_sentence
y = df3['label'].values

In [45]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, stratify = y, random_state = 42
)

In [46]:
def tagged_docs(token_data):
    tagged = []
    for idx, toks in enumerate(token_data):
        # toks의 길이가 0이라면 학습에서 큰 의미가 없음 → 제외
        if len(toks) == 0:
            continue

        tagged.append(
            TaggedDocument(
                words = toks, tags = [f'DOC_{idx}']
            )
        )
    
    return tagged

In [47]:
X_train_tag = tagged_docs(X_train)

In [48]:
print(len(X_train_tag), len(X_train))

3920 4000

In [49]:
# Doc2Vec 객체 생성
model = Doc2Vec(
    documents = X_train_tag,
    vector_size = 200,
    window = 5,
    min_count = 2,
    negative = 5,
    seed = 42,
    epochs = 50
)

In [51]:
model2 = Doc2Vec(
    vector_size = 200,
    window = 5,
    min_count = 2,
    negative = 5,
    seed = 42,
    epochs = 50 
)

model2.build_vocab(X_train_tag)

model2.train(
    X_train_tag, total_examples = len(X_train_tag), epochs = 50
)

In [52]:
print(len(model.wv))
print(len(model2.wv))

2750
2750

In [53]:
print(len(model.dv))

3920

In [54]:
def infer_vector(model, norm_tokens, epochs = 50):
    # model: 임베딩 모델
    # norm_texts: 텍스트 정규화가 끝나고 토큰화가 완료된 데이터

    result = []

    for tokens in norm_tokens:
        if len(tokens) == 0:
            result.append(
                np.zeros(model.vector_size, dtype = np.float32)
            )
        else:
            vec = model.infer_vector(tokens, epochs = epochs)
            result.append(vec)
    
    return np.array(result)

In [55]:
X_train_vec = infer_vector(model, X_train)
X_test_vec = infer_vector(model, X_test)

In [56]:
X_train_vec.shape

(4000, 200)

In [57]:
def eval_clf(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    print(classification_report(y_test, pred))

In [58]:
logi = LogisticRegression(max_iter = 2000, random_state = 42)
svc = LinearSVC(random_state = 42)

In [59]:
eval_clf(logi, X_train_vec, X_test_vec, y_train, y_test)
eval_clf(svc, X_train_vec, X_test_vec, y_train, y_test)

              precision    recall  f1-score   support

           0       0.71      0.74      0.73       501
           1       0.73      0.70      0.71       499

    accuracy                           0.72      1000
   macro avg       0.72      0.72      0.72      1000
weighted avg       0.72      0.72      0.72      1000

              precision    recall  f1-score   support

           0       0.71      0.76      0.73       501
           1       0.74      0.70      0.72       499

    accuracy                           0.73      1000
   macro avg       0.73      0.73      0.73      1000
weighted avg       0.73      0.73      0.73      1000

In [60]:
df

              id                                           document  label
0        9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1        3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2       10265843                                  너무재밓었다그래서보는것을추천한다      0
3        9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4        6483659  사이몬페그의 익살스런 연기가 돋보였던 영화 스파이더맨에서 늙어보이기만 했던 커스틴 ...      1
...          ...                                                ...    ...
149995   6222902                                인간이 문제지.. 소는 뭔죄인가..      0
149996   8549745                                      평점이 너무 낮아서...      1
149997   9311800                      이게 뭐요 한국인은 거들먹거리고 필리핀 혼혈은 착하다      0
149998   2376369                        청춘 영화의 최고봉.방황과 우울했던 날들의 자화상      1
149999   9619869                           한국 영화 최초로 수간하는 내용이 담긴 영화      0

[144733 rows x 3 columns]

In [61]:
# DataFrame을 train, test 분할

train_df, test_df = train_test_split(
    df, test_size = 0.2, random_state = 42, stratify = df['label']
)

In [62]:
train_df['label'].value_counts()

label
0    58271
1    57515
Name: count, dtype: int64

In [63]:
test_df['label'].value_counts()

label
0    14568
1    14379
Name: count, dtype: int64