In [223]:
# 라이브러리 로드
import requests
from bs4 import BeautifulSoup as bs
import pandas as pd

#### 크롤링 예제

1. requests 라이브러리를 이용해서 `http://moons-86.iptime.org:8080/`에 요청을 보낸다.
2. 응답받은 데이터를 BeautifulSoup을 이용하여 데이터를 파싱
3. id가 product_1001인 태그를 찾아서 h2, p의 모든 콘텐츠 데이터를 추출한다.
4. 모든 상품의 정보를 추출
    - 데이터 프레임으로 생성
    - csv로 저장

In [3]:
# 1)

moons = requests.get('http://moons-86.iptime.org:8080/')

In [210]:
# 2)

soup = bs(moons.text, 'html.parser')

In [211]:
soup

<!DOCTYPE html>

<html lang="ko">
<head>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<title>웹 크롤링 수업용 샘플 페이지</title>
<style>
        body { font-family: 'Malgun Gothic', sans-serif; line-height: 1.6; padding: 20px; background-color: #f4f4f4; color: #333; }
        .container { max-width: 960px; margin: 0 auto; background-color: #fff; padding: 30px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }
        header { text-align: center; margin-bottom: 30px; }
        h1#page-title { color: #2c3e50; font-size: 2.5em; margin-bottom: 10px; }
        p#page-description { color: #7f8c8d; font-size: 1.1em; }
        .product-list { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 25px; margin-top: 30px; }
        .product-item { border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; background-color: #fff; transition: transform 0.2s ease-in-out; }
        .product-item:hover { transform: translateY(-5px); box-shadow: 0 4px 10px rgba(0,0,0,0.15); }
        .product-title { font-size: 1.5em; color: #34495e; margin-top: 0; margin-bottom: 10px; }
        .product-category { font-size: 0.9em; color: #95a5a6; margin-bottom: 5px; }
        .product-price { font-size: 1.3em; color: #e74c3c; font-weight: bold; margin-bottom: 15px; }
        .product-rating { color: #f39c12; font-size: 1.1em; margin-bottom: 10px; }
        .product-link { display: inline-block; background-color: #3498db; color: white; padding: 8px 15px; border-radius: 5px; text-decoration: none; font-size: 0.95em; }
        .product-link:hover { background-color: #2980b9; }
        footer { text-align: center; margin-top: 50px; padding-top: 20px; border-top: 1px solid #e0e0e0; color: #7f8c8d; font-size: 0.9em; }
    </style>
</head>
<body>
<div class="container">
<header>
<h1 id="page-title">인기 상품 목록</h1>
<p id="page-description">웹 크롤링 실습을 위한 가상의 상품 정보 페이지입니다.</p>
</header>
<main>
<div class="product-list">
<!-- 상품 1 -->
<div class="product-item" id="product-1001">
<h2 class="product-title">스마트 워치 X100</h2>
<p class="product-category">카테고리: 전자기기</p>
<p class="product-price">가격: 150,000원</p>
<p class="product-rating">평점: ★★★★☆ (4.5/5)</p>
<a class="product-link" href="/products/1001">상세 보기</a>
</div>
<!-- 상품 2 -->
<div class="product-item" id="product-1002">
<h2 class="product-title">무선 이어폰 Pro</h2>
<p class="product-category">카테고리: 전자기기</p>
<p class="product-price">가격: 89,000원</p>
<p class="product-rating">평점: ★★★★★ (5.0/5)</p>
<a class="product-link" href="/products/1002">상세 보기</a>
</div>
<!-- 상품 3 -->
<div class="product-item" id="product-1003">
<h2 class="product-title">고급 가죽 지갑</h2>
<p class="product-category">카테고리: 패션 잡화</p>
<p class="product-price">가격: 75,000원</p>
<p class="product-rating">평점: ★★★★☆ (4.0/5)</p>
<a class="product-link" href="/products/1003">상세 보기</a>
</div>
<!-- 상품 4 -->
<div class="product-item" id="product-1004">
<h2 class="product-title">에코백 디자인 컬렉션</h2>
<p class="product-category">카테고리: 패션 잡화</p>
<p class="product-price">가격: 25,000원</p>
<p class="product-rating">평점: ★★★★☆ (4.2/5)</p>
<a class="product-link" href="/products/1004">상세 보기</a>
</div>
<!-- 상품 5 -->
<div class="product-item" id="product-1005">
<h2 class="product-title">유기농 커피 원두 500g</h2>
<p class="product-category">카테고리: 식품</p>
<p class="product-price">가격: 18,000원</p>
<p class="product-rating">평점: ★★★★★ (4.8/5)</p>
<a class="product-link" href="/products/1005">상세 보기</a>
</div>
</div>
</main>
<footer>
<p id="footer-info">© 2026 가상 쇼핑몰.</p>
</footer>
</div>
</body>
</html>

In [212]:
# 3)

soup_1001 = soup.find('div', attrs = {'id':'product-1001'})

In [213]:
soup_list = soup_1001.find_all(['h2', 'p'])
soup_list

[<h2 class="product-title">스마트 워치 X100</h2>,
 <p class="product-category">카테고리: 전자기기</p>,
 <p class="product-price">가격: 150,000원</p>,
 <p class="product-rating">평점: ★★★★☆ (4.5/5)</p>]

In [156]:
soup_data = [data.get_text().strip() for data in soup_list]
soup_data

['스마트 워치 X100', '카테고리: 전자기기', '가격: 150,000원', '평점: ★★★★☆ (4.5/5)']

In [157]:
# 4)

product_list = soup.find_all('div', attrs={'class': 'product-item'})
product_list

[<div class="product-item" id="product-1001">
 <h2 class="product-title">스마트 워치 X100</h2>
 <p class="product-category">카테고리: 전자기기</p>
 <p class="product-price">가격: 150,000원</p>
 <p class="product-rating">평점: ★★★★☆ (4.5/5)</p>
 <a class="product-link" href="/products/1001">상세 보기</a>
 </div>,
 <div class="product-item" id="product-1002">
 <h2 class="product-title">무선 이어폰 Pro</h2>
 <p class="product-category">카테고리: 전자기기</p>
 <p class="product-price">가격: 89,000원</p>
 <p class="product-rating">평점: ★★★★★ (5.0/5)</p>
 <a class="product-link" href="/products/1002">상세 보기</a>
 </div>,
 <div class="product-item" id="product-1003">
 <h2 class="product-title">고급 가죽 지갑</h2>
 <p class="product-category">카테고리: 패션 잡화</p>
 <p class="product-price">가격: 75,000원</p>
 <p class="product-rating">평점: ★★★★☆ (4.0/5)</p>
 <a class="product-link" href="/products/1003">상세 보기</a>
 </div>,
 <div class="product-item" id="product-1004">
 <h2 class="product-title">에코백 디자인 컬렉션</h2>
 <p class="product-category">카테고리: 패션 잡화</p>
 <p class="product-price">가격: 25,000원</p>
 <p class="product-rating">평점: ★★★★☆ (4.2/5)</p>
 <a class="product-link" href="/products/1004">상세 보기</a>
 </div>,
 <div class="product-item" id="product-1005">
 <h2 class="product-title">유기농 커피 원두 500g</h2>
 <p class="product-category">카테고리: 식품</p>
 <p class="product-price">가격: 18,000원</p>
 <p class="product-rating">평점: ★★★★★ (4.8/5)</p>
 <a class="product-link" href="/products/1005">상세 보기</a>
 </div>]

In [194]:
all_data = [data.get_text().strip() for data in product_list]
all_data2 = [data.split('\n') for data in all_data]
all_data2

[['스마트 워치 X100', '카테고리: 전자기기', '가격: 150,000원', '평점: ★★★★☆ (4.5/5)', '상세 보기'],
 ['무선 이어폰 Pro', '카테고리: 전자기기', '가격: 89,000원', '평점: ★★★★★ (5.0/5)', '상세 보기'],
 ['고급 가죽 지갑', '카테고리: 패션 잡화', '가격: 75,000원', '평점: ★★★★☆ (4.0/5)', '상세 보기'],
 ['에코백 디자인 컬렉션', '카테고리: 패션 잡화', '가격: 25,000원', '평점: ★★★★☆ (4.2/5)', '상세 보기'],
 ['유기농 커피 원두 500g', '카테고리: 식품', '가격: 18,000원', '평점: ★★★★★ (4.8/5)', '상세 보기']]

In [195]:
for i in range(0, 5):
    for j in range(0, 5):
        all_data2[i][j] = all_data2[i][j].split(': ')

In [196]:
all_data2

[[['스마트 워치 X100'],
  ['카테고리', '전자기기'],
  ['가격', '150,000원'],
  ['평점', '★★★★☆ (4.5/5)'],
  ['상세 보기']],
 [['무선 이어폰 Pro'],
  ['카테고리', '전자기기'],
  ['가격', '89,000원'],
  ['평점', '★★★★★ (5.0/5)'],
  ['상세 보기']],
 [['고급 가죽 지갑'],
  ['카테고리', '패션 잡화'],
  ['가격', '75,000원'],
  ['평점', '★★★★☆ (4.0/5)'],
  ['상세 보기']],
 [['에코백 디자인 컬렉션'],
  ['카테고리', '패션 잡화'],
  ['가격', '25,000원'],
  ['평점', '★★★★☆ (4.2/5)'],
  ['상세 보기']],
 [['유기농 커피 원두 500g'],
  ['카테고리', '식품'],
  ['가격', '18,000원'],
  ['평점', '★★★★★ (4.8/5)'],
  ['상세 보기']]]

In [197]:
for i in range(0, 5):
    for j in range(1, 4):
        all_data2[i][j].remove(all_data2[i][j][0])

In [198]:
all_data2

[[['스마트 워치 X100'], ['전자기기'], ['150,000원'], ['★★★★☆ (4.5/5)'], ['상세 보기']],
 [['무선 이어폰 Pro'], ['전자기기'], ['89,000원'], ['★★★★★ (5.0/5)'], ['상세 보기']],
 [['고급 가죽 지갑'], ['패션 잡화'], ['75,000원'], ['★★★★☆ (4.0/5)'], ['상세 보기']],
 [['에코백 디자인 컬렉션'], ['패션 잡화'], ['25,000원'], ['★★★★☆ (4.2/5)'], ['상세 보기']],
 [['유기농 커피 원두 500g'], ['식품'], ['18,000원'], ['★★★★★ (4.8/5)'], ['상세 보기']]]

In [199]:
all_df2 = pd.DataFrame(all_data2)
all_df2

                  0        1           2                3        4
0     [스마트 워치 X100]   [전자기기]  [150,000원]  [★★★★☆ (4.5/5)]  [상세 보기]
1      [무선 이어폰 Pro]   [전자기기]   [89,000원]  [★★★★★ (5.0/5)]  [상세 보기]
2        [고급 가죽 지갑]  [패션 잡화]   [75,000원]  [★★★★☆ (4.0/5)]  [상세 보기]
3     [에코백 디자인 컬렉션]  [패션 잡화]   [25,000원]  [★★★★☆ (4.2/5)]  [상세 보기]
4  [유기농 커피 원두 500g]     [식품]   [18,000원]  [★★★★★ (4.8/5)]  [상세 보기]

In [200]:
all_df2 = all_df2.drop(columns=4)

In [201]:
all_df3 = all_df2.copy()

In [202]:
all_df3

                  0        1           2                3
0     [스마트 워치 X100]   [전자기기]  [150,000원]  [★★★★☆ (4.5/5)]
1      [무선 이어폰 Pro]   [전자기기]   [89,000원]  [★★★★★ (5.0/5)]
2        [고급 가죽 지갑]  [패션 잡화]   [75,000원]  [★★★★☆ (4.0/5)]
3     [에코백 디자인 컬렉션]  [패션 잡화]   [25,000원]  [★★★★☆ (4.2/5)]
4  [유기농 커피 원두 500g]     [식품]   [18,000원]  [★★★★★ (4.8/5)]

In [203]:
all_df3.columns = ['상품명', '카테고리', '가격', '평점']

In [204]:
all_df3

                상품명     카테고리          가격               평점
0     [스마트 워치 X100]   [전자기기]  [150,000원]  [★★★★☆ (4.5/5)]
1      [무선 이어폰 Pro]   [전자기기]   [89,000원]  [★★★★★ (5.0/5)]
2        [고급 가죽 지갑]  [패션 잡화]   [75,000원]  [★★★★☆ (4.0/5)]
3     [에코백 디자인 컬렉션]  [패션 잡화]   [25,000원]  [★★★★☆ (4.2/5)]
4  [유기농 커피 원두 500g]     [식품]   [18,000원]  [★★★★★ (4.8/5)]

#### 강사님 풀이 (제대로 못 적음)

In [ ]:
# 1)
res = requests.get('http://moons-86.iptime.org:8080/')
# 2)
soup = bs(res.text, 'html.parser')

In [216]:
# 3)
div_data = soup.find('div', attrs = {'id':'product-1001'})

In [217]:
div_data.get_text().split('\n')

['',
 '스마트 워치 X100',
 '카테고리: 전자기기',
 '가격: 150,000원',
 '평점: ★★★★☆ (4.5/5)',
 '상세 보기',
 '']

In [219]:
p_list = div_data.find_all(
    ['h2', 'p']
)

p_list

[<h2 class="product-title">스마트 워치 X100</h2>,
 <p class="product-category">카테고리: 전자기기</p>,
 <p class="product-price">가격: 150,000원</p>,
 <p class="product-rating">평점: ★★★★☆ (4.5/5)</p>]

In [220]:
[p.get_text() for p in p_list]

['스마트 워치 X100', '카테고리: 전자기기', '가격: 150,000원', '평점: ★★★★☆ (4.5/5)']

In [221]:
div_list = soup.find_all('div', attrs = {'class':'product-item'})

In [222]:
div_list

[<div class="product-item" id="product-1001">
 <h2 class="product-title">스마트 워치 X100</h2>
 <p class="product-category">카테고리: 전자기기</p>
 <p class="product-price">가격: 150,000원</p>
 <p class="product-rating">평점: ★★★★☆ (4.5/5)</p>
 <a class="product-link" href="/products/1001">상세 보기</a>
 </div>,
 <div class="product-item" id="product-1002">
 <h2 class="product-title">무선 이어폰 Pro</h2>
 <p class="product-category">카테고리: 전자기기</p>
 <p class="product-price">가격: 89,000원</p>
 <p class="product-rating">평점: ★★★★★ (5.0/5)</p>
 <a class="product-link" href="/products/1002">상세 보기</a>
 </div>,
 <div class="product-item" id="product-1003">
 <h2 class="product-title">고급 가죽 지갑</h2>
 <p class="product-category">카테고리: 패션 잡화</p>
 <p class="product-price">가격: 75,000원</p>
 <p class="product-rating">평점: ★★★★☆ (4.0/5)</p>
 <a class="product-link" href="/products/1003">상세 보기</a>
 </div>,
 <div class="product-item" id="product-1004">
 <h2 class="product-title">에코백 디자인 컬렉션</h2>
 <p class="product-category">카테고리: 패션 잡화</p>
 <p class="product-price">가격: 25,000원</p>
 <p class="product-rating">평점: ★★★★☆ (4.2/5)</p>
 <a class="product-link" href="/products/1004">상세 보기</a>
 </div>,
 <div class="product-item" id="product-1005">
 <h2 class="product-title">유기농 커피 원두 500g</h2>
 <p class="product-category">카테고리: 식품</p>
 <p class="product-price">가격: 18,000원</p>
 <p class="product-rating">평점: ★★★★★ (4.8/5)</p>
 <a class="product-link" href="/products/1005">상세 보기</a>
 </div>]

In [ ]:
values = []

for div in div_list:
    p_list = div.find_all(
        ['h2', 'p']
    )

    value = [p.get_text() for p in p_list]
    values.append(value)

values

[['스마트 워치 X100', '카테고리: 전자기기', '가격: 150,000원', '평점: ★★★★☆ (4.5/5)'],
 ['무선 이어폰 Pro', '카테고리: 전자기기', '가격: 89,000원', '평점: ★★★★★ (5.0/5)'],
 ['고급 가죽 지갑', '카테고리: 패션 잡화', '가격: 75,000원', '평점: ★★★★☆ (4.0/5)'],
 ['에코백 디자인 컬렉션', '카테고리: 패션 잡화', '가격: 25,000원', '평점: ★★★★☆ (4.2/5)'],
 ['유기농 커피 원두 500g', '카테고리: 식품', '가격: 18,000원', '평점: ★★★★★ (4.8/5)']]

In [191]:
df = pd.DataFrame(
    values,
    columns = ['상품명', '카테고리', '가격', '평점']
)

In [192]:
df

              상품명         카테고리            가격                 평점
0     스마트 워치 X100   카테고리: 전자기기  가격: 150,000원  평점: ★★★★☆ (4.5/5)
1      무선 이어폰 Pro   카테고리: 전자기기   가격: 89,000원  평점: ★★★★★ (5.0/5)
2        고급 가죽 지갑  카테고리: 패션 잡화   가격: 75,000원  평점: ★★★★☆ (4.0/5)
3     에코백 디자인 컬렉션  카테고리: 패션 잡화   가격: 25,000원  평점: ★★★★☆ (4.2/5)
4  유기농 커피 원두 500g     카테고리: 식품   가격: 18,000원  평점: ★★★★★ (4.8/5)

### <b> <font color=red> 강사님이 깃헙에 올린 코드</font>

### 강사님 풀이2

In [224]:
res = requests.get('http://moons-86.iptime.org:8080/')
soup = bs(res.text, 'html.parser')

In [226]:
# 접근 방식 2 → 상품명, 카테고리, 가격, 평점, 하이퍼링크를
# 각각의 class의 값들로 접근하여 df 생성
# product-list class를 가진 div를 추출
    # (모든 상품의 정보가 담겨있는 div 영역을 선택)

div_data = soup.find(
    'div',
    attrs = {
        'class': 'product-list'
    }
)

In [229]:
# 상품명에 접근: class의 값이 product-title인 태그에 접근

title_list = div_data.find_all(
    attrs = {
        'class' : 'product-title'
    }
)

In [231]:
# 어느 경우에 get_text() 를 써도 되는지 확인하기 위해 독자적으로 수행
type(title_list)

bs4.element.ResultSet

In [230]:
[title.get_text() for title in title_list]

['스마트 워치 X100', '무선 이어폰 Pro', '고급 가죽 지갑', '에코백 디자인 컬렉션', '유기농 커피 원두 500g']

In [232]:
# a 태그에서 href라는 속성의 값을 추출하려면? → Tag['속성명']

link_list = div_data.find_all(
    attrs= {
        'class': 'product-link'
    }
)

In [234]:
links = []
for link in link_list:
    # print('http://moons-86.iptime.org:8080/' + link['href'])
    links.append('http://moons-86.iptime.org:8080/' + link['href'])

In [235]:
links

['http://moons-86.iptime.org:8080//products/1001',
 'http://moons-86.iptime.org:8080//products/1002',
 'http://moons-86.iptime.org:8080//products/1003',
 'http://moons-86.iptime.org:8080//products/1004',
 'http://moons-86.iptime.org:8080//products/1005']

In [236]:
class_list = ['product-title', 'product-category', 'product-price', 'product-rating', 'product-link']
base_url = 'http://moons-86.iptime.org:8080'
dict_data = {}

# 반복 실행하면서 빈 딕셔너리에 key:[] 값들을 추가
for cls in class_list:
    _list = div_data.find_all(
        attrs = {
            'class': cls
        }
    )

    # cls가 product-link라면 href 속성의 값들을 리스트로 생성
    if cls == 'product-link':
        value = [base_url + link['href'] for link in _list]
    else:
        value = [data.get_text().split(': ')[-1] for data in _list]
    
    # key 값은 cls에서 -로 잘라주고 뒤의 값들을 사용
    key_data = cls.split('-')[-1]
    dict_data[key_data] = value

dict_data

{'title': ['스마트 워치 X100',
  '무선 이어폰 Pro',
  '고급 가죽 지갑',
  '에코백 디자인 컬렉션',
  '유기농 커피 원두 500g'],
 'category': ['전자기기', '전자기기', '패션 잡화', '패션 잡화', '식품'],
 'price': ['150,000원', '89,000원', '75,000원', '25,000원', '18,000원'],
 'rating': ['★★★★☆ (4.5/5)',
  '★★★★★ (5.0/5)',
  '★★★★☆ (4.0/5)',
  '★★★★☆ (4.2/5)',
  '★★★★★ (4.8/5)'],
 'link': ['http://moons-86.iptime.org:8080/products/1001',
  'http://moons-86.iptime.org:8080/products/1002',
  'http://moons-86.iptime.org:8080/products/1003',
  'http://moons-86.iptime.org:8080/products/1004',
  'http://moons-86.iptime.org:8080/products/1005']}

In [247]:
df2 = pd.DataFrame(dict_data)
df2

,title,category,price,rating,link
0,스마트 워치 X100,전자기기,"150,000원",★★★★☆ (4.5/5),http://moons-86.iptime.org:8080/products/1001
1,무선 이어폰 Pro,전자기기,"89,000원",★★★★★ (5.0/5),http://moons-86.iptime.org:8080/products/1002
2,고급 가죽 지갑,패션 잡화,"75,000원",★★★★☆ (4.0/5),http://moons-86.iptime.org:8080/products/1003
3,에코백 디자인 컬렉션,패션 잡화,"25,000원",★★★★☆ (4.2/5),http://moons-86.iptime.org:8080/products/1004
4,유기농 커피 원두 500g,식품,"18,000원",★★★★★ (4.8/5),http://moons-86.iptime.org:8080/products/1005

In [ ]:
# csv 파일로 저장 시 기본값으로 인덱스가 포함되어 저장
    # 인덱스가 의미를 가지고 있을 수 있기 때문

df2.to_csv('test.csv')

In [248]:
df2.to_csv('test_clean.csv', index=False)

In [ ]:
# csv 파일에 인덱스(이름 없는 인덱스) 부분이 저장되어 있는 경우

df2 = pd.read_csv('test.csv')
df2

,Unnamed: 0,title,category,price,rating,link
0,0,스마트 워치 X100,전자기기,"150,000원",★★★★☆ (4.5/5),http://moons-86.iptime.org:8080/products/1001
1,1,무선 이어폰 Pro,전자기기,"89,000원",★★★★★ (5.0/5),http://moons-86.iptime.org:8080/products/1002
2,2,고급 가죽 지갑,패션 잡화,"75,000원",★★★★☆ (4.0/5),http://moons-86.iptime.org:8080/products/1003
3,3,에코백 디자인 컬렉션,패션 잡화,"25,000원",★★★★☆ (4.2/5),http://moons-86.iptime.org:8080/products/1004
4,4,유기농 커피 원두 500g,식품,"18,000원",★★★★★ (4.8/5),http://moons-86.iptime.org:8080/products/1005

In [241]:
df3 = pd.read_csv('test.csv', index_col=0)
df3

,title,category,price,rating,link
0,스마트 워치 X100,전자기기,"150,000원",★★★★☆ (4.5/5),http://moons-86.iptime.org:8080/products/1001
1,무선 이어폰 Pro,전자기기,"89,000원",★★★★★ (5.0/5),http://moons-86.iptime.org:8080/products/1002
2,고급 가죽 지갑,패션 잡화,"75,000원",★★★★☆ (4.0/5),http://moons-86.iptime.org:8080/products/1003
3,에코백 디자인 컬렉션,패션 잡화,"25,000원",★★★★☆ (4.2/5),http://moons-86.iptime.org:8080/products/1004
4,유기농 커피 원두 500g,식품,"18,000원",★★★★★ (4.8/5),http://moons-86.iptime.org:8080/products/1005

In [249]:
df4 = pd.read_csv('test_clean.csv')
df4

,title,category,price,rating,link
0,스마트 워치 X100,전자기기,"150,000원",★★★★☆ (4.5/5),http://moons-86.iptime.org:8080/products/1001
1,무선 이어폰 Pro,전자기기,"89,000원",★★★★★ (5.0/5),http://moons-86.iptime.org:8080/products/1002
2,고급 가죽 지갑,패션 잡화,"75,000원",★★★★☆ (4.0/5),http://moons-86.iptime.org:8080/products/1003
3,에코백 디자인 컬렉션,패션 잡화,"25,000원",★★★★☆ (4.2/5),http://moons-86.iptime.org:8080/products/1004
4,유기농 커피 원두 500g,식품,"18,000원",★★★★★ (4.8/5),http://moons-86.iptime.org:8080/products/1005